import {types as utilTypes} from "node:util";
import type {ExtensionAPI} from "@earendil-works/pi-coding-agent";
import {truncateHead} from "@earendil-works/pi-coding-agent";
import {StringEnum} from "@earendil-works/pi-ai/compat";
import {Type,type Static} from "typebox";
import type {AcademicAcquisitionResult,AcademicFetchInput,AcademicSearchInput,NormalizedAcquisitionOptionsInternal} from "../../../src/acquisition/contracts.js";
import {
 AcademicToolError,academicRenderInvariantInternal,assertAcademicSessionCallContinuationInternal,assertAcademicSessionManagerLifecycleInternal,awaitAcademicSessionContinuationInternal,createAcademicSessionManager,createAcademicToolDependencies,createDefaultAcademicToolDependencies,
 detachAcademicSessionManagerInternal,freshAcademicToolErrorInternal,getAcademicSessionNormalizedOptionsInternal,getAcademicToolDependenciesInternal,mapAcademicRenderErrorInternal,
 type AcademicSessionManager,type AcademicToolDependencies,type AcademicToolDependenciesDescriptor,type AcademicToolErrorCode,
} from "../acquisition-session.js";
export {AcademicToolError,createAcademicSessionManager,createAcademicToolDependencies,createDefaultAcademicToolDependencies};
export type {AcademicSessionManager,AcademicToolDependencies,AcademicToolDependenciesDescriptor,AcademicToolErrorCode};

export const AcademicSearchToolParameters=Type.Object({queries:Type.Array(Type.String(),{minItems:1,maxItems:16}),providers:Type.Optional(Type.Array(StringEnum(["crossref","openalex","pubmed"] as const),{maxItems:3})),maxResultsPerQuery:Type.Optional(Type.Integer({minimum:1,maximum:100})),publicationTypes:Type.Optional(Type.Array(StringEnum(["journal-article","review","dataset","other"] as const),{maxItems:4})),fromYear:Type.Optional(Type.Integer({minimum:1,maximum:9999})),toYear:Type.Optional(Type.Integer({minimum:1,maximum:9999}))},{additionalProperties:false});
export const AcademicFetchToolParameters=Type.Object({identifierKind:StringEnum(["doi","pmid","pmcid"] as const),identifier:Type.String()},{additionalProperties:false});
export type AcademicSearchToolInput=Static<typeof AcademicSearchToolParameters>;
export type AcademicFetchToolInput=Static<typeof AcademicFetchToolParameters>;

type CompactDetails=Readonly<{schemaVersion:1;provenanceStatus:"uncommitted";status:"complete"|"partial";partitions:AcademicAcquisitionResult["partitions"];candidateGroups:readonly unknown[];candidates:readonly unknown[];documents:readonly unknown[];traces:readonly unknown[];failures:readonly unknown[];omitted:Readonly<{candidateGroups:number;candidates:number;documents:number;traces:number;failures:number}>;optionsSha256:string}>;
function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const descriptor of Object.values(Object.getOwnPropertyDescriptors(value as object)))if("value" in descriptor)freeze(descriptor.value);Object.freeze(value);}return value;}
const byteLength=(value:string):number=>Buffer.byteLength(value,"utf8"),IS_WELL_FORMED=(String.prototype as unknown as {isWellFormed:()=>boolean}).isWellFormed;
function wellFormed(value:string):boolean{return IS_WELL_FORMED.call(value);}
function safeString(value:string):string{if(!wellFormed(value))return academicRenderInvariantInternal();return value;}
function compactDetails(result:AcademicAcquisitionResult,maximum:number):CompactDetails{const groups:unknown[]=[],candidates:unknown[]=[],documents:unknown[]=[],traces:unknown[]=[],failures:unknown[]=[];const base={schemaVersion:1 as const,provenanceStatus:"uncommitted" as const,status:result.status,partitions:{...result.partitions},candidateGroups:groups,candidates,documents,traces,failures,omitted:{candidateGroups:0,candidates:0,documents:0,traces:0,failures:0},optionsSha256:result.optionsSha256};const fits=()=>{const text=JSON.stringify(base);return wellFormed(text)&&byteLength(text)<=maximum;};const add=(target:unknown[],value:unknown):boolean=>{target.push(value);if(fits())return true;target.pop();return false;};for(const item of result.candidateGroups)if(!add(groups,{groupKey:item.groupKey,identityKind:item.identityKind,status:item.status,candidateKeys:item.candidateKeys.slice(0,16)}))break;for(const item of result.candidates)if(!add(candidates,{candidateKey:item.candidateKey,provider:item.provider,accessLevel:item.accessLevel,identifiers:{...item.identifiers},publicationType:item.publicationType,published:{...item.published},traceKey:item.traceKey}))break;for(const item of result.documents)if(!add(documents,{documentKey:item.documentKey,pmcid:item.pmcid,candidateKey:item.candidateKey,accessLevel:item.accessLevel,sectionCount:item.sections.length,traceKey:item.traceKey}))break;for(const item of result.traces){const settlement=item.settlement;if(!add(traces,{traceKey:item.traceKey,provider:item.provider,operation:item.operation,endpointClass:item.endpointClass,accessLevel:item.accessLevel,settlement:{outcome:settlement.outcome,code:settlement.code,requestedUrl:{...settlement.requestedUrl},finalUrl:settlement.finalUrl===null?null:{...settlement.finalUrl},redirects:settlement.redirects.map(redirect=>({ordinal:redirect.ordinal,status:redirect.status,from:{...redirect.from},to:{...redirect.to}})),httpStatus:settlement.httpStatus,encodedBytes:settlement.encodedBytes,decodedBytes:settlement.decodedBytes,responsePayloadSha256:settlement.responsePayloadSha256,retrievedAt:settlement.retrievedAt},warnings:item.warnings.map(warning=>({...warning}))}))break;}for(const item of result.failures)if(!add(failures,{provider:item.provider,operation:item.operation,partitionKeySha256:item.partitionKeySha256,code:item.code,retryable:item.retryable}))break;(base.omitted as Record<string,number>).candidateGroups=result.candidateGroups.length-groups.length;(base.omitted as Record<string,number>).candidates=result.candidates.length-candidates.length;(base.omitted as Record<string,number>).documents=result.documents.length-documents.length;(base.omitted as Record<string,number>).traces=result.traces.length-traces.length;(base.omitted as Record<string,number>).failures=result.failures.length-failures.length;if(!fits())return academicRenderInvariantInternal();return freeze(base) as CompactDetails;}
function renderInternal(result:AcademicAcquisitionResult,options:NormalizedAcquisitionOptionsInternal):{content:{type:"text";text:string}[];details:CompactDetails}{
 const mandatory=["[UNCOMMITTED PROVENANCE] Metadata discovery only; admit/cite evidence through a future explicit research run.",`Status: ${result.status}`,`Partitions: requested=${result.partitions.requested} dispatched=${result.partitions.dispatched} succeeded=${result.partitions.succeeded} failed=${result.partitions.failed} blocked=${result.partitions.blocked}`,`Candidate groups: ${result.candidateGroups.length}; candidates=${result.candidates.length}; documents=${result.documents.length}`,`Provider witnesses: total=${result.traces.length}`];for(const line of mandatory)safeString(line);const lines=[...mandatory];let text=lines.join("\n"),bytes=byteLength(text);if(lines.length>options.maxVisibleLines||bytes>options.maxVisibleBytes)return academicRenderInvariantInternal();
 const append=(line:string):boolean=>{safeString(line);const extra=byteLength(`\n${line}`);if(lines.length+1>options.maxVisibleLines||bytes+extra>options.maxVisibleBytes)return false;lines.push(line);bytes+=extra;return true;};
 for(const group of result.candidateGroups)if(!append(`Group ${group.identityKind}/${group.status}: ${group.candidateKeys.length} candidate(s)`))break;
 for(const candidate of result.candidates){const ids=[candidate.identifiers.doi&&`doi:${candidate.identifiers.doi}`,candidate.identifiers.pmid&&`pmid:${candidate.identifiers.pmid}`,candidate.identifiers.pmcid&&`pmcid:${candidate.identifiers.pmcid}`].filter(Boolean).join(", ")||"none";if(!append(`Identifiers [${candidate.provider}] access=${candidate.accessLevel}: ${ids}`))break;}
 for(const document of result.documents)if(!append(`Document ${document.pmcid}: access=${document.accessLevel}, sections=${document.sections.length}`))break;
 for(const trace of result.traces)if(!append(`- ${trace.provider}/${trace.endpointClass}: ${trace.settlement.outcome}/${trace.settlement.code} ${trace.settlement.requestedUrl.canonicalUrl}`))break;
 for(const failure of result.failures)if(!append(`Failure ${failure.provider}: ${failure.code} retryable=${failure.retryable}`))break;
 text=lines.join("\n");const truncated=truncateHead(text,{maxBytes:options.maxVisibleBytes,maxLines:options.maxVisibleLines});if(truncated.truncated||truncated.content!==text||truncated.outputBytes!==byteLength(text)||truncated.outputLines!==lines.length||!wellFormed(text))return academicRenderInvariantInternal();const details=compactDetails(result,options.maxVisibleBytes);return freeze({content:Object.freeze([{type:"text" as const,text}]) as unknown as {type:"text";text:string}[],details});
}
export function renderAcademicToolResultInternal(result:AcademicAcquisitionResult,options:NormalizedAcquisitionOptionsInternal):{content:{type:"text";text:string}[];details:CompactDetails}{try{return renderInternal(result,options);}catch(error){return mapAcademicRenderErrorInternal(error);}}
const NATIVE_IS_PROXY=utilTypes.isProxy,NATIVE_PROMISE=Promise,NATIVE_PROMISE_RESOLVE=Promise.resolve,NATIVE_PROMISE_THEN=Promise.prototype.then;
async function notify(onUpdate:unknown,result:AcademicAcquisitionResult,manager:AcademicSessionManager):Promise<void>{if(onUpdate===undefined)return;if(typeof onUpdate!=="function"||NATIVE_IS_PROXY(onUpdate))throw new AcademicToolError("academic-tool.internal-contract");let returned:unknown;try{returned=onUpdate(freeze({content:[{type:"text" as const,text:`Academic discovery complete: ${result.partitions.succeeded} succeeded, ${result.partitions.failed} failed.`}],details:{provenanceStatus:"uncommitted" as const,status:result.status}}));}catch{throw new AcademicToolError("academic-tool.internal-contract");}if(returned===undefined)return;await awaitAcademicSessionContinuationInternal(manager,result,returned);}

export function registerAcademicTools(pi:ExtensionAPI,dependencies:AcademicToolDependencies=createDefaultAcademicToolDependencies()):void {
 let dependencyState;try{dependencyState=getAcademicToolDependenciesInternal(dependencies);}catch(error){return freshAcademicToolErrorInternal(error);}if(!dependencyState.enabled)return;
 let generation=0,current:Readonly<{generation:number;manager:AcademicSessionManager}>|null=null,lifecycleTail:Promise<void>=NATIVE_PROMISE_RESOLVE.call(NATIVE_PROMISE,undefined) as Promise<void>;
 const enqueueLifecycle=(operation:()=>Promise<void>):Promise<void>=>{const run=async()=>{try{await operation();}catch(error){return freshAcademicToolErrorInternal(error);}},queued=NATIVE_PROMISE_THEN.call(lifecycleTail,run,run) as Promise<void>;lifecycleTail=NATIVE_PROMISE_THEN.call(queued,()=>undefined,()=>undefined) as Promise<void>;return queued;};
 const assertCaptured=(slot:Readonly<{generation:number;manager:AcademicSessionManager}>,result?:AcademicAcquisitionResult):void=>{assertAcademicSessionManagerLifecycleInternal(slot.manager);if(slot!==current||slot.generation!==generation)throw new AcademicToolError("academic-tool.stale-generation");if(result!==undefined)assertAcademicSessionCallContinuationInternal(slot.manager,result);};
 const execute=async(kind:"search"|"fetch",params:unknown,signal:AbortSignal|undefined,onUpdate:any)=>{const slot=current;if(!slot)throw new AcademicToolError("academic-tool.pre-session");let result:AcademicAcquisitionResult|null=null;try{assertCaptured(slot);result=kind==="search"?await slot.manager.search(params as AcademicSearchInput,signal):await slot.manager.fetch(params as AcademicFetchInput,signal);assertCaptured(slot,result);const options=getAcademicSessionNormalizedOptionsInternal(slot.manager);assertCaptured(slot,result);if(!options)throw new AcademicToolError("academic-tool.internal-contract");await notify(onUpdate,result,slot.manager);assertCaptured(slot,result);return renderAcademicToolResultInternal(result,options);}catch(error){try{assertCaptured(slot,result??undefined);}catch(lifecycleError){return freshAcademicToolErrorInternal(lifecycleError);}return freshAcademicToolErrorInternal(error);}};
 pi.registerTool({name:"academic_search",label:"Academic Search",description:"Discover bounded scholarly metadata from fixed providers. Results are uncommitted, raw payloads are not saved, output is capped, and citation/evidence admission requires a future explicit research run.",promptSnippet:"Use academic_search for bounded uncommitted scholarly metadata discovery",promptGuidelines:["Use academic_search for metadata discovery; do not treat its uncommitted results as canonical evidence or citations."],parameters:AcademicSearchToolParameters,execute(_toolCallId,params,signal,onUpdate,_ctx){return execute("search",params,signal,onUpdate);}});
 pi.registerTool({name:"academic_fetch",label:"Academic Fetch",description:"Fetch bounded scholarly metadata or PMC text by DOI, PMID, or PMCID. Results are uncommitted, raw payloads are not saved, output is capped, and citation/evidence admission requires a future explicit research run.",promptSnippet:"Use academic_fetch for bounded uncommitted identifier lookup",promptGuidelines:["Use academic_fetch to inspect a known scholarly identifier; use a future explicit research run before admitting or citing evidence."],parameters:AcademicFetchToolParameters,execute(_toolCallId,params,signal,onUpdate,_ctx){return execute("fetch",params,signal,onUpdate);}});
 pi.on("session_start",()=>enqueueLifecycle(async()=>{const prior=current;current=null;if(prior){detachAcademicSessionManagerInternal(prior.manager,"stale-generation");await prior.manager.shutdown();}if(generation===Number.MAX_SAFE_INTEGER)throw new AcademicToolError("academic-tool.internal-contract");generation+=1;current=Object.freeze({generation,manager:createAcademicSessionManager(dependencies,generation)});}));
 pi.on("session_shutdown",()=>enqueueLifecycle(async()=>{const prior=current;current=null;if(!prior)return;detachAcademicSessionManagerInternal(prior.manager,"shutdown");await prior.manager.shutdown();}));
}
