import { mkdir, mkdtemp, readdir, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { describe, expect, test } from "vitest";

import {
  CitationError, EvidenceAdmissionError, EvidenceQueryError, LineageError, ScholarlyIdentifierError, TransactionStoreError,
  assignCitationMappings, buildBoundedValidatedEvidenceSnapshot, buildEvidenceIndex, buildLineageGraph,
  canonicalDoiUrl, canonicalPmidUrl, canonicalPmcidUrl, canonicalJson, sha256Hex, compareSourceIndependence, evaluateEvidenceRule, parseResearchRecord, reduceLedgerEvents,
  validateProspectiveEvidenceSemantics, validateProspectiveSourceIdentityFields,
  type CanonicalEvidenceSet,
} from "../../src/index.js";
import type { RequestIntentRecord, RequestRecord } from "../../src/domain/events.js";
import type { EvidenceSnapshotDiagnostics } from "../../src/evidence/admission.js";
import type { AttemptRecord, RunSnapshot, TaskRecord } from "../../src/domain/records.js";
import type { CalculationRecord, ClaimRecord, EvidenceRecord, SourceRecord, VerificationRecord } from "../../src/domain/research-records.js";
import {
  createOwnedRunRoot, openOwnedRunRoot, inspectOwnedRunRootIntegrity,
  type OwnedRunRoot, type InspectedOwnedRunRoot,
} from "../../src/storage/run-root.js";
import { openEventLedger, readVerifiedLedgerSnapshot, type EventLedger } from "../../src/storage/event-ledger.js";
import {
  prepareTransaction, commitTransaction, reconcileCanonicalTransactions, reconstructCanonicalRecords,
  type CanonicalTransactionInput, type TransactionStoreOptions,
} from "../../src/storage/transaction-store.js";

const RUN = "run-0000000000000001" as const;
const TASK = "task-0000000000000001" as const;
const ATTEMPT_1 = "attempt-0000000000000001" as const;
const ATTEMPT_2 = "attempt-0000000000000002" as const;
const REQUEST_1 = "request-0000000000000001" as const;
const REQUEST_2 = "request-0000000000000002" as const;
const TX_1 = "tx-0000000000000001" as const;
const TX_2 = "tx-0000000000000002" as const;
const SOURCE = "src-reopen.00000001";
const CLAIM = "claim-0000000000000001";
const EVIDENCE = "ev-0000000000000001";
const VERIFY = "verify-0000000000000001";
const CALC = "calc-0000000000000001";
const AT = "2026-08-25T12:00:00.000Z";
const HASH = "a".repeat(64);
const URL = "https://article.example.org/reopen";

function runRecord(): RunSnapshot { return { schemaVersion: 1, runId: RUN, revision: 1, question: "q", language: "en", depth: "standard", reproducible: true, allowCalculations: true, calculationPolicySha256: HASH, state: "created", checkpointStage: null, executionEpoch: 0, outputRoot: "research/run", roleModels: { coordinator: "p/m", researcher: "p/m", verifier: "p/m" }, roleThinking: { coordinator: "medium", researcher: "medium", verifier: "medium" }, budget: { activeTimeLimitMs: 600_000, activeTimeUsedMs: 0, finalizationReserveMs: 120_000, maxSources: 10, admittedSources: 0, maxWaves: 2, waveOrdinal: 0 }, taskRefs: [], attemptRefs: [], acceptedVerificationRef: null, currentRevisionId: null, blocker: null, createdAt: AT, updatedAt: AT, completedAt: null }; }
function taskRecord(revision: number, attemptIds: string[]): TaskRecord { return { schemaVersion: 1, taskId: TASK, revision, description: "research", evidenceRule: { minimumLineages: 1, independentVerificationAllowed: true, primarySourceRequired: false, fullTextRequired: false }, role: "literature-searcher", state: "running", attemptIds, blocker: null, resolution: null }; }
function attemptRecord(id: typeof ATTEMPT_1 | typeof ATTEMPT_2, revision: number): AttemptRecord { return { schemaVersion: 1, attemptId: id, revision: 1, runId: RUN, taskId: TASK, executionEpoch: 0, logicalOperationId: `operation-${revision}`, attemptOrdinal: 1, retryOfAttemptId: null, attemptKind: "research", replayPolicy: "safe-read", state: "intent-recorded", providerModel: "p/m", thinkingLevel: "medium", promptTemplateSha256: HASH, renderedPromptSha256: "b".repeat(64), logicalInputSha256: "c".repeat(64), attemptEnvelopeSha256: "d".repeat(64), toolAllowlist: [], deadlineAt: "2026-08-25T13:00:00.000Z", capabilityId: `capability-${revision}`, resultSha256: null, billingStatus: "unknown", reportedUsage: null, error: null, createdAt: AT, updatedAt: AT }; }
function requestIntent(id: typeof REQUEST_1 | typeof REQUEST_2, attemptId: typeof ATTEMPT_1 | typeof ATTEMPT_2, ordinal: number): RequestIntentRecord { return { schemaVersion: 1, requestId: id, attemptId, executionEpoch: 0, logicalRequestId: `logical-${ordinal}`, physicalAttemptOrdinal: 1, retryOfRequestId: null, replayPolicy: "safe-read", provider: "openalex", operation: "fetch", normalizedInput: { query: null, identifier: null, url: URL, parameters: [] }, accessPolicySha256: HASH, deadlineAt: "2026-08-25T13:00:00.000Z", createdAt: AT }; }
function requestRecord(id: typeof REQUEST_1 | typeof REQUEST_2, attemptId: typeof ATTEMPT_1 | typeof ATTEMPT_2, ordinal: number): RequestRecord { const { deadlineAt: _deadlineAt, createdAt: _createdAt, ...identity } = requestIntent(id, attemptId, ordinal); return { ...identity, startedAt: AT, endedAt: AT, status: "success", httpStatus: 200, requestedUrl: URL, finalUrl: URL, redirectUrls: [], responseSha256: HASH, responseFile: { relativePath: `.state/request-payloads/${HASH}`, mediaType: "application/json", decodedBytes: 0, sha256: HASH }, encodedBytes: 0, decodedBytes: 0, resultSourceIds: [SOURCE], errorClass: null }; }
function sourceRecord(revision: number): SourceRecord { return { schemaVersion: 1, sourceId: SOURCE, revision, identifiers: { doi: null, pmid: null, pmcid: null }, canonicalUrl: URL, title: `source-${revision}`, authors: [], containerTitle: null, publisher: null, volume: null, issue: null, pages: null, published: { date: null, precision: "unknown" }, publicationType: "journal-article", peerReviewStatus: "unknown", accessLevel: "full-text", retrievedAt: AT, retrievalRequestIds: revision === 1 ? [REQUEST_1] : [REQUEST_1, REQUEST_2], metadataProvenance: [], lineage: { studyId: "study-reopen", cohortIds: [], datasetIds: [], relatedSourceIds: [], relationTypes: [] } }; }
function claimRecord(revision: number): ClaimRecord { return { schemaVersion: 1, claimId: CLAIM, revision, statement: "claim", kind: "externally-verifiable-fact", materiality: "load-bearing", scopeQualifiers: { population: null, intervention: null, comparator: null, outcome: null, timeRange: null }, evidenceRule: { minimumLineages: 1, independentVerificationAllowed: true, primarySourceRequired: false, fullTextRequired: false }, status: "supported", confidence: 0.8, evidenceRefs: [{ evidenceId: EVIDENCE, revision }], conflictClaimIds: [], createdByAttemptId: ATTEMPT_1 }; }
function evidenceRecord(revision: number, stance: EvidenceRecord["stance"] = "supporting"): EvidenceRecord { return { schemaVersion: 1, evidenceId: EVIDENCE, revision, claimRef: { claimId: CLAIM, revision }, evidenceType: "retrieved", sourceRef: { sourceId: SOURCE, revision }, calculationId: null, stance, quotes: ["evidence"], locators: [], extractedValues: [], method: null, quality: "primary-peer-reviewed", confidence: 0.9, recordedByAttemptId: revision === 1 ? ATTEMPT_1 : ATTEMPT_2, verificationStatus: "verified", conflictsWith: [] }; }
function verificationRecord(): VerificationRecord { return { schemaVersion: 1, verificationId: VERIFY, revision: 1, attemptId: ATTEMPT_2, method: "independent-source", checkedClaims: [{ claimId: CLAIM, revision: 2 }], checkedEvidence: [{ evidenceId: EVIDENCE, revision: 2 }], requestIds: [REQUEST_2], calculationIds: [CALC], result: "accepted", corrections: [{ claimId: CLAIM, description: "checked" }], independentEvidenceIds: [EVIDENCE], notes: "ok" }; }
function calculationRecord(): CalculationRecord { return { schemaVersion: 1, calculationId: CALC, attemptId: ATTEMPT_2, sandboxPolicySha256: HASH, runtime: "node", command: "calc", environment: [], inputs: [{ relativePath: "input.json", mediaType: "application/json", decodedBytes: 0, sha256: HASH }], sourceFiles: [], outputs: [{ relativePath: "output.json", mediaType: "application/json", decodedBytes: 0, sha256: HASH }], networkEnabled: false, startedAt: AT, endedAt: AT, exitCode: 0, status: "success" }; }
function canonicalSet(): CanonicalEvidenceSet { return { sources: [sourceRecord(1), sourceRecord(2)], claims: [claimRecord(1), claimRecord(2)], evidence: [evidenceRecord(1), evidenceRecord(2)], verifications: [verificationRecord()], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1), requestRecord(REQUEST_2, ATTEMPT_2, 2)], calculations: [calculationRecord()] }; }
function closureSet(): CanonicalEvidenceSet { const source2 = { ...sourceRecord(1), sourceId: "src-reopen.closure2", identifiers: { doi: "10.1234/closure2", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/closure2"), retrievalRequestIds: [], lineage: { ...sourceRecord(1).lineage, studyId: "study-closure2", relatedSourceIds: [SOURCE], relationTypes: ["reports" as const] } }; const claim2id = "claim-0000000000000002"; const evidence2id = "ev-0000000000000002"; const c1 = { ...claimRecord(1), evidenceRefs: [{ evidenceId: EVIDENCE, revision: 1 }], conflictClaimIds: [claim2id] }; const c2 = { ...claimRecord(1), claimId: claim2id, evidenceRefs: [{ evidenceId: evidence2id, revision: 1 }], conflictClaimIds: [CLAIM], status: "disputed" as const }; const c2later = { ...c2, revision: 2, status: "rejected" as const }; const e1 = { ...evidenceRecord(1), conflictsWith: [evidence2id] }; const e2 = { ...evidenceRecord(1, "contradicting"), evidenceId: evidence2id, claimRef: { claimId: claim2id, revision: 1 }, sourceRef: { sourceId: source2.sourceId, revision: 1 }, conflictsWith: [EVIDENCE] }; const verification = { ...verificationRecord(), checkedClaims: [{ claimId: CLAIM, revision: 1 }], checkedEvidence: [{ evidenceId: EVIDENCE, revision: 1 }], corrections: [{ claimId: claim2id, description: "correction edge" }], independentEvidenceIds: [evidence2id] }; const r1 = { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), resultSourceIds: [SOURCE, source2.sourceId] }; const r2 = { ...requestRecord(REQUEST_2, ATTEMPT_2, 2), resultSourceIds: [source2.sourceId] }; return { sources: [sourceRecord(1), source2], claims: [c1, c2, c2later], evidence: [e1, e2], verifications: [verification], requests: [r1, r2], calculations: [calculationRecord()] }; }
function diag(): EvidenceSnapshotDiagnostics { return { canonicalRecordVisits: 0, referenceVisits: 0, revisionIndexInsertions: 0, sourceIdentityVisits: 0, lineageVisits: 0, requestRecordsIndexed: 0, requestUrlVisits: 0, metadataStepVisits: 0 }; }
const foundationTransactionLimits: TransactionStoreOptions = Object.freeze({ maxLineBytes: 262_144, maxFileBytes: 1_048_576, maxTransactionBytes: 4_194_304 });
const effectiveScholarlyLimits = Object.freeze({ maxSourceRecordCanonicalBytes: 262_143, maxRequestRecordCanonicalBytes: 262_143, maxClaimRecordCanonicalBytes: 262_143, maxEvidenceRecordCanonicalBytes: 262_143, maxVerificationRecordCanonicalBytes: 262_143, maxCalculationRecordCanonicalBytes: 262_143, maxCanonicalEvidenceSetBytes: 4_194_304 });

interface ScholarlyResult { snapshotSha256: string; optionsSha256: string; policySha256: string; gate: string; selection: string; citations: string; diagnostics: EvidenceSnapshotDiagnostics }
function scholarly(records: CanonicalEvidenceSet, events: readonly any[], limits = effectiveScholarlyLimits): ScholarlyResult { const diagnostics = diag(); const policy = Object.freeze({ allowHttp: false }); const snapshot = buildBoundedValidatedEvidenceSnapshot(records, { sourceUrlPolicy: policy, limits }, diagnostics); const before = { ...diagnostics }; const gate = evaluateEvidenceRule(snapshot, { claimId: CLAIM, revision: 2 }); expect(diagnostics).toEqual(before); const selection = buildEvidenceIndex({ snapshot, ledgerEvents: events }).query({ verificationRefs: [{ verificationId: VERIFY, revision: 1 }], limit: 20, maxSelectedBytes: 1_000_000 }); expect(diagnostics).toEqual(before); const citations = assignCitationMappings(snapshot, [{ sourceId: SOURCE, revision: 2 }], [{ sourceRef: { sourceId: SOURCE, revision: 2 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]); expect(diagnostics).toEqual(before); return { snapshotSha256: snapshot.snapshotSha256, optionsSha256: snapshot.optionsSha256, policySha256: snapshot.policySha256, gate: canonicalJson(gate), selection: canonicalJson(selection), citations: canonicalJson(citations), diagnostics: { ...diagnostics } }; }

async function snapshotTree(root: string): Promise<Record<string, unknown>> { const output: Record<string, unknown> = {}; const walk = async (path: string): Promise<void> => { const info = await stat(path); const key = relative(root, path) || "."; output[key] = { dev: info.dev, ino: info.ino, size: info.size, bytes: info.isFile() ? (await readFile(path)).toString("base64") : null, sha256: info.isFile() ? sha256Hex(await readFile(path)) : null }; if (info.isDirectory()) for (const name of (await readdir(path)).sort()) await walk(join(path, name)); }; await walk(root); return output; }
async function closePreserving(operation: (() => Promise<void>) | undefined, primary: unknown): Promise<unknown> { if (!operation) return primary; try { await operation(); return primary; } catch (error) { return primary ?? error; } }
async function cleanupWithPreservedFailures(primary: Error, acquired: readonly Readonly<{ name: string; close: () => Promise<void> }>[], remove: () => Promise<void>): Promise<never> { const secondary: unknown[] = []; for (const handle of [...acquired].reverse()) { try { await handle.close(); } catch (error) { secondary.push(error); } } try { await remove(); } catch (error) { secondary.push(error); } Object.defineProperty(primary, "cleanupFailures", { value: Object.freeze(secondary), enumerable: false }); throw primary; }
interface ReopenConfig { records?: CanonicalEvidenceSet; evaluate?: (records: CanonicalEvidenceSet, events: readonly any[], effectiveLimits: import("../../src/index.js").EvidenceSetLimits) => unknown; comparePre?: boolean; foundationLimits?: TransactionStoreOptions }
async function buildAndReopen(config: ReopenConfig = {}): Promise<any> {
  const base = await mkdtemp(join(tmpdir(), "pi-scholarly-reopen-")); const project = join(base, "project"); await mkdir(project);
  let root: OwnedRunRoot | undefined; let ledger: EventLedger | undefined; let reopened: OwnedRunRoot | undefined; let inspection: InspectedOwnedRunRoot | undefined; let primary: unknown;
  const closeOrder: string[] = [];
  try {
    root = await createOwnedRunRoot({ trustedProject: project, repositoryRoot: project, topic: "reopen", runId: RUN, requestedPath: "run", ownershipToken: "f".repeat(64), now: () => new Date(AT) }); const path = root.path; const token = root.ownershipToken;
    await mkdir(join(path, ".state"), { mode: 0o700 }); let event = 0; ledger = await openEventLedger(join(path, ".state/events.jsonl"), { now: () => new Date(AT), eventId: () => `event-${++event}` }); await ledger.append("run_created", { run: runRecord() });
    const committed = config.records ?? canonicalSet(); const transactionLimits = config.foundationLimits ?? foundationTransactionLimits;
    const transactions = [
      { attemptId: ATTEMPT_1, requestId: REQUEST_1, transactionId: TX_1, revision: 1, records: { sources: committed.sources.filter((record) => record.revision === 1), claims: committed.claims.filter((record) => record.revision === 1), evidence: committed.evidence.filter((record) => record.recordedByAttemptId === ATTEMPT_1), verifications: committed.verifications.filter((record) => record.attemptId === ATTEMPT_1), requests: committed.requests.filter((record) => record.requestId === REQUEST_1), calculations: committed.calculations.filter((record) => record.attemptId === ATTEMPT_1) } },
      { attemptId: ATTEMPT_2, requestId: REQUEST_2, transactionId: TX_2, revision: 2, records: { sources: committed.sources.filter((record) => record.revision !== 1), claims: committed.claims.filter((record) => record.revision !== 1), evidence: committed.evidence.filter((record) => record.recordedByAttemptId === ATTEMPT_2), verifications: committed.verifications.filter((record) => record.attemptId === ATTEMPT_2), requests: committed.requests.filter((record) => record.requestId === REQUEST_2), calculations: committed.calculations.filter((record) => record.attemptId === ATTEMPT_2) } },
    ] as const;
    for (const item of transactions) {
      await ledger.reserveIdentity("attempt", item.attemptId, "parent-generated"); await ledger.reserveIdentity("request", item.requestId, "child-import"); await ledger.reserveIdentity("transaction", item.transactionId, "parent-generated");
      await ledger.append("task_upserted", { task: taskRecord(item.revision, item.revision === 1 ? [ATTEMPT_1] : [ATTEMPT_1, ATTEMPT_2]) }); await ledger.append("dispatch_intent", { attempt: attemptRecord(item.attemptId, item.revision) }); await ledger.append("dispatch_started", { attemptId: item.attemptId, pid: null, requestCorrelation: null });
      const request = item.records.requests[0]!; const intentRecord = { ...requestIntent(item.requestId, item.attemptId, item.revision), provider: request.provider, operation: request.operation, normalizedInput: request.normalizedInput, accessPolicySha256: request.accessPolicySha256 }; const intent = await ledger.append("request_intent_recorded", { attemptId: item.attemptId, journalLocalSeq: 1, journalEntrySha256: item.revision === 1 ? HASH : "b".repeat(64), intent: intentRecord });
      await ledger.append("request_result_recorded", { attemptId: item.attemptId, journalLocalSeq: 2, journalEntrySha256: item.revision === 1 ? "c".repeat(64) : "d".repeat(64), intentLedgerSeq: intent.seq, request });
      const result = await ledger.append("result_recorded", { attemptId: item.attemptId, resultSha256: item.revision === 1 ? "e".repeat(64) : "9".repeat(64), manifestSha256: null, transactionId: item.transactionId });
      const input: CanonicalTransactionInput = { schemaVersion: 1, transactionId: item.transactionId, runId: RUN, attemptId: item.attemptId, sourceResultSeq: result.seq, createdAt: AT, ...item.records }; const prepared = await prepareTransaction(path, input, transactionLimits); const manifestRef = await commitTransaction(path, item.transactionId, transactionLimits);
      await ledger.append("records_committed", { transactionId: item.transactionId, sourceResultSeq: result.seq, transactionManifestPath: manifestRef.relativePath, transactionManifestSha256: manifestRef.sha256, sourceRefs: prepared.manifest.sourceRefs, claimRefs: prepared.manifest.claimRefs, evidenceRefs: prepared.manifest.evidenceRefs, verificationRefs: prepared.manifest.verificationRefs, requestIds: prepared.manifest.requestIds, calculationIds: prepared.manifest.calculationIds });
      await ledger.append("attempt_committed", { attemptId: item.attemptId, transactionId: item.transactionId, taskId: TASK, sourceResultSeq: result.seq });
    }
    await ledger.verify(); const preEvents = await ledger.readAll(); reduceLedgerEvents(preEvents); const pre = config.comparePre === false ? null : scholarly(committed, preEvents); await ledger.close(); closeOrder.push("ledger"); ledger = undefined; await root.close(); closeOrder.push("owned-original"); root = undefined;
    reopened = await openOwnedRunRoot(path, RUN, token); const events = await readVerifiedLedgerSnapshot(join(path, ".state/events.jsonl"), { trustedRoot: path }); expect(await reconcileCanonicalTransactions(path, events, transactionLimits)).toEqual([]); const rebuilt = await reconstructCanonicalRecords(path, events, transactionLimits); const beforeSemantic = await snapshotTree(path); inspection = await inspectOwnedRunRootIntegrity(path);
    const postRecords = rebuilt as unknown as CanonicalEvidenceSet; const effectiveFoundationRecordCanonicalBytes = Math.min(262_144, transactionLimits.maxLineBytes! - 1); const effectiveFoundationKindFileBytes = Math.min(16_777_216, transactionLimits.maxFileBytes!); const effectiveFoundationTransactionCanonicalBytes = Math.min(33_554_432, transactionLimits.maxTransactionBytes!); const effectiveLimits = Object.freeze({ maxSourceRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxRequestRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxClaimRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxEvidenceRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxVerificationRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxCalculationRecordCanonicalBytes: effectiveFoundationRecordCanonicalBytes, maxCanonicalEvidenceSetBytes: effectiveFoundationTransactionCanonicalBytes }); let post: ScholarlyResult | null = null; let evaluation: unknown; let semanticError: unknown; try { if (config.evaluate) evaluation = config.evaluate(postRecords, events, effectiveLimits); else post = scholarly(postRecords, events); } catch (error) { semanticError = error; } await inspection.revalidate(); const afterSemantic = await snapshotTree(path); expect(afterSemantic).toEqual(beforeSemantic); const entries = await readdir(path); return { pre, post, evaluation, semanticError, beforeSemantic, afterSemantic, events, records: postRecords, entries, path, base, closeOrder, effectiveLimits, effectiveFoundationRecordCanonicalBytes, effectiveFoundationKindFileBytes, effectiveFoundationTransactionCanonicalBytes };
  } catch (error) { primary = error; throw error; }
  finally {
    primary = await closePreserving(inspection ? async () => { await inspection!.close(); closeOrder.push("inspection"); } : undefined, primary); inspection = undefined;
    primary = await closePreserving(reopened ? async () => { await reopened!.close(); closeOrder.push("owned-reopened"); } : undefined, primary); reopened = undefined;
    primary = await closePreserving(ledger ? async () => { await ledger!.close(); closeOrder.push("ledger"); } : undefined, primary); ledger = undefined;
    primary = await closePreserving(root ? async () => { await root!.close(); closeOrder.push("owned-original"); } : undefined, primary); root = undefined;
    try { await rm(base, { recursive: true, force: true }); } catch (error) { if (!primary) primary = error; }
    if (primary) throw primary;
  }
}

async function reconstructLegacySource(legacy: SourceRecord, legacyEvidence: EvidenceRecord): Promise<Readonly<{ source: Record<string, unknown>; evidence: Record<string, unknown>; before: string; after: string }>> {
  const records = { sources: [legacy], claims: [claimRecord(1)], evidence: [legacyEvidence], verifications: [], requests: canonicalSet().requests, calculations: [] };
  const value = await buildAndReopen({ records, comparePre: false, evaluate: (rebuilt) => { expectCode(() => validateProspectiveSourceIdentityFields(rebuilt.sources[0]!), ScholarlyIdentifierError, "url.invalid"); expectCode(() => validateProspectiveEvidenceSemantics(rebuilt.evidence[0]!), EvidenceAdmissionError, "evidence.invalid-prospective-record"); return { source: rebuilt.sources[0]!, evidence: rebuilt.evidence[0]! }; } });
  if (value.semanticError) throw value.semanticError; return { ...value.evaluation, before: canonicalJson(value.beforeSemantic), after: canonicalJson(value.afterSemantic) };
}

const names = [
  "uses exact owned root ledger transaction APIs and canonical event sequence",
  "closes ledger inspection and owned roots in finally without masking failures",
  "builds one branded snapshot per reopen and reuses it across evaluator query and citations",
  "uses the lower named foundation line kind-file and transaction byte ceilings on reopen",
  "keeps run data and local documents out of repository and package contents",
  "rebuilds identical scholarly decisions from reconstructed records and requests",
  "reconstructs legacy V1 records unchanged while prospective evaluation fails closed",
  "keeps historical revision closure valid and rejects stale refs introduced by latest records",
  "rejects omitted and duplicate reconstructed requests without mutating the run",
  "audits canonical URL duplicate and strong-identifier ambiguity after reopen",
  "proves citation and source URL transport metadata or resolver provenance under explicit HTTP policy",
  "rebuilds weak lineage components including common-parent forks",
  "returns bounded six-kind transitive query closure for every canonical edge",
  "requires canonical metadata for task and role query filters",
  "accepts disconfirmation citation and rejects only mismatched refs",
  "credits normative method and calculation derivation alternatives",
  "forwards identical URL policy through direct evidence evaluation",
  "fails closed on lineage conflict citation and query semantic corruption",
] as const;
function expectCode(action: () => unknown, klass: new (...args: any[]) => Error, code: string): void { try { action(); throw new Error("missing rejection"); } catch (error) { expect(error).toBeInstanceOf(klass); expect(error).toMatchObject({ code }); } }

describe("canonical scholarly reopen", () => {
  test(names[0], async () => { const value = await buildAndReopen(); expect(value.events.map((event: any) => event.type)).toEqual(["run_created", "identity_reserved", "identity_reserved", "identity_reserved", "task_upserted", "dispatch_intent", "dispatch_started", "request_intent_recorded", "request_result_recorded", "result_recorded", "records_committed", "attempt_committed", "identity_reserved", "identity_reserved", "identity_reserved", "task_upserted", "dispatch_intent", "dispatch_started", "request_intent_recorded", "request_result_recorded", "result_recorded", "records_committed", "attempt_committed"]); expect(value.events.filter((event: any) => event.type === "identity_reserved").map((event: any) => [event.payload.kind, event.payload.origin])).toEqual([["attempt", "parent-generated"], ["request", "child-import"], ["transaction", "parent-generated"], ["attempt", "parent-generated"], ["request", "child-import"], ["transaction", "parent-generated"]]); });
  test(names[1], async () => { const value = await buildAndReopen(); expect(value.closeOrder).toEqual(["ledger", "owned-original", "inspection", "owned-reopened"]); await expect(stat(value.base)).rejects.toMatchObject({ code: "ENOENT" }); const attempts: string[] = []; const primary = new Error("primary evaluation failure"); const acquired = ["owned-root", "ledger", "inspection"].map((name) => ({ name, close: async () => { attempts.push(name); if (name !== "ledger") throw new Error(`${name}-close`); } })); let thrown: unknown; try { await cleanupWithPreservedFailures(primary, acquired, async () => { attempts.push("rm"); throw new Error("rm-failed"); }); } catch (error) { thrown = error; } expect(thrown).toBe(primary); expect(attempts).toEqual(["inspection", "ledger", "owned-root", "rm"]); expect((thrown as Error & { cleanupFailures: unknown[] }).cleanupFailures.map((error) => (error as Error).message)).toEqual(["inspection-close", "owned-root-close", "rm-failed"]); const safe = await mkdtemp(join(tmpdir(), "pi-cleanup-idempotent-")); await rm(safe, { recursive: true, force: true }); await expect(rm(safe, { recursive: true, force: true })).resolves.toBeUndefined(); });
  test(names[2], async () => { const value = await buildAndReopen(); expect(value.post.diagnostics).toEqual({ canonicalRecordVisits: 10, referenceVisits: 17, revisionIndexInsertions: 10, sourceIdentityVisits: 2, lineageVisits: 2, requestRecordsIndexed: 2, requestUrlVisits: 4, metadataStepVisits: 0 }); expect(value.post).toEqual(value.pre); });
  test(names[3], async () => { const value = await buildAndReopen(); expect(value.effectiveLimits).toEqual(effectiveScholarlyLimits); expect([value.effectiveFoundationRecordCanonicalBytes, value.effectiveFoundationKindFileBytes, value.effectiveFoundationTransactionCanonicalBytes]).toEqual([262_143, 1_048_576, 4_194_304]); const expectOverflow = async (records: CanonicalEvidenceSet, limits: TransactionStoreOptions) => { try { await buildAndReopen({ records, foundationLimits: limits, comparePre: false }); throw new Error("missing foundation rejection"); } catch (error) { expect(error).toBeInstanceOf(TransactionStoreError); expect(error).toMatchObject({ code: "transaction.file-too-large" }); } }; const lineSet = { ...canonicalSet(), sources: [sourceRecord(1), { ...sourceRecord(2), title: "l".repeat(5_000) }] }; await expectOverflow(lineSet, { maxLineBytes: 4_096, maxFileBytes: 100_000, maxTransactionBytes: 500_000 }); const pairs = Array.from({ length: 8 }, (_, index) => { const id = `src-reopen.limit${String(index).padStart(3, "0")}`; const doi = `10.1234/limit${index}`; const first = { ...sourceRecord(1), sourceId: id, identifiers: { doi, pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl(doi), retrievalRequestIds: [], title: "a" }; return [first, { ...first, revision: 2, title: "f".repeat(900) }] as const; }); const fileSet = { sources: pairs.flat(), claims: [], evidence: [], verifications: [], requests: canonicalSet().requests.map((request) => ({ ...request, resultSourceIds: [] })), calculations: [] }; await expectOverflow(fileSet, { maxLineBytes: 8_192, maxFileBytes: 6_000, maxTransactionBytes: 500_000 }); const txSet = { ...canonicalSet(), sources: [sourceRecord(1), { ...sourceRecord(2), title: "s".repeat(3_000) }], verifications: [{ ...verificationRecord(), notes: "v".repeat(3_000) }], calculations: [{ ...calculationRecord(), command: "c".repeat(3_000) }] }; await expectOverflow(txSet, { maxLineBytes: 8_192, maxFileBytes: 50_000, maxTransactionBytes: 10_000 }); });
  test(names[4], async () => { const value = await buildAndReopen(); expect(value.path).toContain("pi-scholarly-reopen-"); expect(value.entries).not.toContain("docs"); await expect(stat(value.base)).rejects.toMatchObject({ code: "ENOENT" }); });
  test(names[5], async () => { const first = await buildAndReopen(); const second = await buildAndReopen(); expect(first.post).toEqual(first.pre); expect(second.post).toEqual(first.post); expect(first.records.requests).toHaveLength(2); });
  test(names[6], async () => { const legacy = { ...sourceRecord(1), canonicalUrl: "not a canonical URL", retrievalRequestIds: [], metadataProvenance: [] }; const legacyEvidence = { ...evidenceRecord(1), quotes: [""] }; const sourceBefore = canonicalJson(legacy); const evidenceBefore = canonicalJson(legacyEvidence); expect(parseResearchRecord("sources", legacy).success).toBe(true); expect(parseResearchRecord("evidence", legacyEvidence).success).toBe(true); const rebuilt = await reconstructLegacySource(legacy, legacyEvidence); expect(canonicalJson(rebuilt.source)).toBe(sourceBefore); expect(canonicalJson(rebuilt.evidence)).toBe(evidenceBefore); expect(rebuilt.after).toBe(rebuilt.before); expect(canonicalJson(legacy)).toBe(sourceBefore); expect(canonicalJson(legacyEvidence)).toBe(evidenceBefore); });
  test(names[7], async () => { const applicable = { ...verificationRecord(), attemptId: ATTEMPT_1, checkedClaims: [{ claimId: CLAIM, revision: 1 }], checkedEvidence: [{ evidenceId: EVIDENCE, revision: 1 }], requestIds: [REQUEST_1], calculationIds: [], corrections: [{ claimId: CLAIM, description: "applicable historical check" }] }; const later = { ...verificationRecord(), revision: 2, checkedClaims: [{ claimId: CLAIM, revision: 2 }], checkedEvidence: [{ evidenceId: EVIDENCE, revision: 2 }], corrections: [{ claimId: CLAIM, description: "unrelated later check" }] }; const qualified = canonicalSet().evidence.map((record) => ({ ...record, locators: [{ type: "page" as const, value: "1" }] })); const unrelated1 = { ...qualified[0]!, stance: "neutral" as const, evidenceId: "ev-0000000000000003" }; const unrelated2 = { ...unrelated1, revision: 2, recordedByAttemptId: ATTEMPT_2 }; const committed = { ...canonicalSet(), evidence: [...qualified, unrelated1, unrelated2], verifications: [applicable, later] }; const value = await buildAndReopen({ records: committed, comparePre: false, evaluate: (records, _events, limits) => { const snap = buildBoundedValidatedEvidenceSnapshot(records, { limits }); const historical = evaluateEvidenceRule(snap, { claimId: CLAIM, revision: 1 }); expect(historical.claimRef).toEqual({ claimId: CLAIM, revision: 1 }); expect(historical.supportingEvidenceRefs).toEqual([{ evidenceId: EVIDENCE, revision: 1 }]); const selected = evaluateEvidenceRule(snap, { claimId: CLAIM, revision: 1 }); const withoutLater = evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...records, verifications: [records.verifications[0]!] }, { limits }), { claimId: CLAIM, revision: 1 }); expect(selected.independentVerificationCredit).toBe(withoutLater.independentVerificationCredit); const wrong = { ...later, verificationId: "verify-0000000000000002", revision: 1 }; const wrongOnly = evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...records, verifications: [wrong] }, { limits }), { claimId: CLAIM, revision: 1 }); expect(wrongOnly.independentVerificationCredit).toBe(0); const stale = { ...claimRecord(2), evidenceRefs: [{ evidenceId: EVIDENCE, revision: 1 }] }; const prior = { ...claimRecord(1), evidenceRefs: [] }; expectCode(() => evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...records, claims: [prior, stale] }, { limits }), { claimId: CLAIM, revision: 2 }), EvidenceAdmissionError, "evidence.stale-latest-ref"); return historical; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation.claimRef.revision).toBe(1); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[8], async () => { const value = await buildAndReopen({ comparePre: false, evaluate: (records, _events, limits) => { expectCode(() => buildBoundedValidatedEvidenceSnapshot({ ...records, requests: [records.requests[0]!] }, { limits }), EvidenceAdmissionError, "evidence.unresolved-ref"); expectCode(() => buildBoundedValidatedEvidenceSnapshot({ ...records, requests: [...records.requests, records.requests[0]!] }, { limits }), EvidenceAdmissionError, "evidence.duplicate-request"); return "both-closed-errors"; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation).toBe("both-closed-errors"); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[9], async () => { const base = { ...sourceRecord(1), retrievalRequestIds: [] }; const compatible = { ...base, sourceId: "src-reopen.00000002" }; const requests = canonicalSet().requests; const duplicate = await buildAndReopen({ records: { sources: [base, compatible], claims: [], evidence: [], verifications: [], requests, calculations: [] }, comparePre: false, evaluate: (records, _events, limits) => buildBoundedValidatedEvidenceSnapshot(records, { limits }) }); expect(duplicate.semanticError).toBeInstanceOf(EvidenceAdmissionError); expect(duplicate.semanticError).toMatchObject({ code: "evidence.duplicate-source-identity" }); expect(duplicate.afterSemantic).toEqual(duplicate.beforeSemantic); const strongBase = { ...base, identifiers: { doi: "10.1234/base", pmid: null, pmcid: null } }; const conflicting = { ...compatible, identifiers: { doi: "10.1234/other", pmid: null, pmcid: null } }; const conflictingPmid = { ...compatible, sourceId: "src-reopen.00000003", identifiers: { doi: null, pmid: "123", pmcid: null } }; const conflictingPmcid = { ...compatible, sourceId: "src-reopen.00000004", identifiers: { doi: null, pmid: null, pmcid: "PMC456" } }; const ambiguous = await buildAndReopen({ records: { sources: [strongBase, conflicting, conflictingPmid, conflictingPmcid], claims: [], evidence: [], verifications: [], requests, calculations: [] }, comparePre: false, evaluate: (records, _events, limits) => buildBoundedValidatedEvidenceSnapshot(records, { limits }) }); expect(ambiguous.semanticError).toBeInstanceOf(EvidenceAdmissionError); expect(ambiguous.semanticError).toMatchObject({ code: "evidence.ambiguous-source-identity" }); expect(ambiguous.afterSemantic).toEqual(ambiguous.beforeSemantic); });
  test(names[10], async () => { const urls = ["https://requested.example/a", "https://final.example/a", "https://redirect.example/a", "https://article.example/a", canonicalDoiUrl("10.1234/resolver"), canonicalPmidUrl("123"), canonicalPmcidUrl("PMC456")]; const ids = [SOURCE, "src-reopen.final0001", "src-reopen.redir0001", "src-reopen.article01", "src-reopen.doi00001", "src-reopen.pmid0001", "src-reopen.pmcid001"]; const sources = urls.map((canonicalUrl, index) => ({ ...sourceRecord(1), sourceId: ids[index]!, canonicalUrl, title: `url-${index}`, identifiers: index === 4 ? { doi: "10.1234/resolver", pmid: null, pmcid: null } : index === 5 ? { doi: null, pmid: "123", pmcid: null } : index === 6 ? { doi: null, pmid: null, pmcid: "PMC456" } : { doi: null, pmid: null, pmcid: null }, retrievalRequestIds: index < 4 ? [REQUEST_1] : [], metadataProvenance: index === 3 ? [{ field: "canonicalUrl", provider: "openalex", requestId: REQUEST_1 }] : [], lineage: { ...sourceRecord(1).lineage, studyId: `study-url-${index}` } })); const request1 = { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), normalizedInput: { query: null, identifier: null, url: urls[0]!, parameters: [] }, requestedUrl: urls[0]!, finalUrl: urls[1]!, redirectUrls: [urls[2]!], resultSourceIds: ids.slice(0, 4) }; const records = { sources, claims: [], evidence: [], verifications: [], requests: [request1, requestRecord(REQUEST_2, ATTEMPT_2, 2)], calculations: [] }; const value = await buildAndReopen({ records, comparePre: false, evaluate: (rebuilt, _events, limits) => { const snapshot = buildBoundedValidatedEvidenceSnapshot(rebuilt, { limits }); return assignCitationMappings(snapshot, sources.map((source) => ({ sourceId: source.sourceId, revision: 1 })), []); } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation.bibliography.map((entry: any) => entry.canonicalUrl)).toEqual(urls); expect(value.evaluation.citations.map((citation: any) => citation.citationNumber)).toEqual([1, 2, 3, 4, 5, 6, 7]); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[11], async () => { const parent = sourceRecord(1); const a = { ...parent, sourceId: "src-reopen.forka001", identifiers: { doi: "10.1234/forka", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/forka"), retrievalRequestIds: [], lineage: { ...parent.lineage, relatedSourceIds: [parent.sourceId], relationTypes: ["reports" as const] } }; const b = { ...a, sourceId: "src-reopen.forkb001", identifiers: { doi: "10.1234/forkb", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/forkb") }; const disconnected = { ...a, sourceId: "src-reopen.free0001", identifiers: { doi: "10.1234/free", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/free"), lineage: { ...a.lineage, studyId: "study-free", relatedSourceIds: [], relationTypes: [] } }; const records = { sources: [parent, a, b, disconnected], claims: [], evidence: [], verifications: [], requests: canonicalSet().requests, calculations: [] }; const value = await buildAndReopen({ records, comparePre: false, evaluate: (rebuilt) => { const graph = buildLineageGraph(rebuilt.sources); expect(compareSourceIndependence(graph, { sourceId: a.sourceId, revision: 1 }, { sourceId: b.sourceId, revision: 1 }).status).toBe("dependent"); expect(compareSourceIndependence(graph, { sourceId: a.sourceId, revision: 1 }, { sourceId: disconnected.sourceId, revision: 1 }).status).toBe("independent"); const missing = { ...a, lineage: { ...a.lineage, relatedSourceIds: ["src-reopen.missing1"] } }; expectCode(() => buildLineageGraph([missing]), LineageError, "lineage.unresolved-ref"); return graph.stableSourceCount; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation).toBe(4); expect(value.afterSemantic).toEqual(value.beforeSemantic); const missing = { ...a, lineage: { ...a.lineage, relatedSourceIds: ["src-reopen.missing1"] } }; try { await buildAndReopen({ records: { ...records, sources: [missing] }, comparePre: false }); throw new Error("missing foundation rejection"); } catch (error) { expect(error).toBeInstanceOf(TransactionStoreError); expect(error).toMatchObject({ code: "transaction.invalid-reference" }); } });
  test(names[12], async () => { const records = closureSet(); const value = await buildAndReopen({ records, comparePre: false, evaluate: (rebuilt, events, limits) => { const snapshot = buildBoundedValidatedEvidenceSnapshot(rebuilt, { limits }); const index = buildEvidenceIndex({ snapshot, ledgerEvents: events }); const query = (seed: any) => index.query({ ...seed, limit: 20, maxSelectedBytes: 1_000_000 }); const direct = [query({ sourceRefs: [{ sourceId: SOURCE, revision: 1 }] }), query({ claimRefs: [{ claimId: CLAIM, revision: 1 }] }), query({ evidenceRefs: [{ evidenceId: EVIDENCE, revision: 1 }] }), query({ verificationRefs: [{ verificationId: VERIFY, revision: 1 }] })]; expect(direct.every((selection) => selection.sources.length > 0)).toBe(true); const selection = direct[3]!; expect(selection.sources.map((record) => record.sourceId)).toEqual([SOURCE, "src-reopen.closure2"]); expect(selection.claims.map((record) => record.claimId)).toContain("claim-0000000000000002"); expect(selection.evidence.map((record) => record.evidenceId)).toEqual([EVIDENCE, "ev-0000000000000002"]); expect(selection.verifications.map((record) => record.verificationId)).toEqual([VERIFY]); expect(selection.requests.map((record) => record.requestId)).toEqual([REQUEST_1, REQUEST_2]); expect(selection.calculations.map((record) => record.calculationId)).toEqual([CALC]); for (const kind of ["sources", "claims", "evidence", "verifications", "requests", "calculations"] as const) expect(new Set(selection[kind].map((record: any) => `${record.sourceId ?? record.claimId ?? record.evidenceId ?? record.verificationId ?? record.requestId ?? record.calculationId}:${record.revision ?? 0}`)).size).toBe(selection[kind].length); const seed = { verificationRefs: [{ verificationId: VERIFY, revision: 1 }], limit: 20, maxSelectedBytes: 1_000_000 }; expectCode(() => buildEvidenceIndex({ snapshot }, { maxSelectedPerKind: { sources: 1, claims: 10, evidence: 10, verifications: 10, requests: 10, calculations: 10 } }).query(seed), EvidenceQueryError, "query.closure-too-large"); expectCode(() => buildEvidenceIndex({ snapshot }, { maxTotalSelectedRecords: 4, maxSelectedPerKind: { sources: 4, claims: 4, evidence: 4, verifications: 4, requests: 4, calculations: 4 } }).query(seed), EvidenceQueryError, "query.closure-too-large"); expectCode(() => buildEvidenceIndex({ snapshot }, { maxClosureEdges: 1 }).query(seed), EvidenceQueryError, "query.closure-too-large"); expectCode(() => index.query({ ...seed, maxSelectedBytes: 100 }), EvidenceQueryError, "query.closure-too-large"); return canonicalJson(selection); } }); expect(value.semanticError).toBeUndefined(); expect(typeof value.evaluation).toBe("string"); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[13], async () => { const value = await buildAndReopen(); const snapshot = buildBoundedValidatedEvidenceSnapshot(value.records); expect(buildEvidenceIndex({ snapshot, ledgerEvents: value.events }).query({ taskIds: [TASK], roles: ["literature-searcher"], limit: 10, maxSelectedBytes: 1_000_000 }).evidence.length).toBeGreaterThan(0); expectCode(() => buildEvidenceIndex({ snapshot }).query({ taskIds: [TASK], limit: 10, maxSelectedBytes: 1_000_000 }), EvidenceQueryError, "query.metadata-required"); });
  test(names[14], async () => { const set = { ...canonicalSet(), evidence: [evidenceRecord(1), { ...evidenceRecord(2, "contradicting"), verificationStatus: "rejected" as const }] }; const value = await buildAndReopen({ records: set, comparePre: false, evaluate: (records, _events, limits) => { const snapshot = buildBoundedValidatedEvidenceSnapshot(records, { limits }); const citation = assignCitationMappings(snapshot, [{ sourceId: SOURCE, revision: 2 }], [{ sourceRef: { sourceId: SOURCE, revision: 2 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]); expect(citation.citations[0]!.evidenceRefs).toEqual([{ evidenceId: EVIDENCE, revision: 2 }]); const other = { ...sourceRecord(1), sourceId: "src-reopen.other001", identifiers: { doi: "10.1234/other", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/other"), retrievalRequestIds: [] }; expectCode(() => assignCitationMappings(buildBoundedValidatedEvidenceSnapshot({ ...records, sources: [...records.sources, other] }, { limits }), [{ sourceId: other.sourceId, revision: 1 }], [{ sourceRef: { sourceId: other.sourceId, revision: 1 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]), CitationError, "citation.cross-source-evidence"); return citation; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation.citations).toHaveLength(1); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[15], async () => { const file = calculationRecord().inputs[0]!; const modes = ["method", "inputs", "sourceFiles", "zeroOutput", "bareMethod", "failed", "missingInput", "missingOutput", "missingContext"] as const; const claims = modes.map((mode, index) => ({ ...claimRecord(1), claimId: `claim-00000000000000${10 + index}`, kind: "derived-result" as const, evidenceRefs: [{ evidenceId: `ev-00000000000000${10 + index}`, revision: 1 }] })); const calculations = modes.slice(1).map((mode, index) => { const id = `calc-00000000000000${11 + index}`; const base = { ...calculationRecord(), calculationId: id, attemptId: ATTEMPT_1 }; if (mode === "sourceFiles") return { ...base, inputs: [], sourceFiles: [file] }; if (mode === "failed") return { ...base, status: "failed" as const, exitCode: 1 }; if (mode === "missingInput") return { ...base, inputs: [], sourceFiles: [] }; if (mode === "missingOutput") return { ...base, outputs: [] }; return base; }); const evidence = modes.map((mode, index) => ({ ...evidenceRecord(1), evidenceId: `ev-00000000000000${10 + index}`, claimRef: { claimId: claims[index]!.claimId, revision: 1 }, evidenceType: "derived" as const, sourceRef: mode === "method" ? { sourceId: SOURCE, revision: 1 } : null, calculationId: mode === "method" || mode === "bareMethod" ? null : calculations[index - 1]!.calculationId, method: mode === "method" || mode === "bareMethod" ? "deterministic method" : null, quotes: [], extractedValues: mode === "bareMethod" || mode === "missingContext" ? [] : [{ value: "1", numericValue: 1, unit: "1", context: "result context" }] })); const records = { sources: [sourceRecord(1)], claims, evidence, verifications: [], requests: canonicalSet().requests, calculations }; const value = await buildAndReopen({ records, comparePre: false, evaluate: (rebuilt, _events, limits) => { const snapshot = buildBoundedValidatedEvidenceSnapshot(rebuilt, { limits }); const decisions = new Map(modes.map((mode, index) => [mode, evaluateEvidenceRule(snapshot, { claimId: claims[index]!.claimId, revision: 1 })])); for (const mode of ["method", "inputs", "sourceFiles", "zeroOutput"] as const) { expect(decisions.get(mode)!.derivedComponentCount, `${mode}:${canonicalJson(decisions.get(mode))}`).toBe(1); expect(decisions.get(mode)!.blockers).not.toContain("claim.invalid-derived-evidence"); } for (const mode of ["bareMethod", "failed", "missingInput", "missingOutput", "missingContext"] as const) { expect(decisions.get(mode)!.derivedComponentCount, mode).toBe(0); expect(decisions.get(mode)!.blockers).toContain("claim.invalid-derived-evidence"); } expect(calculations.find((calculation) => calculation.calculationId === evidence[3]!.calculationId)!.outputs[0]!.decodedBytes).toBe(0); return decisions.size; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation).toBe(9); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
  test(names[16], async () => { const second = requestRecord(REQUEST_2, ATTEMPT_2, 2); const runFailure = async (source: SourceRecord, first: RequestRecord, code: string, policy?: any) => { const value = await buildAndReopen({ records: { sources: [source], claims: [], evidence: [], verifications: [], requests: [first, second], calculations: [] }, comparePre: false, evaluate: (records, _events, limits) => buildBoundedValidatedEvidenceSnapshot(records, policy === undefined ? { limits } : { limits, sourceUrlPolicy: policy }) }); expect(value.semanticError).toBeInstanceOf(EvidenceAdmissionError); expect(value.semanticError).toMatchObject({ code }); expect(value.afterSemantic).toEqual(value.beforeSemantic); }; const arbitrary = { ...sourceRecord(1), canonicalUrl: "https://arbitrary.example/a", retrievalRequestIds: [] }; await runFailure(arbitrary, requestRecord(REQUEST_1, ATTEMPT_1, 1), "evidence.source-url-unattributed"); const wrongRequest = { ...sourceRecord(1), canonicalUrl: URL, retrievalRequestIds: [REQUEST_1] }; await runFailure(wrongRequest, { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), resultSourceIds: [] }, "evidence.source-url-request-mismatch"); const providerSource = { ...sourceRecord(1), canonicalUrl: "https://article.example/a", retrievalRequestIds: [REQUEST_1], metadataProvenance: [{ field: "canonicalUrl", provider: "openalex", requestId: REQUEST_1 }] }; await runFailure(providerSource, { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), provider: "crossref", finalUrl: "https://api.example/result" }, "evidence.source-url-metadata-mismatch"); const terminal = { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), status: "terminal-error" as const, httpStatus: null, finalUrl: null, responseSha256: null, responseFile: null, resultSourceIds: [], errorClass: "network" }; await runFailure(sourceRecord(1), terminal, "evidence.source-url-request-mismatch"); const http = { ...sourceRecord(1), canonicalUrl: "http://trusted.example.org/reopen", retrievalRequestIds: [] }; await runFailure(http, requestRecord(REQUEST_1, ATTEMPT_1, 1), "evidence.source-url-policy-invalid"); });
  test(names[17], async () => { const value = await buildAndReopen({ records: closureSet(), comparePre: false, evaluate: (records, events, limits) => { const snapshot = buildBoundedValidatedEvidenceSnapshot(records, { limits }); const decision = evaluateEvidenceRule(snapshot, { claimId: CLAIM, revision: 1 }); expect(decision.blockers).toContain("claim.unresolved-conflict"); expect(records.claims.find((claim) => claim.claimId === "claim-0000000000000002" && claim.revision === 2)!.status).toBe("rejected"); expectCode(() => assignCitationMappings(snapshot, [{ sourceId: "src-reopen.pending01", revision: 1 }], []), CitationError, "citation.unresolved-ref"); const a = sourceRecord(1); const b = { ...a, sourceId: "src-reopen.cycle001", identifiers: { doi: "10.1234/cycle", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/cycle"), retrievalRequestIds: [], lineage: { ...a.lineage, relatedSourceIds: [a.sourceId], relationTypes: ["version-of" as const] } }; const c = { ...a, sourceId: "src-reopen.cycle002", identifiers: { doi: "10.1234/cycle2", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/cycle2"), retrievalRequestIds: [], lineage: { ...a.lineage, relatedSourceIds: [b.sourceId], relationTypes: ["reports" as const] } }; const cyclic = { ...a, retrievalRequestIds: [], lineage: { ...a.lineage, relatedSourceIds: [c.sourceId], relationTypes: ["reanalysis-of" as const] } }; expectCode(() => buildLineageGraph([cyclic, b, c]), LineageError, "lineage.cycle"); const index = buildEvidenceIndex({ snapshot, ledgerEvents: events }); expectCode(() => index.query({ evidenceRefs: [{ evidenceId: "bad", revision: 1 }] as never, limit: 10, maxSelectedBytes: 10_000 }), EvidenceQueryError, "query.reference-invalid"); return decision; } }); expect(value.semanticError).toBeUndefined(); expect(value.evaluation.blockers).toContain("claim.unresolved-conflict"); expect(value.afterSemantic).toEqual(value.beforeSemantic); });
});
