import { mkdir, mkdtemp, readdir, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { describe, expect, test } from "vitest";

import {
  CitationError, EvidenceAdmissionError, EvidenceQueryError, LineageError, ScholarlyIdentifierError,
  assignCitationMappings, buildBoundedValidatedEvidenceSnapshot, buildEvidenceIndex, buildLineageGraph,
  canonicalDoiUrl, canonicalJson, compareSourceIndependence, evaluateEvidenceRule, parseResearchRecord, reduceLedgerEvents,
  validateProspectiveSourceIdentityFields,
  type CanonicalEvidenceSet,
} from "../../src/index.js";
import type { RequestIntentRecord, RequestRecord } from "../../src/domain/events.js";
import type { EvidenceSnapshotDiagnostics } from "../../src/evidence/admission.js";
import type { AttemptRecord, RunSnapshot, TaskRecord } from "../../src/domain/records.js";
import type { CalculationRecord, ClaimRecord, EvidenceRecord, SourceRecord, VerificationRecord } from "../../src/domain/research-records.js";
import {
  createOwnedRunRoot, openOwnedRunRoot, inspectOwnedRunRootIntegrity,
  type OwnedRunRoot, type InspectedOwnedRunRoot,
} from "../../src/storage/run-root.js";
import { openEventLedger, readVerifiedLedgerSnapshot, type EventLedger } from "../../src/storage/event-ledger.js";
import {
  prepareTransaction, commitTransaction, reconcileCanonicalTransactions, reconstructCanonicalRecords,
  type CanonicalTransactionInput, type TransactionStoreOptions,
} from "../../src/storage/transaction-store.js";

const RUN = "run-0000000000000001" as const;
const TASK = "task-0000000000000001" as const;
const ATTEMPT_1 = "attempt-0000000000000001" as const;
const ATTEMPT_2 = "attempt-0000000000000002" as const;
const REQUEST_1 = "request-0000000000000001" as const;
const REQUEST_2 = "request-0000000000000002" as const;
const TX_1 = "tx-0000000000000001" as const;
const TX_2 = "tx-0000000000000002" as const;
const SOURCE = "src-reopen.00000001";
const CLAIM = "claim-0000000000000001";
const EVIDENCE = "ev-0000000000000001";
const VERIFY = "verify-0000000000000001";
const CALC = "calc-0000000000000001";
const AT = "2026-08-25T12:00:00.000Z";
const HASH = "a".repeat(64);
const URL = "https://article.example.org/reopen";

function runRecord(): RunSnapshot { return { schemaVersion: 1, runId: RUN, revision: 1, question: "q", language: "en", depth: "standard", reproducible: true, allowCalculations: true, calculationPolicySha256: HASH, state: "created", checkpointStage: null, executionEpoch: 0, outputRoot: "research/run", roleModels: { coordinator: "p/m", researcher: "p/m", verifier: "p/m" }, roleThinking: { coordinator: "medium", researcher: "medium", verifier: "medium" }, budget: { activeTimeLimitMs: 600_000, activeTimeUsedMs: 0, finalizationReserveMs: 120_000, maxSources: 10, admittedSources: 0, maxWaves: 2, waveOrdinal: 0 }, taskRefs: [], attemptRefs: [], acceptedVerificationRef: null, currentRevisionId: null, blocker: null, createdAt: AT, updatedAt: AT, completedAt: null }; }
function taskRecord(revision: number, attemptIds: string[]): TaskRecord { return { schemaVersion: 1, taskId: TASK, revision, description: "research", evidenceRule: { minimumLineages: 1, independentVerificationAllowed: true, primarySourceRequired: false, fullTextRequired: false }, role: "literature-searcher", state: "running", attemptIds, blocker: null, resolution: null }; }
function attemptRecord(id: typeof ATTEMPT_1 | typeof ATTEMPT_2, revision: number): AttemptRecord { return { schemaVersion: 1, attemptId: id, revision: 1, runId: RUN, taskId: TASK, executionEpoch: 0, logicalOperationId: `operation-${revision}`, attemptOrdinal: 1, retryOfAttemptId: null, attemptKind: "research", replayPolicy: "safe-read", state: "intent-recorded", providerModel: "p/m", thinkingLevel: "medium", promptTemplateSha256: HASH, renderedPromptSha256: "b".repeat(64), logicalInputSha256: "c".repeat(64), attemptEnvelopeSha256: "d".repeat(64), toolAllowlist: [], deadlineAt: "2026-08-25T13:00:00.000Z", capabilityId: `capability-${revision}`, resultSha256: null, billingStatus: "unknown", reportedUsage: null, error: null, createdAt: AT, updatedAt: AT }; }
function requestIntent(id: typeof REQUEST_1 | typeof REQUEST_2, attemptId: typeof ATTEMPT_1 | typeof ATTEMPT_2, ordinal: number): RequestIntentRecord { return { schemaVersion: 1, requestId: id, attemptId, executionEpoch: 0, logicalRequestId: `logical-${ordinal}`, physicalAttemptOrdinal: 1, retryOfRequestId: null, replayPolicy: "safe-read", provider: "openalex", operation: "fetch", normalizedInput: { query: null, identifier: null, url: URL, parameters: [] }, accessPolicySha256: HASH, deadlineAt: "2026-08-25T13:00:00.000Z", createdAt: AT }; }
function requestRecord(id: typeof REQUEST_1 | typeof REQUEST_2, attemptId: typeof ATTEMPT_1 | typeof ATTEMPT_2, ordinal: number): RequestRecord { const { deadlineAt: _deadlineAt, createdAt: _createdAt, ...identity } = requestIntent(id, attemptId, ordinal); return { ...identity, startedAt: AT, endedAt: AT, status: "success", httpStatus: 200, requestedUrl: URL, finalUrl: URL, redirectUrls: [], responseSha256: HASH, responseFile: { relativePath: `.state/request-payloads/${HASH}`, mediaType: "application/json", decodedBytes: 0, sha256: HASH }, encodedBytes: 0, decodedBytes: 0, resultSourceIds: [SOURCE], errorClass: null }; }
function sourceRecord(revision: number): SourceRecord { return { schemaVersion: 1, sourceId: SOURCE, revision, identifiers: { doi: null, pmid: null, pmcid: null }, canonicalUrl: URL, title: `source-${revision}`, authors: [], containerTitle: null, publisher: null, volume: null, issue: null, pages: null, published: { date: null, precision: "unknown" }, publicationType: "journal-article", peerReviewStatus: "unknown", accessLevel: "full-text", retrievedAt: AT, retrievalRequestIds: revision === 1 ? [REQUEST_1] : [REQUEST_1, REQUEST_2], metadataProvenance: [], lineage: { studyId: "study-reopen", cohortIds: [], datasetIds: [], relatedSourceIds: [], relationTypes: [] } }; }
function claimRecord(revision: number): ClaimRecord { return { schemaVersion: 1, claimId: CLAIM, revision, statement: "claim", kind: "externally-verifiable-fact", materiality: "load-bearing", scopeQualifiers: { population: null, intervention: null, comparator: null, outcome: null, timeRange: null }, evidenceRule: { minimumLineages: 1, independentVerificationAllowed: true, primarySourceRequired: false, fullTextRequired: false }, status: "supported", confidence: 0.8, evidenceRefs: [{ evidenceId: EVIDENCE, revision }], conflictClaimIds: [], createdByAttemptId: ATTEMPT_1 }; }
function evidenceRecord(revision: number, stance: EvidenceRecord["stance"] = "supporting"): EvidenceRecord { return { schemaVersion: 1, evidenceId: EVIDENCE, revision, claimRef: { claimId: CLAIM, revision }, evidenceType: "retrieved", sourceRef: { sourceId: SOURCE, revision }, calculationId: null, stance, quotes: ["evidence"], locators: [], extractedValues: [], method: null, quality: "primary-peer-reviewed", confidence: 0.9, recordedByAttemptId: revision === 1 ? ATTEMPT_1 : ATTEMPT_2, verificationStatus: "verified", conflictsWith: [] }; }
function verificationRecord(): VerificationRecord { return { schemaVersion: 1, verificationId: VERIFY, revision: 1, attemptId: ATTEMPT_2, method: "independent-source", checkedClaims: [{ claimId: CLAIM, revision: 2 }], checkedEvidence: [{ evidenceId: EVIDENCE, revision: 2 }], requestIds: [REQUEST_2], calculationIds: [CALC], result: "accepted", corrections: [{ claimId: CLAIM, description: "checked" }], independentEvidenceIds: [EVIDENCE], notes: "ok" }; }
function calculationRecord(): CalculationRecord { return { schemaVersion: 1, calculationId: CALC, attemptId: ATTEMPT_2, sandboxPolicySha256: HASH, runtime: "node", command: "calc", environment: [], inputs: [{ relativePath: "input.json", mediaType: "application/json", decodedBytes: 0, sha256: HASH }], sourceFiles: [], outputs: [{ relativePath: "output.json", mediaType: "application/json", decodedBytes: 0, sha256: HASH }], networkEnabled: false, startedAt: AT, endedAt: AT, exitCode: 0, status: "success" }; }
function canonicalSet(): CanonicalEvidenceSet { return { sources: [sourceRecord(1), sourceRecord(2)], claims: [claimRecord(1), claimRecord(2)], evidence: [evidenceRecord(1), evidenceRecord(2)], verifications: [verificationRecord()], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1), requestRecord(REQUEST_2, ATTEMPT_2, 2)], calculations: [calculationRecord()] }; }
function diag(): EvidenceSnapshotDiagnostics { return { canonicalRecordVisits: 0, referenceVisits: 0, revisionIndexInsertions: 0, sourceIdentityVisits: 0, lineageVisits: 0, requestRecordsIndexed: 0, requestUrlVisits: 0, metadataStepVisits: 0 }; }
const foundationTransactionLimits: TransactionStoreOptions = Object.freeze({ maxLineBytes: 262_144, maxFileBytes: 1_048_576, maxTransactionBytes: 4_194_304 });

interface ScholarlyResult { snapshotSha256: string; optionsSha256: string; policySha256: string; gate: string; selection: string; citations: string; diagnostics: EvidenceSnapshotDiagnostics }
function scholarly(records: CanonicalEvidenceSet, events: readonly any[]): ScholarlyResult { const diagnostics = diag(); const policy = Object.freeze({ allowHttp: false }); const snapshot = buildBoundedValidatedEvidenceSnapshot(records, { sourceUrlPolicy: policy }, diagnostics); const before = { ...diagnostics }; const gate = evaluateEvidenceRule(snapshot, { claimId: CLAIM, revision: 2 }); const selection = buildEvidenceIndex({ snapshot, ledgerEvents: events }).query({ verificationRefs: [{ verificationId: VERIFY, revision: 1 }], limit: 20, maxSelectedBytes: 1_000_000 }); const citations = assignCitationMappings(snapshot, [{ sourceId: SOURCE, revision: 2 }], [{ sourceRef: { sourceId: SOURCE, revision: 2 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]); expect(diagnostics).toEqual(before); return { snapshotSha256: snapshot.snapshotSha256, optionsSha256: snapshot.optionsSha256, policySha256: snapshot.policySha256, gate: canonicalJson(gate), selection: canonicalJson(selection), citations: canonicalJson(citations), diagnostics: { ...diagnostics } }; }

async function snapshotTree(root: string): Promise<Record<string, unknown>> { const output: Record<string, unknown> = {}; const walk = async (path: string): Promise<void> => { const info = await stat(path); const key = relative(root, path) || "."; output[key] = { dev: info.dev, ino: info.ino, size: info.size, bytes: info.isFile() ? (await readFile(path)).toString("base64") : null }; if (info.isDirectory()) for (const name of (await readdir(path)).sort()) await walk(join(path, name)); }; await walk(root); return output; }
async function closePreserving(operation: (() => Promise<void>) | undefined, primary: unknown): Promise<unknown> { if (!operation) return primary; try { await operation(); return primary; } catch (error) { return primary ?? error; } }
async function buildAndReopen() {
  const base = await mkdtemp(join(tmpdir(), "pi-scholarly-reopen-")); const project = join(base, "project"); await mkdir(project);
  let root: OwnedRunRoot | undefined; let ledger: EventLedger | undefined; let reopened: OwnedRunRoot | undefined; let inspection: InspectedOwnedRunRoot | undefined; let primary: unknown;
  const closeOrder: string[] = [];
  try {
    root = await createOwnedRunRoot({ trustedProject: project, repositoryRoot: project, topic: "reopen", runId: RUN, requestedPath: "run", ownershipToken: "f".repeat(64), now: () => new Date(AT) }); const path = root.path; const token = root.ownershipToken;
    await mkdir(join(path, ".state"), { mode: 0o700 }); let event = 0; ledger = await openEventLedger(join(path, ".state/events.jsonl"), { now: () => new Date(AT), eventId: () => `event-${++event}` }); await ledger.append("run_created", { run: runRecord() });
    const transactions = [
      { attemptId: ATTEMPT_1, requestId: REQUEST_1, transactionId: TX_1, revision: 1, records: { sources: [sourceRecord(1)], claims: [claimRecord(1)], evidence: [evidenceRecord(1)], verifications: [], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1)], calculations: [] } },
      { attemptId: ATTEMPT_2, requestId: REQUEST_2, transactionId: TX_2, revision: 2, records: { sources: [sourceRecord(2)], claims: [claimRecord(2)], evidence: [evidenceRecord(2)], verifications: [verificationRecord()], requests: [requestRecord(REQUEST_2, ATTEMPT_2, 2)], calculations: [calculationRecord()] } },
    ] as const;
    for (const item of transactions) {
      await ledger.reserveIdentity("attempt", item.attemptId, "parent-generated"); await ledger.reserveIdentity("request", item.requestId, "child-import"); await ledger.reserveIdentity("transaction", item.transactionId, "parent-generated");
      await ledger.append("task_upserted", { task: taskRecord(item.revision, item.revision === 1 ? [ATTEMPT_1] : [ATTEMPT_1, ATTEMPT_2]) }); await ledger.append("dispatch_intent", { attempt: attemptRecord(item.attemptId, item.revision) }); await ledger.append("dispatch_started", { attemptId: item.attemptId, pid: null, requestCorrelation: null });
      const intent = await ledger.append("request_intent_recorded", { attemptId: item.attemptId, journalLocalSeq: 1, journalEntrySha256: item.revision === 1 ? HASH : "b".repeat(64), intent: requestIntent(item.requestId, item.attemptId, item.revision) });
      await ledger.append("request_result_recorded", { attemptId: item.attemptId, journalLocalSeq: 2, journalEntrySha256: item.revision === 1 ? "c".repeat(64) : "d".repeat(64), intentLedgerSeq: intent.seq, request: requestRecord(item.requestId, item.attemptId, item.revision) });
      const result = await ledger.append("result_recorded", { attemptId: item.attemptId, resultSha256: item.revision === 1 ? "e".repeat(64) : "9".repeat(64), manifestSha256: null, transactionId: item.transactionId });
      const input: CanonicalTransactionInput = { schemaVersion: 1, transactionId: item.transactionId, runId: RUN, attemptId: item.attemptId, sourceResultSeq: result.seq, createdAt: AT, ...item.records }; const prepared = await prepareTransaction(path, input, foundationTransactionLimits); const manifestRef = await commitTransaction(path, item.transactionId, foundationTransactionLimits);
      await ledger.append("records_committed", { transactionId: item.transactionId, sourceResultSeq: result.seq, transactionManifestPath: manifestRef.relativePath, transactionManifestSha256: manifestRef.sha256, sourceRefs: prepared.manifest.sourceRefs, claimRefs: prepared.manifest.claimRefs, evidenceRefs: prepared.manifest.evidenceRefs, verificationRefs: prepared.manifest.verificationRefs, requestIds: prepared.manifest.requestIds, calculationIds: prepared.manifest.calculationIds });
      await ledger.append("attempt_committed", { attemptId: item.attemptId, transactionId: item.transactionId, taskId: TASK, sourceResultSeq: result.seq });
    }
    await ledger.verify(); const preEvents = await ledger.readAll(); reduceLedgerEvents(preEvents); const pre = scholarly(canonicalSet(), preEvents); await ledger.close(); closeOrder.push("ledger"); ledger = undefined; await root.close(); closeOrder.push("owned-original"); root = undefined;
    reopened = await openOwnedRunRoot(path, RUN, token); const events = await readVerifiedLedgerSnapshot(join(path, ".state/events.jsonl"), { trustedRoot: path }); expect(await reconcileCanonicalTransactions(path, events, foundationTransactionLimits)).toEqual([]); const rebuilt = await reconstructCanonicalRecords(path, events, foundationTransactionLimits); const beforeSemantic = await snapshotTree(path); inspection = await inspectOwnedRunRootIntegrity(path);
    const postRecords = rebuilt as unknown as CanonicalEvidenceSet; const post = scholarly(postRecords, events); await inspection.revalidate(); expect(await snapshotTree(path)).toEqual(beforeSemantic); const entries = await readdir(path); return { pre, post, events, records: postRecords, entries, path, base, closeOrder, effectiveFoundationRecordCanonicalBytes: Math.min(262_144, foundationTransactionLimits.maxLineBytes! - 1), effectiveFoundationKindFileBytes: Math.min(16_777_216, foundationTransactionLimits.maxFileBytes!), effectiveFoundationTransactionCanonicalBytes: Math.min(33_554_432, foundationTransactionLimits.maxTransactionBytes!) };
  } catch (error) { primary = error; throw error; }
  finally {
    primary = await closePreserving(inspection ? async () => { await inspection!.close(); closeOrder.push("inspection"); } : undefined, primary); inspection = undefined;
    primary = await closePreserving(reopened ? async () => { await reopened!.close(); closeOrder.push("owned-reopened"); } : undefined, primary); reopened = undefined;
    primary = await closePreserving(ledger ? async () => { await ledger!.close(); closeOrder.push("ledger"); } : undefined, primary); ledger = undefined;
    primary = await closePreserving(root ? async () => { await root!.close(); closeOrder.push("owned-original"); } : undefined, primary); root = undefined;
    try { await rm(base, { recursive: true, force: true }); } catch (error) { if (!primary) primary = error; }
    if (primary) throw primary;
  }
}

async function reconstructLegacySource(legacy: SourceRecord): Promise<Readonly<{ record: Record<string, unknown>; before: string; after: string }>> {
  const base = await mkdtemp(join(tmpdir(), "pi-scholarly-legacy-")); const project = join(base, "project"); await mkdir(project); let root: OwnedRunRoot | undefined; let reopened: OwnedRunRoot | undefined; let ledger: EventLedger | undefined; let inspection: InspectedOwnedRunRoot | undefined; let primary: unknown;
  try {
    root = await createOwnedRunRoot({ trustedProject: project, repositoryRoot: project, topic: "legacy", runId: RUN, requestedPath: "run", ownershipToken: "e".repeat(64), now: () => new Date(AT) }); const path = root.path; const token = root.ownershipToken; await mkdir(join(path, ".state"), { mode: 0o700 }); let event = 0; ledger = await openEventLedger(join(path, ".state/events.jsonl"), { now: () => new Date(AT), eventId: () => `legacy-${++event}` }); await ledger.append("run_created", { run: runRecord() }); await ledger.reserveIdentity("attempt", ATTEMPT_1, "parent-generated"); await ledger.reserveIdentity("transaction", TX_1, "parent-generated"); await ledger.append("task_upserted", { task: taskRecord(1, [ATTEMPT_1]) }); await ledger.append("dispatch_intent", { attempt: attemptRecord(ATTEMPT_1, 1) }); await ledger.append("dispatch_started", { attemptId: ATTEMPT_1, pid: null, requestCorrelation: null }); const result = await ledger.append("result_recorded", { attemptId: ATTEMPT_1, resultSha256: HASH, manifestSha256: null, transactionId: TX_1 }); const prepared = await prepareTransaction(path, { schemaVersion: 1, transactionId: TX_1, runId: RUN, attemptId: ATTEMPT_1, sourceResultSeq: result.seq, createdAt: AT, sources: [legacy], claims: [], evidence: [], verifications: [], requests: [], calculations: [] }, foundationTransactionLimits); const ref = await commitTransaction(path, TX_1, foundationTransactionLimits); await ledger.append("records_committed", { transactionId: TX_1, sourceResultSeq: result.seq, transactionManifestPath: ref.relativePath, transactionManifestSha256: ref.sha256, sourceRefs: prepared.manifest.sourceRefs, claimRefs: [], evidenceRefs: [], verificationRefs: [], requestIds: [], calculationIds: [] }); await ledger.append("attempt_committed", { attemptId: ATTEMPT_1, transactionId: TX_1, taskId: TASK, sourceResultSeq: result.seq }); await ledger.close(); ledger = undefined; await root.close(); root = undefined; reopened = await openOwnedRunRoot(path, RUN, token); const events = await readVerifiedLedgerSnapshot(join(path, ".state/events.jsonl"), { trustedRoot: path }); const rebuilt = await reconstructCanonicalRecords(path, events, foundationTransactionLimits); inspection = await inspectOwnedRunRootIntegrity(path); const before = canonicalJson(await snapshotTree(path)); expectCode(() => validateProspectiveSourceIdentityFields(rebuilt.sources[0] as unknown as SourceRecord), ScholarlyIdentifierError, "url.invalid"); await inspection.revalidate(); const after = canonicalJson(await snapshotTree(path)); return { record: rebuilt.sources[0]!, before, after };
  } catch (error) { primary = error; throw error; }
  finally { primary = await closePreserving(inspection ? () => inspection!.close() : undefined, primary); primary = await closePreserving(reopened ? () => reopened!.close() : undefined, primary); primary = await closePreserving(ledger ? () => ledger!.close() : undefined, primary); primary = await closePreserving(root ? () => root!.close() : undefined, primary); try { await rm(base, { recursive: true, force: true }); } catch (error) { primary ??= error; } if (primary) throw primary; }
}

const names = [
  "uses exact owned root ledger transaction APIs and canonical event sequence",
  "closes ledger inspection and owned roots in finally without masking failures",
  "builds one branded snapshot per reopen and reuses it across evaluator query and citations",
  "uses the lower named foundation line kind-file and transaction byte ceilings on reopen",
  "keeps run data and local documents out of repository and package contents",
  "rebuilds identical scholarly decisions from reconstructed records and requests",
  "reconstructs legacy V1 records unchanged while prospective evaluation fails closed",
  "keeps historical revision closure valid and rejects stale refs introduced by latest records",
  "rejects omitted and duplicate reconstructed requests without mutating the run",
  "audits canonical URL duplicate and strong-identifier ambiguity after reopen",
  "proves citation and source URL transport metadata or resolver provenance under explicit HTTP policy",
  "rebuilds weak lineage components including common-parent forks",
  "returns bounded six-kind transitive query closure for every canonical edge",
  "requires canonical metadata for task and role query filters",
  "accepts disconfirmation citation and rejects only mismatched refs",
  "credits normative method and calculation derivation alternatives",
  "forwards identical URL policy through direct evidence evaluation",
  "fails closed on lineage conflict citation and query semantic corruption",
] as const;
function expectCode(action: () => unknown, klass: new (...args: any[]) => Error, code: string): void { try { action(); throw new Error("missing rejection"); } catch (error) { expect(error).toBeInstanceOf(klass); expect(error).toMatchObject({ code }); } }

describe("canonical scholarly reopen", () => {
  test(names[0], async () => { const value = await buildAndReopen(); expect(value.events.map((event: any) => event.type)).toEqual(["run_created", "identity_reserved", "identity_reserved", "identity_reserved", "task_upserted", "dispatch_intent", "dispatch_started", "request_intent_recorded", "request_result_recorded", "result_recorded", "records_committed", "attempt_committed", "identity_reserved", "identity_reserved", "identity_reserved", "task_upserted", "dispatch_intent", "dispatch_started", "request_intent_recorded", "request_result_recorded", "result_recorded", "records_committed", "attempt_committed"]); expect(value.events.filter((event: any) => event.type === "identity_reserved").map((event: any) => [event.payload.kind, event.payload.origin])).toEqual([["attempt", "parent-generated"], ["request", "child-import"], ["transaction", "parent-generated"], ["attempt", "parent-generated"], ["request", "child-import"], ["transaction", "parent-generated"]]); });
  test(names[1], async () => { const value = await buildAndReopen(); expect(value.closeOrder).toEqual(["ledger", "owned-original", "inspection", "owned-reopened"]); await expect(stat(value.base)).rejects.toMatchObject({ code: "ENOENT" }); });
  test(names[2], async () => { const value = await buildAndReopen(); expect(value.post.diagnostics.canonicalRecordVisits).toBe(10); expect(value.post).toEqual(value.pre); });
  test(names[3], async () => { const value = await buildAndReopen(); expect([value.effectiveFoundationRecordCanonicalBytes, value.effectiveFoundationKindFileBytes, value.effectiveFoundationTransactionCanonicalBytes]).toEqual([262_143, 1_048_576, 4_194_304]); });
  test(names[4], async () => { const value = await buildAndReopen(); expect(value.path).toContain("pi-scholarly-reopen-"); expect(value.entries).not.toContain("docs"); await expect(stat(value.base)).rejects.toMatchObject({ code: "ENOENT" }); });
  test(names[5], async () => { const first = await buildAndReopen(); const second = await buildAndReopen(); expect(first.post).toEqual(first.pre); expect(second.post).toEqual(first.post); expect(first.records.requests).toHaveLength(2); });
  test(names[6], async () => { const legacy = { ...sourceRecord(1), canonicalUrl: "not a canonical URL", retrievalRequestIds: [], metadataProvenance: [] }; const before = canonicalJson(legacy); expect(parseResearchRecord("sources", legacy).success).toBe(true); const rebuilt = await reconstructLegacySource(legacy); expect(canonicalJson(rebuilt.record)).toBe(before); expect(rebuilt.after).toBe(rebuilt.before); expect(canonicalJson(legacy)).toBe(before); });
  test(names[7], () => { const set = canonicalSet(); const snap = buildBoundedValidatedEvidenceSnapshot(set); expect(evaluateEvidenceRule(snap, { claimId: CLAIM, revision: 1 }).claimRef).toEqual({ claimId: CLAIM, revision: 1 }); const stale = { ...claimRecord(2), evidenceRefs: [{ evidenceId: EVIDENCE, revision: 1 }] }; const prior = { ...claimRecord(1), evidenceRefs: [] }; expectCode(() => evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...set, claims: [prior, stale] }), { claimId: CLAIM, revision: 2 }), EvidenceAdmissionError, "evidence.stale-latest-ref"); });
  test(names[8], () => { const set = canonicalSet(); expectCode(() => buildBoundedValidatedEvidenceSnapshot({ ...set, requests: [set.requests[0]!] }), EvidenceAdmissionError, "evidence.unresolved-ref"); expectCode(() => buildBoundedValidatedEvidenceSnapshot({ ...set, requests: [...set.requests, set.requests[0]!] }), EvidenceAdmissionError, "evidence.duplicate-request"); });
  test(names[9], () => { const base = sourceRecord(1); const compatible = { ...base, sourceId: "src-reopen.00000002", identifiers: { doi: null, pmid: null, pmcid: null } }; const fallback = { ...base, identifiers: { doi: null, pmid: null, pmcid: null } }; expectCode(() => buildBoundedValidatedEvidenceSnapshot({ sources: [fallback, compatible], claims: [], evidence: [], verifications: [], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1)], calculations: [] }), EvidenceAdmissionError, "evidence.duplicate-source-identity"); const strongBase = { ...base, identifiers: { doi: "10.1234/base", pmid: null, pmcid: null } }; const conflicting = { ...compatible, identifiers: { doi: "10.1234/other", pmid: null, pmcid: null } }; expectCode(() => buildBoundedValidatedEvidenceSnapshot({ sources: [strongBase, conflicting], claims: [], evidence: [], verifications: [], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1)], calculations: [] }), EvidenceAdmissionError, "evidence.ambiguous-source-identity"); });
  test(names[10], async () => { const value = await buildAndReopen(); expect(JSON.parse(value.post.citations).citations).toHaveLength(1); const resolver = { ...sourceRecord(1), identifiers: { doi: "10.1234/resolver", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/resolver"), retrievalRequestIds: [] }; const set = { sources: [resolver], claims: [claimRecord(1)], evidence: [evidenceRecord(1)], verifications: [], requests: [], calculations: [] }; expect(assignCitationMappings(buildBoundedValidatedEvidenceSnapshot(set), [{ sourceId: SOURCE, revision: 1 }], []).citations).toHaveLength(1); });
  test(names[11], () => { const parent = sourceRecord(1); const a = { ...parent, sourceId: "src-reopen.forka001", identifiers: { doi: "10.1234/forka", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/forka"), lineage: { ...parent.lineage, relatedSourceIds: [parent.sourceId], relationTypes: ["reports" as const] } }; const b = { ...a, sourceId: "src-reopen.forkb001", identifiers: { doi: "10.1234/forkb", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/forkb") }; const graph = buildLineageGraph([parent, a, b]); expect(compareSourceIndependence(graph, { sourceId: a.sourceId, revision: 1 }, { sourceId: b.sourceId, revision: 1 }).status).toBe("dependent"); const disconnected = { ...a, sourceId: "src-reopen.free0001", identifiers: { doi: "10.1234/free", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/free"), lineage: { ...a.lineage, studyId: "study-free", relatedSourceIds: [], relationTypes: [] } }; const extended = buildLineageGraph([parent, a, b, disconnected]); expect(compareSourceIndependence(extended, { sourceId: a.sourceId, revision: 1 }, { sourceId: disconnected.sourceId, revision: 1 }).status).toBe("independent"); expectCode(() => buildLineageGraph([{ ...a, lineage: { ...a.lineage, relatedSourceIds: ["src-reopen.missing1"] } }]), LineageError, "lineage.unresolved-ref"); });
  test(names[12], async () => { const value = await buildAndReopen(); const selection = JSON.parse(value.post.selection); for (const kind of ["sources", "claims", "evidence", "verifications", "requests", "calculations"]) expect(selection[kind].length).toBeGreaterThan(0); const snapshot = buildBoundedValidatedEvidenceSnapshot(value.records); const bounded = buildEvidenceIndex({ snapshot }, { maxSelectedPerKind: { sources: 1, claims: 1, evidence: 1, verifications: 1, requests: 1, calculations: 1 }, maxTotalSelectedRecords: 6 }); expectCode(() => bounded.query({ verificationRefs: [{ verificationId: VERIFY, revision: 1 }], limit: 10, maxSelectedBytes: 1_000_000 }), EvidenceQueryError, "query.closure-too-large"); });
  test(names[13], async () => { const value = await buildAndReopen(); const snapshot = buildBoundedValidatedEvidenceSnapshot(value.records); expect(buildEvidenceIndex({ snapshot, ledgerEvents: value.events }).query({ taskIds: [TASK], roles: ["literature-searcher"], limit: 10, maxSelectedBytes: 1_000_000 }).evidence.length).toBeGreaterThan(0); expectCode(() => buildEvidenceIndex({ snapshot }).query({ taskIds: [TASK], limit: 10, maxSelectedBytes: 1_000_000 }), EvidenceQueryError, "query.metadata-required"); });
  test(names[14], () => { const set = { ...canonicalSet(), evidence: [evidenceRecord(1), evidenceRecord(2, "contradicting")] }; const snapshot = buildBoundedValidatedEvidenceSnapshot(set); expect(assignCitationMappings(snapshot, [{ sourceId: SOURCE, revision: 2 }], [{ sourceRef: { sourceId: SOURCE, revision: 2 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]).citations[0]!.evidenceRefs).toHaveLength(1); const other = { ...sourceRecord(1), sourceId: "src-reopen.other001", identifiers: { doi: "10.1234/other", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/other") }; expectCode(() => assignCitationMappings(buildBoundedValidatedEvidenceSnapshot({ ...set, sources: [...set.sources, other] }), [{ sourceId: other.sourceId, revision: 1 }], [{ sourceRef: { sourceId: other.sourceId, revision: 1 }, claimRefs: [{ claimId: CLAIM, revision: 2 }], evidenceRefs: [{ evidenceId: EVIDENCE, revision: 2 }] }]), CitationError, "citation.cross-source-evidence"); });
  test(names[15], () => { const base = canonicalSet(); const method = { ...evidenceRecord(2), evidenceType: "derived" as const, sourceRef: { sourceId: SOURCE, revision: 2 }, quotes: [], extractedValues: [{ value: "1", numericValue: 1, unit: null, context: "result" }], method: "method" }; const methodDecision = evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...base, evidence: [evidenceRecord(1), method] }), { claimId: CLAIM, revision: 2 }); expect(methodDecision.blockers).not.toContain("claim.invalid-derived-evidence"); const calculated = { ...method, sourceRef: null, calculationId: CALC, method: null }; const calculationDecision = evaluateEvidenceRule(buildBoundedValidatedEvidenceSnapshot({ ...base, evidence: [evidenceRecord(1), calculated] }), { claimId: CLAIM, revision: 2 }); expect(calculationDecision.blockers).not.toContain("claim.invalid-derived-evidence"); const bare = { ...calculated, calculationId: null }; expectCode(() => buildBoundedValidatedEvidenceSnapshot({ ...base, evidence: [evidenceRecord(1), bare] }), EvidenceAdmissionError, "evidence.invalid-input"); });
  test(names[16], () => { const policy = Object.freeze({ allowHttp: false }); const snapshot = buildBoundedValidatedEvidenceSnapshot(canonicalSet(), { sourceUrlPolicy: policy }); expect(evaluateEvidenceRule(snapshot, { claimId: CLAIM, revision: 2 }).claimRef.revision).toBe(2); const httpUrl = "http://trusted.example.org/reopen"; const httpSource = { ...sourceRecord(1), canonicalUrl: httpUrl }; const httpRequest = { ...requestRecord(REQUEST_1, ATTEMPT_1, 1), normalizedInput: { query: null, identifier: null, url: httpUrl, parameters: [] }, requestedUrl: httpUrl, finalUrl: httpUrl }; const httpSet = { sources: [httpSource], claims: [claimRecord(1)], evidence: [evidenceRecord(1)], verifications: [], requests: [httpRequest], calculations: [] }; const allowed = buildBoundedValidatedEvidenceSnapshot(httpSet, { sourceUrlPolicy: { allowHttp: true, approvedHttpHosts: ["trusted.example.org"], accessPolicySha256: HASH } }); expect(evaluateEvidenceRule(allowed, { claimId: CLAIM, revision: 1 }).claimRef.revision).toBe(1); });
  test(names[17], () => { const a = sourceRecord(1); const b = { ...a, sourceId: "src-reopen.cycle001", identifiers: { doi: "10.1234/cycle", pmid: null, pmcid: null }, canonicalUrl: canonicalDoiUrl("10.1234/cycle"), lineage: { ...a.lineage, relatedSourceIds: [a.sourceId], relationTypes: ["version-of" as const] } }; const cyclic = { ...a, lineage: { ...a.lineage, relatedSourceIds: [b.sourceId], relationTypes: ["version-of" as const] } }; expectCode(() => buildBoundedValidatedEvidenceSnapshot({ sources: [cyclic, b], claims: [], evidence: [], verifications: [], requests: [requestRecord(REQUEST_1, ATTEMPT_1, 1)], calculations: [] }), EvidenceAdmissionError, "evidence.lineage-invalid"); const committed = buildBoundedValidatedEvidenceSnapshot(canonicalSet()); expectCode(() => assignCitationMappings(committed, [{ sourceId: "src-reopen.pending01", revision: 1 }], []), CitationError, "citation.unresolved-ref"); });
});
