import {types as utilTypes} from "node:util";
import {
  AcademicAcquisitionError,
  assertAcademicAcquisitionDependencyFactoryInternal,
  createAcademicAcquisitionCallCapabilities,
  createAcademicAcquisitionClient,
  createDefaultAcademicAcquisitionDependencyFactoryInternal,
  getAcademicAcquisitionClientNormalizedOptionsInternal,
  type AcademicAcquisitionClient,
  type AcademicAcquisitionDependencyFactoryInternal,
} from "../../src/acquisition/coordinator.js";
import type {
  AcademicAcquisitionOptions,AcademicAcquisitionResult,AcademicFetchInput,AcademicSearchInput,
  NormalizedAcquisitionOptionsInternal,
} from "../../src/acquisition/contracts.js";

export type AcademicToolErrorCode=
 |"academic-tool.invalid-input"|"academic-tool.invalid-options"
 |"academic-tool.disabled"|"academic-tool.pre-session"|"academic-tool.unavailable"
 |"academic-tool.stale-generation"|"academic-tool.shutdown"
 |"academic-tool.cancelled"|"academic-tool.deadline-exceeded"
 |"academic-tool.security-policy"|"academic-tool.sink-settlement-failure"
 |"academic-tool.provider-failure"|"academic-tool.result-too-large"
 |"academic-tool.truncation-invariant"|"academic-tool.internal-contract";
export class AcademicToolError extends Error{declare readonly name:"AcademicToolError";readonly code:AcademicToolErrorCode;constructor(code:AcademicToolErrorCode){super(code);this.code=code;Object.defineProperty(this,"name",{value:"AcademicToolError",enumerable:true,writable:false,configurable:true});}}
const toolFail=(code:AcademicToolErrorCode):never=>{throw new AcademicToolError(code);};

export interface AcademicToolDependenciesDescriptor{readonly enabled?:boolean;readonly options?:AcademicAcquisitionOptions;readonly acquisitionDependencyFactory?:AcademicAcquisitionDependencyFactoryInternal;}
export interface AcademicToolDependencies{readonly capabilityKind:"academic-tool-dependencies";}
type DependencyState=Readonly<{enabled:boolean;options:AcademicAcquisitionOptions|undefined;factory:AcademicAcquisitionDependencyFactoryInternal}>;
const dependencyStates=new WeakMap<object,DependencyState>();
function plainDescriptor(value:unknown):PropertyDescriptorMap{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)toolFail("academic-tool.internal-contract");const descriptors=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(descriptors),allowed=["enabled","options","acquisitionDependencyFactory"];if(keys.some(key=>typeof key!=="string"||!allowed.includes(key))||keys.length>allowed.length)toolFail("academic-tool.internal-contract");for(const key of keys as string[]){const descriptor=descriptors[key]!;if(!descriptor.enumerable||!("value" in descriptor))toolFail("academic-tool.internal-contract");}return descriptors;}
export function createAcademicToolDependencies(descriptor:AcademicToolDependenciesDescriptor={}):AcademicToolDependencies{const d=plainDescriptor(descriptor),enabledValue=d.enabled?.value;if(enabledValue!==undefined&&typeof enabledValue!=="boolean")toolFail("academic-tool.internal-contract");const factory=(d.acquisitionDependencyFactory?.value??createDefaultAcademicAcquisitionDependencyFactoryInternal()) as AcademicAcquisitionDependencyFactoryInternal;try{assertAcademicAcquisitionDependencyFactoryInternal(factory);}catch{return toolFail("academic-tool.internal-contract");}const output=Object.freeze({capabilityKind:"academic-tool-dependencies" as const});dependencyStates.set(output,Object.freeze({enabled:enabledValue??true,options:d.options?.value as AcademicAcquisitionOptions|undefined,factory}));return output;}
export function createDefaultAcademicToolDependencies():AcademicToolDependencies{return createAcademicToolDependencies();}
export function getAcademicToolDependenciesInternal(value:AcademicToolDependencies):DependencyState{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!Object.isFrozen(value))toolFail("academic-tool.internal-contract");const state=dependencyStates.get(value as object);if(!state)toolFail("academic-tool.internal-contract");return state!;}

export interface AcademicSessionManager{readonly generation:number;search(input:AcademicSearchInput,signal?:AbortSignal):Promise<AcademicAcquisitionResult>;fetch(input:AcademicFetchInput,signal?:AbortSignal):Promise<AcademicAcquisitionResult>;shutdown():Promise<void>;}
type ManagerState={dependencies:DependencyState;generation:number;lifecycle:"open"|"stale-generation"|"shutdown";controller:AbortController;client:AcademicAcquisitionClient|null;normalized:NormalizedAcquisitionOptionsInternal|null;shutdownPromise:Promise<void>|null;};
const managerStates=new WeakMap<object,ManagerState>();
const ABORTED=Object.getOwnPropertyDescriptor(AbortSignal.prototype,"aborted")!.get!,THROW=AbortSignal.prototype.throwIfAborted,ADD=AbortSignal.prototype.addEventListener,REMOVE=AbortSignal.prototype.removeEventListener;
function managerState(value:unknown):ManagerState{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!Object.isFrozen(value))toolFail("academic-tool.internal-contract");const state=managerStates.get(value as object);if(!state)toolFail("academic-tool.internal-contract");return state!;}
function genuineSignal(value:unknown):AbortSignal|null{if(value===undefined)return null;if(value===null||typeof value!=="object"||utilTypes.isProxy(value))toolFail("academic-tool.internal-contract");try{if(Object.getOwnPropertyDescriptor(value,"aborted")!==undefined||Object.getOwnPropertyDescriptor(value,"throwIfAborted")!==undefined)toolFail("academic-tool.internal-contract");const aborted=ABORTED.call(value) as boolean;let threw=false;try{THROW.call(value);}catch{threw=true;}if(aborted!==threw)toolFail("academic-tool.internal-contract");return value as AbortSignal;}catch(error){if(error instanceof AcademicToolError)throw new AcademicToolError(error.code);return toolFail("academic-tool.internal-contract");}}
function ownData(value:unknown,allowed:readonly string[],required:readonly string[]):PropertyDescriptorMap{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)toolFail("academic-tool.invalid-input");const d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(d);if(keys.some(key=>typeof key!=="string"||!allowed.includes(key))||required.some(key=>!keys.includes(key)))toolFail("academic-tool.invalid-input");for(const key of keys as string[]){const item=d[key]!;if(!item.enumerable||!("value" in item))toolFail("academic-tool.invalid-input");}return d;}
function denseStrings(value:unknown,maximum:number,enums?:readonly string[]):readonly string[]{if(!Array.isArray(value)||utilTypes.isProxy(value)){toolFail("academic-tool.invalid-input");}const lengthDescriptor=Object.getOwnPropertyDescriptor(value,"length");if(!lengthDescriptor||!("value" in lengthDescriptor)||!Number.isSafeInteger(lengthDescriptor.value)||lengthDescriptor.value<0||lengthDescriptor.value>maximum)toolFail("academic-tool.invalid-input");const length=lengthDescriptor!.value as number,d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(d);if(keys.length!==length+1)toolFail("academic-tool.invalid-input");const output:string[]=[];for(let index=0;index<length;index++){const item=d[String(index)];if(!item||!("value" in item)||!item.enumerable||typeof item.value!=="string"||(enums&&!enums.includes(item.value)))toolFail("academic-tool.invalid-input");output.push(item.value);}return Object.freeze(output);}
function integer(value:unknown,minimum:number,maximum:number):number{if(typeof value!=="number"||!Number.isSafeInteger(value)||value<minimum||value>maximum)toolFail("academic-tool.invalid-input");return value as number;}
function searchInput(value:unknown):AcademicSearchInput{const d=ownData(value,["queries","providers","maxResultsPerQuery","publicationTypes","fromYear","toYear"],["queries"]),queries=denseStrings(d.queries!.value,16);if(queries.length<1)toolFail("academic-tool.invalid-input");const output:Record<string,unknown>={queries};if(d.providers)output.providers=denseStrings(d.providers.value,3,["crossref","openalex","pubmed"]);if(d.maxResultsPerQuery)output.maxResultsPerQuery=integer(d.maxResultsPerQuery.value,1,100);if(d.publicationTypes)output.publicationTypes=denseStrings(d.publicationTypes.value,4,["journal-article","review","dataset","other"]);if(d.fromYear)output.fromYear=integer(d.fromYear.value,1,9999);if(d.toYear)output.toYear=integer(d.toYear.value,1,9999);return Object.freeze(output) as unknown as AcademicSearchInput;}
function fetchInput(value:unknown):AcademicFetchInput{const d=ownData(value,["identifierKind","identifier"],["identifierKind","identifier"]),kind=d.identifierKind!.value,identifier=d.identifier!.value;if(!["doi","pmid","pmcid"].includes(kind)||typeof identifier!=="string")toolFail("academic-tool.invalid-input");return Object.freeze({identifierKind:kind,identifier}) as AcademicFetchInput;}
const acquisitionMap:Readonly<Record<string,AcademicToolErrorCode>>=Object.freeze({"acquisition.invalid-input":"academic-tool.invalid-input","acquisition.too-many-queries":"academic-tool.invalid-input","acquisition.query-too-large":"academic-tool.invalid-input","acquisition.too-many-partitions":"academic-tool.invalid-input","acquisition.invalid-options":"academic-tool.invalid-options","acquisition.closed":"academic-tool.shutdown","acquisition.cancelled":"academic-tool.cancelled","acquisition.deadline-exceeded":"academic-tool.deadline-exceeded","acquisition.security-failure":"academic-tool.security-policy","acquisition.sink-settlement-failure":"academic-tool.sink-settlement-failure","acquisition.provider-failure":"academic-tool.provider-failure","acquisition.result-too-large":"academic-tool.result-too-large","acquisition.internal-contract":"academic-tool.internal-contract"});
export function mapAcademicAcquisitionErrorInternal(error:unknown):never{if(error instanceof AcademicAcquisitionError){const d=Object.getOwnPropertyDescriptor(error,"code"),code=d&&"value" in d?d.value:null;if(typeof code==="string"&&acquisitionMap[code])return toolFail(acquisitionMap[code]!);}return toolFail("academic-tool.internal-contract");}
function mapped(error:unknown,state:ManagerState,external:AbortSignal|null,constructing=false):never{if(state.lifecycle==="stale-generation")return toolFail("academic-tool.stale-generation");if(state.lifecycle==="shutdown")return toolFail("academic-tool.shutdown");if(external&&ABORTED.call(external))return toolFail("academic-tool.cancelled");if(error instanceof AcademicToolError)return toolFail(error.code);if(constructing&&error instanceof AcademicAcquisitionError){const d=Object.getOwnPropertyDescriptor(error,"code"),code=d&&"value" in d?d.value:null;if(code==="acquisition.invalid-capability")return toolFail("academic-tool.unavailable");}if(constructing&&!(error instanceof AcademicAcquisitionError))return toolFail("academic-tool.unavailable");return mapAcademicAcquisitionErrorInternal(error);}
function client(state:ManagerState):AcademicAcquisitionClient{if(state.lifecycle!=="open")toolFail(state.lifecycle==="stale-generation"?"academic-tool.stale-generation":"academic-tool.shutdown");if(!state.dependencies.enabled)toolFail("academic-tool.disabled");if(state.client)return state.client;try{const created=createAcademicAcquisitionClient(state.dependencies.options,state.dependencies.factory);state.client=created;state.normalized=getAcademicAcquisitionClientNormalizedOptionsInternal(created);return created;}catch(error){return mapped(error,state,null,true);}}
async function invoke(state:ManagerState,kind:"search"|"fetch",input:unknown,signalValue?:AbortSignal):Promise<AcademicAcquisitionResult>{if(!state.dependencies.enabled)toolFail("academic-tool.disabled");if(state.lifecycle!=="open")toolFail(state.lifecycle==="stale-generation"?"academic-tool.stale-generation":"academic-tool.shutdown");let inputValue:AcademicSearchInput|AcademicFetchInput,external:AbortSignal|null=null;try{inputValue=kind==="search"?searchInput(input):fetchInput(input);external=genuineSignal(signalValue);if(external&&ABORTED.call(external))toolFail("academic-tool.cancelled");}catch(error){return mapped(error,state,external??null);}const controller=new AbortController(),generationSignal=state.controller.signal,abortGeneration=()=>controller.abort(),abortExternal=()=>controller.abort();ADD.call(generationSignal,"abort",abortGeneration,{once:true});if(external)ADD.call(external,"abort",abortExternal,{once:true});if(ABORTED.call(generationSignal))abortGeneration();if(external&&ABORTED.call(external))abortExternal();try{const acquisitionClient=client(state),capability=createAcademicAcquisitionCallCapabilities({signal:controller.signal}),result=kind==="search"?await acquisitionClient.search(inputValue as AcademicSearchInput,capability):await acquisitionClient.fetch(inputValue as AcademicFetchInput,capability);if(state.lifecycle!=="open")toolFail(state.lifecycle==="stale-generation"?"academic-tool.stale-generation":"academic-tool.shutdown");return result;}catch(error){return mapped(error,state,external);}finally{REMOVE.call(generationSignal,"abort",abortGeneration);if(external)REMOVE.call(external,"abort",abortExternal);}}
export function createAcademicSessionManager(dependencies:AcademicToolDependencies,generation:number):AcademicSessionManager{const dependency=getAcademicToolDependenciesInternal(dependencies);if(!Number.isSafeInteger(generation)||generation<1)toolFail("academic-tool.internal-contract");let manager!:AcademicSessionManager;const state:ManagerState={dependencies:dependency,generation,controller:new AbortController(),lifecycle:"open",client:null,normalized:null,shutdownPromise:null};manager=Object.freeze({generation,search(input:AcademicSearchInput,signal?:AbortSignal){return invoke(state,"search",input,signal);},fetch(input:AcademicFetchInput,signal?:AbortSignal){return invoke(state,"fetch",input,signal);},shutdown(){if(state.shutdownPromise)return state.shutdownPromise;if(state.lifecycle==="open")state.lifecycle="shutdown";state.controller.abort();state.shutdownPromise=(async()=>{if(state.client)try{await state.client.close();}catch{/* redacted */}})();return state.shutdownPromise;}});managerStates.set(manager,state);return manager;}
export function detachAcademicSessionManagerInternal(manager:AcademicSessionManager,reason:"stale-generation"|"shutdown"):void{const state=managerState(manager);if(state.lifecycle!=="open")return;state.lifecycle=reason;state.controller.abort();}
export function getAcademicSessionNormalizedOptionsInternal(manager:AcademicSessionManager):NormalizedAcquisitionOptionsInternal|null{return managerState(manager).normalized;}
