import fs from "node:fs";
import path from "node:path";
import {describe,expect,test,vi} from "vitest";

import {normalizeAcquisitionOptions,type AcademicTransportOptions} from "../../src/acquisition/contracts.js";
import {createContentDecodeCapabilitiesInternal,createSecureJsonTransport,createSecureTransportCapabilitiesInternal,openSecureTransportRequestInternal,type ContentDecodeOperationsDescriptorInternal} from "../../src/acquisition/content-decoding-internal.js";
import {getProviderJsonSettlementInternal,snapshotProviderJsonInternal} from "../../src/acquisition/json-wire-scanner-internal.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import type {SecureTransportRequest} from "../../src/acquisition/transport.js";
import {createMockSecureTransportCapabilities,type MockSecureTransportControl} from "../helpers/mock-secure-transport.js";

const HASH="a".repeat(64);
const request=():SecureTransportRequest=>({partitionKey:`partition-v1-${HASH}`,partitionKeySha256:HASH,provider:"crossref",operation:"search",endpointClass:"crossref-search",target:"crossref",url:"https://api.crossref.org/works?query=x",headers:Object.freeze([{name:"accept",value:"application/json"}])});
type RequestRecord=MockSecureTransportControl["requests"][number];
function secure(record:RequestRecord){record.callbacks.onSecureConnected({address:record.options.pinnedAddress,family:record.options.family,hostnameVerified:true,authorized:true,authorizationError:null});}
async function waitFor(condition:()=>boolean){for(let index=0;index<200;index+=1){if(condition())return;await Promise.resolve();}throw new Error("condition not reached");}
function setup(decode:ContentDecodeOperationsDescriptorInternal["decodeContentLayer"],transportOptions:AcademicTransportOptions={}){const options=normalizeAcquisitionOptions({transport:transportOptions});const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const pinned=createPinnedHopRuntimeInternal({maxDnsAddresses:options.transport.maxDnsAddresses,maxCanonicalUrlBytes:options.transport.maxCanonicalUrlBytes},node);const scheduler=createNodeRequestDeadlineSchedulerCapabilitiesInternal(node);const decoder=createContentDecodeCapabilitiesInternal({decodeContentLayer:decode});const capabilities=createSecureTransportCapabilitiesInternal(pinned,decoder,scheduler);const transport=createSecureJsonTransport(options,capabilities);return{options,mock,transport,decoder,pinned,scheduler};}
async function start(value:ReturnType<typeof setup>,payload:Uint8Array,encoding?:string){const handle=openSecureTransportRequestInternal(value.transport,request());await waitFor(()=>value.mock.requests.length===1);const record=value.mock.requests[0]!;secure(record);const headers=encoding===undefined?["content-length",String(payload.byteLength)]:["content-encoding",encoding,"content-length",String(payload.byteLength)];record.callbacks.onResponse(200,"1.1",headers);record.callbacks.onData(payload);record.callbacks.onEnd();return handle;}
async function complete(value:ReturnType<typeof setup>,payload:Uint8Array,encoding?:string){const handle=await start(value,payload,encoding);return{handle,settlement:await handle.completion};}
function failureCode(settlement:Awaited<ReturnType<ReturnType<typeof setup>["transport"]["request"]>>){return settlement.outcome==="success"?null:settlement.failureCode;}
const identity=async(_encoding:"gzip"|"deflate"|"br",input:Uint8Array)=>new Uint8Array(input);

 describe("bounded scholarly content decoding",()=>{
  test("accepts only Task1 authentic normalized options and passes its frozen transport view without defaults",async()=>{const options=normalizeAcquisitionOptions(undefined);const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const pinned=createPinnedHopRuntimeInternal(undefined,node);const scheduler=createNodeRequestDeadlineSchedulerCapabilitiesInternal(node);let decoderCalls=0;const decoder=createContentDecodeCapabilitiesInternal({decodeContentLayer:async()=>{decoderCalls+=1;return new Uint8Array();}});const capabilities=createSecureTransportCapabilitiesInternal(pinned,decoder,scheduler);expect(()=>createSecureTransportCapabilitiesInternal(pinned,decoder,scheduler)).toThrowError(expect.objectContaining({code:"transport.invalid-capability"}));expect(()=>createSecureJsonTransport(Object.freeze({...options}) as never,capabilities)).toThrowError(expect.objectContaining({code:"transport.invalid-capability"}));expect(decoderCalls).toBe(0);const transport=createSecureJsonTransport(options,capabilities);expect(Object.isFrozen(transport)&&transport.capabilityKind).toBe("secure-json-transport");expect(()=>createSecureJsonTransport(options,capabilities)).toThrowError(expect.objectContaining({code:"transport.invalid-capability"}));await transport.close();});

  test("rejects encoding layer count before constructing any decoder",async()=>{let calls=0;const value=setup(async()=>{calls+=1;return new Uint8Array();},{maxEncodingLayers:1});const result=await complete(value,new TextEncoder().encode("{}"),"gzip, br");expect(failureCode(result.settlement)).toBe("transport.too-many-encoding-layers");expect(calls).toBe(0);await result.handle.close();await value.transport.close();});

  test("streams gzip deflate brotli with checked per-layer and whole-stack caps",async()=>{const calls:Array<{encoding:string;input:number;maximum:number;decoded:number;ratio:number}>=[];const value=setup(async(encoding,input,maximum,decoded,ratio)=>{calls.push({encoding,input:input.byteLength,maximum,decoded,ratio});return encoding==="br"?new Uint8Array([1,2]):encoding==="deflate"?new Uint8Array([3,4,5]):new TextEncoder().encode(`{"ok":true}`);},{maxDecodedBodyBytes:64,maxDecompressionRatio:64,maxEncodingLayers:3});const result=await complete(value,new Uint8Array([9]),"gzip, deflate, br");expect(result.settlement.outcome).toBe("success");expect(calls.map((call)=>call.encoding)).toEqual(["br","deflate","gzip"]);expect(calls.every((call)=>call.maximum===Math.min(call.decoded,call.ratio))).toBe(true);const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/content-decoding-internal.ts"),"utf8");expect(source).toContain("createGunzip");expect(source).toContain("createInflate");expect(source).toContain("createBrotliDecompress");expect(source).not.toMatch(/gunzipSync|inflateSync|brotliDecompressSync/u);await result.handle.close();await value.transport.close();});

  test("uses decoded-too-large for exact ties and simultaneous chunk breaches",async()=>{for(const output of [new Uint8Array(5),new Uint8Array(6)]){const value=setup(async()=>output,{maxDecodedBodyBytes:4,maxDecompressionRatio:4});const result=await complete(value,new Uint8Array([1]),"gzip");expect(failureCode(result.settlement)).toBe("transport.decoded-too-large");await result.handle.close();await value.transport.close();}const ratio=setup(async()=>new Uint8Array(3),{maxDecodedBodyBytes:8,maxDecompressionRatio:2});const ratioResult=await complete(ratio,new Uint8Array([1]),"gzip");expect(failureCode(ratioResult.settlement)).toBe("transport.decompression-ratio");await ratioResult.handle.close();await ratio.transport.close();});

  test("destroys transforms before retaining oversized output and concatenates only after end",async()=>{let release!:()=>void;let calls=0;const value=setup(async(_encoding,_input,maximum)=>{calls+=1;await new Promise<void>((resolve)=>{release=resolve;});return new Uint8Array(maximum+1);},{maxDecodedBodyBytes:8,maxDecompressionRatio:8});const pending=complete(value,new Uint8Array([1]),"gzip");await waitFor(()=>calls===1);let settled=false;void pending.then(()=>{settled=true;});await Promise.resolve();expect(settled).toBe(false);release();const result=await pending;expect(failureCode(result.settlement)).toBe("transport.decoded-too-large");await result.handle.close();await value.transport.close();const invalidUtf8=setup(identity);const utf8Result=await complete(invalidUtf8,new Uint8Array([0xff]));expect(failureCode(utf8Result.settlement)).toBe("transport.invalid-utf8");await utf8Result.handle.close();await invalidUtf8.transport.close();const malformed=setup(async()=>{throw new Error("SECRET");});const malformedResult=await complete(malformed,new Uint8Array([1]),"gzip");expect(failureCode(malformedResult.settlement)).toBe("transport.decompression-failed");await malformedResult.handle.close();await malformed.transport.close();});

  test("propagates one request deadline through decode chunks JSON scan sidecar and final close",async()=>{let signal:AbortSignal|undefined;const value=setup(async(_encoding,input,_maximum,_decoded,_ratio,currentSignal)=>{signal=currentSignal;expect(currentSignal.aborted).toBe(false);return new TextEncoder().encode(`{"records":[1]}`);});const result=await complete(value,new Uint8Array([1]),"gzip");expect(result.settlement.outcome).toBe("success");if(result.settlement.outcome!=="success")throw new Error("expected success");const sidecar=getProviderJsonSettlementInternal(result.settlement);expect(snapshotProviderJsonInternal(sidecar.value!)).toEqual({records:[1]});expect(Object.isFrozen(sidecar)).toBe(true);expect(getProviderJsonSettlementInternal(result.settlement)).toBe(sidecar);expect(signal?.aborted).toBe(false);expect(value.mock.timerMilliseconds.size).toBe(0);await result.handle.close();await value.transport.close();const invalid=setup(identity);const invalidResult=await complete(invalid,new TextEncoder().encode(`{"a":1,"\\u0061":2}`));expect(failureCode(invalidResult.settlement)).toBe("transport.protocol-invalid");expect(getProviderJsonSettlementInternal(invalidResult.settlement as never)).toEqual({value:null,errorCode:"json.duplicate-key"});await invalidResult.handle.close();await invalid.transport.close();});

  test("rejects forged cross-owner or expired deadline and ignores late transform scanner callbacks",async()=>{let release!:()=>void;const value=setup(async()=>await new Promise<Uint8Array>((resolve)=>{release=()=>resolve(new TextEncoder().encode(`{"late":true}`));}));const handle=await start(value,new Uint8Array([1]),"gzip");await waitFor(()=>release!==undefined);handle.forceClose();release();const settlement=await handle.completion;expect(failureCode(settlement)).toBe("transport.cancelled");expect(()=>getProviderJsonSettlementInternal(settlement as never)).toThrow();await handle.close();await value.transport.close();let expire!:()=>void;const expired=setup(async()=>await new Promise<Uint8Array>((resolve)=>{expire=()=>resolve(new TextEncoder().encode(`{"late":true}`));}),{requestDeadlineMs:10,connectTimeoutMs:10});const expiredHandle=await start(expired,new Uint8Array([1]),"gzip");await waitFor(()=>expire!==undefined);expired.mock.now+=10;for(const timer of [...expired.mock.timers.values()])timer();expire();expect(failureCode(await expiredHandle.completion)).toBe("transport.deadline-exceeded");await expiredHandle.close();await expired.transport.close();});
 });
