import fs from "node:fs";
import path from "node:path";
import {describe,expect,test,vi} from "vitest";
import {normalizeAcquisitionOptions,validateAcademicAcquisitionResult,type AcademicAcquisitionOptions,type AcademicAcquisitionResult} from "../../src/acquisition/contracts.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import {createContentDecodeCapabilitiesInternal,createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createCrossrefAdapter} from "../../src/acquisition/providers/crossref.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {createPubmedAdapter} from "../../src/acquisition/providers/pubmed.js";
import {createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {createInvocationSchedulerCapabilitiesInternal} from "../../src/acquisition/scheduler-internal.js";
import {
  AcademicAcquisitionError,acquisitionSinkBeforeDispatchInternal,acquisitionSinkSettledInternal,
  createAcademicAcquisitionCallCapabilities,createAcademicAcquisitionCallCapabilitiesInternal,
  createAcademicAcquisitionClient,createAcademicAcquisitionDependencyFactoryInternal,
  createAcquisitionProvenanceSinkInternal,
  getAcademicAcquisitionClientNormalizedOptionsInternal,
  type AcademicAcquisitionDependencyFactoryInternal,
} from "../../src/acquisition/coordinator.js";
import {createMockSecureTransportCapabilities,type MockSecureTransportControl} from "../helpers/mock-secure-transport.js";

const fixture=(name:string)=>new Uint8Array(fs.readFileSync(path.join(import.meta.dirname,"../fixtures/acquisition",name)));
const bodies={crossref:fixture("crossref-search.json"),openalex:fixture("openalex-search.json"),esearch:fixture("pubmed-esearch.json"),esummary:fixture("pubmed-esummary.json"),elink:fixture("pubmed-elink.json"),pmc:fixture("pmc-bioc.json")};
function bodyFor(url:string):Uint8Array{if(url.includes("api.crossref"))return bodies.crossref;if(url.includes("api.openalex"))return bodies.openalex;if(url.includes("esearch.fcgi"))return bodies.esearch;if(url.includes("esummary.fcgi"))return bodies.esummary;if(url.includes("elink.fcgi"))return bodies.elink;return bodies.pmc;}
function fakeScheduler(){let now=0,next=0;const callbacks=new Map<number,()=>void>();return{capability:createInvocationSchedulerCapabilitiesInternal({monotonicNow:()=>now,setTimeout:callback=>{const id=++next;callbacks.set(id,callback);return id;},clearTimeout:id=>{callbacks.delete(id as number);}}),advance(ms:number){now+=ms;for(const callback of [...callbacks.values()])callback();callbacks.clear();},callbacks};}
function dependencies(overrides:Partial<Record<"createTransport"|"createCrossref"|"createOpenalex"|"createPubmed"|"createPmc"|"createScheduler",(...args:any[])=>unknown>>={}){const mocks:MockSecureTransportControl[]=[],schedulers:ReturnType<typeof fakeScheduler>[]=[],seen:unknown[]=[];const descriptor={createTransport:(options:any)=>{seen.push(options);if(overrides.createTransport)return overrides.createTransport(options);const mock=createMockSecureTransportCapabilities(),node=createNodeRuntimeCapabilitiesInternal(mock.ops);mocks.push(mock);return createSecureJsonTransport(options,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node)));},createCrossref:(options:any)=>{seen.push(options);return overrides.createCrossref?.(options)??createCrossrefAdapter();},createOpenalex:(options:any)=>{seen.push(options);return overrides.createOpenalex?.(options)??createOpenAlexAdapter();},createPubmed:(options:any)=>{seen.push(options);return overrides.createPubmed?.(options)??createPubmedAdapter();},createPmc:(options:any)=>{seen.push(options);return overrides.createPmc?.(options)??createPmcAdapter();},createScheduler:(options:any)=>{seen.push(options);if(overrides.createScheduler)return overrides.createScheduler(options);const scheduler=fakeScheduler();schedulers.push(scheduler);return scheduler.capability;}};return{factory:createAcademicAcquisitionDependencyFactoryInternal(descriptor as never),mocks,schedulers,seen};}
async function drive<T>(promise:Promise<T>,mocks:readonly MockSecureTransportControl[],select:(url:string,index:number)=>Uint8Array=bodyFor):Promise<T>{let settled=false;void promise.finally(()=>{settled=true;}).catch(()=>{});const answered=new Set<object>();for(let turn=0;turn<2_000&&!settled;turn++){for(const mock of mocks)for(const request of mock.requests)if(!answered.has(request)){answered.add(request);const payload=select(request.options.url,answered.size-1);request.callbacks.onSecureConnected({address:request.options.pinnedAddress,family:request.options.family,hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onResponse(200,"1.1",["content-length",String(payload.byteLength),"content-type","application/json"]);request.callbacks.onData(payload);request.callbacks.onEnd();}await Promise.resolve();}return promise;}
async function successfulSearch(options:AcademicAcquisitionOptions|undefined=undefined,sink?:ReturnType<typeof createAcquisitionProvenanceSinkInternal>){const deps=dependencies(),client=createAcademicAcquisitionClient(options,deps.factory),cap=sink?createAcademicAcquisitionCallCapabilitiesInternal({provenanceSink:sink}):undefined,promise=client.search({queries:["synthetic"],providers:["crossref"]},cap),result=await drive(promise,deps.mocks);return{client,result,deps};}
const expectCode=async(promise:Promise<unknown>,code:string)=>expect(promise).rejects.toMatchObject({name:"AcademicAcquisitionError",code,message:`Academic acquisition rejected (${code})`});

describe("academic acquisition coordinator outcomes",()=>{
 test("normalizes raw client options exactly once before dependency factory access and passes one identity to every factory",async()=>{const raw={maxResultsPerQuery:2},deps=dependencies(),client=createAcademicAcquisitionClient(raw,deps.factory),normalized=getAcademicAcquisitionClientNormalizedOptionsInternal(client);expect(deps.seen).toHaveLength(6);expect(deps.seen.every(item=>item===normalized)).toBe(true);await client.close();});
 test("makes every dependency factory validate normalized brand hash with no raw option argument",()=>{let calls=0;const deps=dependencies({createCrossref:()=>{calls++;return createCrossrefAdapter();}});expect(()=>deps.factory.createCrossref({...normalizeAcquisitionOptions(undefined)} as never)).toThrowError(expect.objectContaining({code:"acquisition.invalid-capability"}));expect(calls).toBe(0);expect(Object.keys(deps.factory).sort()).toEqual(["capabilityKind","createCrossref","createOpenalex","createPmc","createPubmed","createScheduler","createTransport"].sort());});
 test("allocates no transport adapter scheduler or client state when raw options are unknown invalid getter or proxy",()=>{for(const raw of [{unknown:true},Object.defineProperty({},"maxQueries",{get(){throw new Error("secret");},enumerable:true}),new Proxy({},{ownKeys(){throw new Error("secret");}})]){let traps=0;const factory=new Proxy({},{get(){traps++;throw new Error("dependency secret");}});expect(()=>createAcademicAcquisitionClient(raw as never,factory as never)).toThrowError(expect.objectContaining({code:"acquisition.invalid-options"}));expect(traps).toBe(0);}});
 test("keeps transport planner provider result hash stable after caller mutates raw client options",async()=>{const raw:{maxResultsPerQuery:number}={maxResultsPerQuery:2},deps=dependencies(),client=createAcademicAcquisitionClient(raw,deps.factory),hash=getAcademicAcquisitionClientNormalizedOptionsInternal(client).optionsSha256;raw.maxResultsPerQuery=99;const result=await drive(client.search({queries:[],providers:[]}),deps.mocks);expect([result.optionsSha256,getAcademicAcquisitionClientNormalizedOptionsInternal(client).maxResultsPerQuery]).toEqual([hash,2]);await client.close();});
 test("delegates each raw search fetch call exactly once to Task8 planner then executes its same authenticated plan",async()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source.match(/planAcquisitionInvocation\(/gu)).toHaveLength(2);expect(source).toContain("executeInvocationPlanInternal(plan");const deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory);expect((await drive(client.search({queries:[],providers:[]}),deps.mocks)).partitions.requested).toBe(0);await client.close();});
 test("consumes frozen normalized limits options and partitions without coordinator renormalization revalidation or rebuild",()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source.match(/normalizeAcquisitionOptions\(/gu)).toHaveLength(1);expect(source).toContain("getAcquisitionExecutionPlanSnapshotInternal(plan)");expect(source).not.toContain("createProviderPartitionKey(");});
 test("preserves ordered success drafts when later PubMed ELink outcome is invalid",async()=>{const deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory),promise=client.fetch({identifierKind:"pmid",identifier:"9"}),result=await drive(promise,deps.mocks,(url)=>url.includes("elink.fcgi")?new TextEncoder().encode("{}") : bodyFor(url));expect(result.status).toBe("partial");expect(result.candidates.some(item=>item.identifiers.pmid==="9")).toBe(true);expect(result.failures.some(item=>item.code==="provider.invalid-response")).toBe(true);await client.close();});
 test("constructs candidate document and trace keys only in coordinator after outcomes settle",async()=>{const {client,result}=await successfulSearch();expect(result.candidates[0]?.candidateKey).toMatch(/^candidate-v1-/u);expect(result.traces[0]?.traceKey).toMatch(/^trace-v1-/u);expect(result.provenanceStatus).toBe("uncommitted");await client.close();});
 test("rejects drafts containing coordinator keys hashes provenance or timestamps",()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source).toContain("createAcademicCandidate");expect(source).toContain("createAcademicDocument");expect(source).toContain("createAcquisitionTrace");expect(source).not.toMatch(/draft\.(?:candidateKey|documentKey|traceKey|provenanceStatus)/u);});
 test("records sink veto as blocked failed not dispatched with closed trace",async()=>{let calls=0;const sink=createAcquisitionProvenanceSinkInternal({beforeDispatch:async intent=>{calls++;if(intent.provider==="crossref")throw new Error("veto");return Object.freeze({correlationKey:"ok"});},settled:async()=>{}}),deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory),promise=client.search({queries:["x"],providers:["crossref","openalex"]},createAcademicAcquisitionCallCapabilitiesInternal({provenanceSink:sink})),result=await drive(promise,deps.mocks);expect(result.partitions).toEqual({requested:2,dispatched:1,succeeded:1,failed:1,blocked:1});const blocked=result.traces.find(trace=>trace.settlement.outcome==="blocked")!;expect(blocked.settlement).toMatchObject({code:"sink-blocked",finalUrl:null,redirects:[],encodedBytes:0,decodedBytes:0});expect(calls).toBe(2);await client.close();const timeoutDeps=dependencies(),timeoutClient=createAcademicAcquisitionClient({sinkSettlementTimeoutMs:10},timeoutDeps.factory),timeoutSink=createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>new Promise(()=>{}),settled:async()=>{}}),timed=timeoutClient.search({queries:["x"],providers:["crossref"]},createAcademicAcquisitionCallCapabilitiesInternal({provenanceSink:timeoutSink}));for(let turn=0;turn<20&&timeoutDeps.schedulers[0]!.callbacks.size===0;turn++)await Promise.resolve();timeoutDeps.schedulers[0]!.advance(10);await expectCode(timed,"acquisition.sink-settlement-failure");expect(timeoutDeps.mocks[0]!.requests).toHaveLength(0);await timeoutClient.close();});
 test("keeps all outputs uncommitted when observation sink succeeds fails blocks or is absent",async()=>{for(const mode of ["absent","success","settled-fail"] as const){const sink=mode==="absent"?undefined:createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>Object.freeze({correlationKey:mode}),settled:async()=>{if(mode==="settled-fail")throw new Error("sink");}}),{client,result}=await successfulSearch(undefined,sink);expect(result.provenanceStatus).toBe("uncommitted");expect(result.candidates.every(item=>item.provenanceStatus==="uncommitted")&&result.traces.every(item=>item.provenanceStatus==="uncommitted")).toBe(true);await client.close();}});
 test("preserves parsed candidates documents traces when settled sink observation fails",async()=>{const sink=createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>Object.freeze({correlationKey:"x"}),settled:async()=>{throw new Error("settled");}}),{client,result}=await successfulSearch(undefined,sink);expect([result.status,result.partitions.succeeded,result.candidates.length,result.traces.length]).toEqual(["partial",1,1,1]);expect(result.failures).toContainEqual(expect.objectContaining({code:"sink.failed"}));await client.close();});
 test("never exposes sink callback path that sets provenance admits evidence or constructs RequestRecord",()=>{const sink=createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>Object.freeze({correlationKey:"x"}),settled:async()=>{}});expect(Object.keys(sink)).toEqual(["capabilityKind"]);const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source).not.toMatch(/RequestRecord|admitEvidence|setProvenance|provenanceStatus\s*=/u);});
 test("rejects plain forged sink and every staged candidate document trace result object",async()=>{await expect(acquisitionSinkBeforeDispatchInternal(Object.freeze({capabilityKind:"acquisition-provenance-sink"}) as never,Object.freeze({}) as never,new AbortController().signal)).rejects.toMatchObject({code:"acquisition.invalid-capability"});expect(()=>createAcademicAcquisitionCallCapabilitiesInternal({provenanceSink:Object.freeze({capabilityKind:"acquisition-provenance-sink"}) as never})).toThrowError(expect.objectContaining({code:"acquisition.invalid-capability"}));});
 test("counts requested dispatched succeeded failed blocked with exact invariants",async()=>{const {client,result}=await successfulSearch();const p=result.partitions;expect(p.requested).toBe(p.dispatched+p.blocked);expect(p.dispatched).toBe(p.succeeded+p.failed-p.blocked);expect(p.blocked).toBeLessThanOrEqual(p.failed);expect(()=>validateAcademicAcquisitionResult(result)).not.toThrow();await client.close();});
 test("materializes ESummary ELink PMC reservations then calls executeMaterialized once per authentic partition",async()=>{const deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory),result=await drive(client.fetch({identifierKind:"pmid",identifier:"9"}),deps.mocks);expect(result.partitions.requested).toBe(3);expect(deps.mocks[0]!.requests.map(item=>item.options.url)).toEqual(expect.arrayContaining([expect.stringContaining("esummary.fcgi"),expect.stringContaining("elink.fcgi"),expect.stringContaining("BioC_json")]));expect(result.documents.length).toBeGreaterThan(0);await client.close();});
 test("rejects forged fixture and foreign-plan materialized partitions before adapter execution",()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8"),assertion=source.indexOf("assertMaterializedProviderPartitionInternal"),execution=source.indexOf("executeMaterialized",assertion);expect(assertion).toBeGreaterThanOrEqual(0);expect(execution).toBeGreaterThan(assertion);});
 test("skips empty failed blocked parents without executeMaterialized",async()=>{const empty=new TextEncoder().encode('{"header":{"type":"eutils","version":"0.3"},"esearchresult":{"count":"0","retmax":"0","retstart":"0","idlist":[]}}'),deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory),result=await drive(client.search({queries:["none"],providers:["pubmed"]}),deps.mocks,()=>empty);expect(result.partitions).toEqual({requested:1,dispatched:1,succeeded:1,failed:0,blocked:0});expect(deps.mocks[0]!.requests).toHaveLength(1);await client.close();});
 test("aborts internal-contract on foreign replayed or double-materialized reservation",()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source).toContain("materializeReservation(reservation,facts)");expect(source).not.toContain("currentState()");});
 test("maps synchronous dispatch throw to internal contract with planned requested returned-owner dispatched and exact cleanup counts",async()=>{const deps=dependencies({createTransport:(options:any)=>{const mock=createMockSecureTransportCapabilities(),node=createNodeRuntimeCapabilitiesInternal(mock.ops),transport=createSecureJsonTransport(options,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_e,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node)));void transport.close();return transport;}}),client=createAcademicAcquisitionClient(undefined,deps.factory);await expectCode(client.search({queries:["x"],providers:["crossref"]}),"acquisition.internal-contract");await client.close();});
 test("injects fake scheduler races hanging secure close then force destroys only owned request and quarantines late completion",()=>{const source=fs.readFileSync(path.join(import.meta.dirname,"../../src/acquisition/coordinator.ts"),"utf8");expect(source).toContain("openSecureTransportRequestInternal");expect(source).toContain("handle.forceClose()");expect(source).not.toMatch(/transport\.close\(\).*force/u);});
 test("retains bounded cleanup diagnostics without replacing redacted primary error",async()=>{const deps=dependencies({createTransport:()=>{throw new Error("path secret");}});expect(()=>createAcademicAcquisitionClient(undefined,deps.factory)).toThrowError(expect.objectContaining({code:"acquisition.invalid-capability",message:"Academic acquisition rejected (acquisition.invalid-capability)"}));});
 test("applies security then sink then provider fatal precedence and partial success rules",async()=>{const veto=createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>{throw new Error("veto");},settled:async()=>{}}),deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory);await expectCode(client.search({queries:["x"],providers:["crossref"]},createAcademicAcquisitionCallCapabilitiesInternal({provenanceSink:veto})),"acquisition.sink-settlement-failure");await client.close();const partial=await successfulSearch(undefined,createAcquisitionProvenanceSinkInternal({beforeDispatch:async()=>Object.freeze({correlationKey:"x"}),settled:async()=>{throw new Error("x");}}));expect(partial.result.status).toBe("partial");await partial.client.close();});
 test("groups compatible strong IDs and URLs while preserving ambiguity deterministically",async()=>{const deps=dependencies(),client=createAcademicAcquisitionClient(undefined,deps.factory),bridged=new TextEncoder().encode(new TextDecoder().decode(bodies.openalex).replace("https://example.org/openalex/2","https://example.org/crossref/1")),result=await drive(client.search({queries:["x"],providers:["crossref","openalex"]}),deps.mocks,url=>url.includes("openalex")?bridged:bodyFor(url));expect(result.candidates).toHaveLength(2);expect(result.candidateGroups).toHaveLength(1);expect(result.candidateGroups[0]).toMatchObject({identityKind:"canonical-url",status:"ambiguous",candidateKeys:result.candidates.map(item=>item.candidateKey).sort()});expect(()=>validateAcademicAcquisitionResult(result)).not.toThrow();await client.close();});
 test("returns fresh immutable uncommitted public results independent of completion order",async()=>{const first=await successfulSearch(),second=await successfulSearch();expect(first.result).not.toBe(second.result);expect(first.result).toEqual(second.result);expect(Object.isFrozen(first.result)&&Object.isFrozen(first.result.candidates)&&Object.isFrozen(first.result.candidates[0])).toBe(true);await first.client.close();await second.client.close();});
});
