import {describe,expect,test,vi} from "vitest";

import {createContentDecodeCapabilitiesInternal} from "../../src/acquisition/content-decoding-internal.js";
import {createCrossrefAdapter} from "../../src/acquisition/providers/crossref.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {ProviderAdapterError,createProviderExecutionResultInternal,createProviderPartitionExecutor,getProviderExecutionResultInternal,providerEndpointResultCap} from "../../src/acquisition/providers/shared.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import {createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createProviderRequestPartitionFixtureInternal,normalizeAcquisitionOptions,type ProviderRequestPartitionInternal,type ProviderRequestPartitionSnapshotInternal,type TransportSettlement} from "../../src/acquisition/contracts.js";
import {createMockSecureTransportCapabilities} from "../helpers/mock-secure-transport.js";

const normalized=normalizeAcquisitionOptions(undefined);const options=normalized.providers;
const registryOptions={maxPartitions:normalized.maxPartitions,maxCanonicalUrlBytes:normalized.transport.maxCanonicalUrlBytes,maxStructureDepth:normalized.maxStructureDepth,maxStructureNodes:normalized.maxStructureNodes,maxStructureKeys:normalized.maxStructureKeys,maxStringCanonicalBytes:normalized.maxStringCanonicalBytes,maxScalarCanonicalBytes:normalized.maxScalarCanonicalBytes};
function partition(snapshot:ProviderRequestPartitionSnapshotInternal):ProviderRequestPartitionInternal{return createProviderRequestPartitionFixtureInternal({partition:snapshot,options:registryOptions});}
async function settlement(snapshot:ProviderRequestPartitionSnapshotInternal,payload:string,status=200):Promise<TransportSettlement>{const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const transport=createSecureJsonTransport(normalized,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node)));const completion=transport.request({partitionKey:snapshot.partitionKey,partitionKeySha256:snapshot.partitionKeySha256,provider:snapshot.provider,operation:snapshot.operation,endpointClass:snapshot.endpointClass,target:snapshot.target,url:snapshot.url});for(let count=0;count<100&&mock.requests.length===0;count+=1)await Promise.resolve();const request=mock.requests[0]!;request.callbacks.onSecureConnected({address:request.options.pinnedAddress,family:request.options.family,hostnameVerified:true,authorized:true,authorizationError:null});const bytes=new TextEncoder().encode(payload);request.callbacks.onResponse(status,"1.1",["content-length",String(bytes.byteLength)]);request.callbacks.onData(bytes);request.callbacks.onEnd();const output=await completion;await transport.close();return output;}
async function run(payload:unknown,input:{query:string;limit:number}={query:"synthetic",limit:10}){const adapter=createCrossrefAdapter();const snapshot=adapter.buildSearchPartition(input);const opaque=partition(snapshot);const wire=await settlement(snapshot,JSON.stringify(payload));const executor=createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})});return adapter.search(opaque,options,executor);}
function errorCode(action:()=>unknown):string|undefined{try{action();}catch(error){expect(error).toBeInstanceOf(ProviderAdapterError);return(error as ProviderAdapterError).code;}return undefined;}
const minimal={status:"ok",message:{items:[{DOI:"10.5555/synthetic.1",title:["Synthetic"],author:[],"container-title":[],published:{"date-parts":[[2024]]},type:"journal-article"}]}};

describe("Crossref metadata adapter",()=>{
 test("exposes fixed Crossref 1000 OpenAlex 200 search and fetch 1 endpoint caps",()=>{expect([providerEndpointResultCap("crossref","search"),providerEndpointResultCap("crossref","fetch"),providerEndpointResultCap("openalex","search"),providerEndpointResultCap("openalex","fetch")]).toEqual([1000,1,200,1]);});
 test("builds exact RFC3986 ordered Crossref paths parameters and select list",()=>{const adapter=createCrossrefAdapter();expect(adapter.buildSearchPartition({query:"space / café",limit:7}).url).toBe("https://api.crossref.org/works?query.bibliographic=space%20%2F%20caf%C3%A9&rows=7&select=DOI%2CURL%2Ctitle%2Cauthor%2Ccontainer-title%2Cpublisher%2Cpublished-print%2Cpublished-online%2Cpublished%2Ctype%2Csubtype");expect(adapter.buildFetchPartition({identifierKind:"doi",identifier:"https://doi.org/10.5555/ABC"}).url).toBe("https://api.crossref.org/works/10.5555%2Fabc");});
 test("parses dense bounded Crossref title arrays and selects first nonempty provider-order string",async()=>{const result=await run({...minimal,message:{items:[{...minimal.message.items[0],title:["","First","Second"],"container-title":["","Venue"]}]}});expect(result.outcomes[0]!.status).toBe("success");if(result.outcomes[0]!.status==="success")expect([result.outcomes[0]!.candidateDrafts[0]!.title,result.outcomes[0]!.candidateDrafts[0]!.containerTitle]).toEqual(["First","Venue"]);});
 test("rejects sparse or non-string Crossref title and container-title elements",async()=>{for(const field of ["title","container-title"] as const){const values:string[]=["ok"];delete values[0];const bad={...minimal,message:{items:[{...minimal.message.items[0],[field]:values}]}};expect((await run(bad)).outcomes[0]!.code).toBe("provider.invalid-response");expect((await run({...minimal,message:{items:[{...minimal.message.items[0],[field]:[{}]}]}})).outcomes[0]!.code).toBe("provider.invalid-response");}});
 test("normalizes 0000-0002-1825-0097 and 0000-0002-1694-233X preserving all 16 characters",async()=>{const result=await run({...minimal,message:{items:[{...minimal.message.items[0],author:[{family:"One",ORCID:"0000-0002-1825-0097"},{name:"Two",ORCID:"https://orcid.org/0000-0002-1694-233X"},{name:"Bad",ORCID:"0000-0000-0000-0000"}]}]}});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");expect(result.outcomes[0]!.candidateDrafts[0]!.authors.map((author)=>author.orcid)).toEqual(["https://orcid.org/0000-0002-1825-0097","https://orcid.org/0000-0002-1694-233X",null]);});
 test("omits invalid URLs and identifiers with typed value-free warnings but rejects wrong shapes",async()=>{const invalid=await run({...minimal,message:{items:[{...minimal.message.items[0],DOI:"not a doi",URL:"javascript:secret"}]}});if(invalid.outcomes[0]!.status!=="success")throw new Error("success expected");expect(invalid.outcomes[0]!.warnings).toEqual([{code:"provider.invalid-url-omitted",recordOrdinal:0,field:"URL"},{code:"provider.invalid-identifier-omitted",recordOrdinal:0,field:"doi"}]);expect(JSON.stringify(invalid.outcomes[0]!.warnings)).not.toContain("javascript");expect((await run({...minimal,message:{items:[{...minimal.message.items[0],URL:{}}]}})).outcomes[0]!.code).toBe("provider.invalid-response");});
 test("rejects fetch identifier mismatch and malformed provider envelopes",async()=>{const adapter=createCrossrefAdapter();const snapshot=adapter.buildFetchPartition({identifierKind:"doi",identifier:"10.5555/wanted"});const opaque=partition(snapshot);for(const payload of [{status:"bad",message:{}},{status:"ok",message:{DOI:"10.5555/other"}}]){const wire=await settlement(snapshot,JSON.stringify(payload));const result=await adapter.fetch(opaque,options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));expect(result.outcomes[0]!.code).toBe("provider.invalid-response");}});
 test("bounds provider records bytes authors and structure before sorting",async()=>{expect((await run({status:"ok",message:{items:Array.from({length:101},()=>minimal.message.items[0])}})).outcomes[0]!.code).toBe("provider.invalid-response");const tiny={...options,maxProviderRecordCanonicalBytes:10,maxConditionalFactCanonicalBytes:10};const adapter=createCrossrefAdapter();const snapshot=adapter.buildSearchPartition({query:"x",limit:1});const wire=await settlement(snapshot,JSON.stringify(minimal));const result=await adapter.search(partition(snapshot),tiny,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));expect(result.outcomes[0]!.code).toBe("provider.invalid-response");});
 test("uses response ordinal only when a stable provider ID is absent",async()=>{const result=await run({status:"ok",message:{items:[{title:["No DOI"],author:[],"container-title":[],type:"other"}]}});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");expect([result.outcomes[0]!.candidateDrafts[0]!.providerRecordId,result.outcomes[0]!.candidateDrafts[0]!.providerOrdinal]).toEqual([null,0]);});
 test("brands executor capabilities accepts undefined signal and validates genuine signal when present",async()=>{const adapter=createCrossrefAdapter();const snapshot=adapter.buildSearchPartition({query:"x",limit:1});const wire=await settlement(snapshot,JSON.stringify(minimal));let calls=0;const executor=createProviderPartitionExecutor({execute:async(_partition,signal)=>{calls+=1;expect(signal).toBeUndefined();return{status:"settled",settlement:wire};}});await adapter.search(partition(snapshot),options,executor);expect(calls).toBe(1);await expect(adapter.search(partition(snapshot),options,{} as never)).rejects.toMatchObject({code:"provider.invalid-capability"});await expect(adapter.search(partition(snapshot),options,executor,{} as never)).rejects.toMatchObject({code:"provider.invalid-capability"});});
 test("uses only bounded predecessor fixture partitions and rejects forged or foreign-owner partitions",async()=>{const adapter=createCrossrefAdapter();const snapshot=adapter.buildSearchPartition({query:"x",limit:1});const wire=await settlement(snapshot,JSON.stringify(minimal));const executor=createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})});await expect(adapter.search(Object.freeze({capabilityKind:"provider-request-partition"}) as never,options,executor)).rejects.toMatchObject({code:"provider.invalid-capability"});const foreign=createOpenAlexAdapter().buildSearchPartition({query:"x",limit:1});await expect(adapter.search(partition(foreign),options,executor)).rejects.toMatchObject({code:"provider.invalid-input"});});
 test("returns one ordered bounded outcome per physical metadata partition with exact empty conditional facts",async()=>{const result=await run(minimal);expect([result.schemaVersion,result.outcomes.length,result.outcomes[0]!.outcomeOrdinal,result.conditionalFacts]).toEqual([1,1,0,[]]);});
 test("accepts only closed execution-result input outcomes conditionalFacts options",async()=>{const result=await run(minimal);expect(errorCode(()=>createProviderExecutionResultInternal({...{outcomes:result.outcomes,conditionalFacts:[],options},extra:true} as never))).toBe("provider.invalid-input");});
 test("atomically registers frozen provider results and rejects forged clone mutated hash count proxy and duplicate-registry keys",async()=>{const result=await run(minimal);expect(Object.isFrozen(result)&&Object.isFrozen(result.outcomes)).toBe(true);for(const value of [{...result},{...result,contentSha256:"0".repeat(64)},new Proxy(result,{})])expect(errorCode(()=>getProviderExecutionResultInternal(value))).toBe("provider-result-invalid");const duplicate=await vi.importActual<typeof import("../../src/acquisition/providers/shared.js")>("../../src/acquisition/providers/shared.js?duplicate-registry");expect(()=>duplicate.getProviderExecutionResultInternal(result)).toThrowError(/provider-result-invalid/u);});
 test("returns one frozen O1 provider-result view repeatedly without rehash iteration or parse",async()=>{const result=await run(minimal);const parse=vi.spyOn(JSON,"parse");const first=getProviderExecutionResultInternal(result);expect(getProviderExecutionResultInternal(result)).toBe(first);expect(Object.isFrozen(first)).toBe(true);expect(parse).not.toHaveBeenCalled();parse.mockRestore();});
 test("shares one registry across provider modules while exposing no root result getter",async()=>{const result=await run(minimal);expect(getProviderExecutionResultInternal(result).result).toBe(result);expect(Object.keys(await import("../../src/index.js"))).not.toContain("getProviderExecutionResultInternal");});
 test("keeps provider drafts free of coordinator keys hashes provenance and timestamps",async()=>{const result=await run(minimal);if(result.outcomes[0]!.status!=="success")throw new Error("success expected");const text=JSON.stringify(result.outcomes[0]!.candidateDrafts);for(const forbidden of ["candidateKey","documentKey","traceKey","partitionKey","payloadSha","provenance","timestamp","status"])expect(text).not.toContain(forbidden);});
 test("reports exact redacted ProviderAdapterError and ProviderOutcome codes",async()=>{expect(new ProviderAdapterError("provider.invalid-input")).toMatchObject({message:"Provider adapter rejected (provider.invalid-input)",code:"provider.invalid-input"});const adapter=createCrossrefAdapter();const snapshot=adapter.buildSearchPartition({query:"x",limit:1});const wire=await settlement(snapshot,"{}",503);const result=await adapter.search(partition(snapshot),options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));expect(result.outcomes[0]!.code).toBe("provider.availability");});
});
