import {describe,expect,test,vi} from "vitest";

import {normalizeAcquisitionOptions,type AcademicNcbiProviderOptions} from "../../src/acquisition/contracts.js";
import {createContentDecodeCapabilitiesInternal} from "../../src/acquisition/content-decoding-internal.js";
import {createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal,createRequestDeadlineInternal,createRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import type {SecureTransportRequest} from "../../src/acquisition/transport.js";
import {createMockSecureTransportCapabilities} from "../helpers/mock-secure-transport.js";
import {ProviderJsonScanError,getProviderJsonSettlementInternal,scanAndParseProviderJsonInternal,snapshotProviderJsonInternal} from "../../src/acquisition/json-wire-scanner-internal.js";

function deadline(){return createRequestDeadlineInternal(10_000,createRequestDeadlineSchedulerCapabilitiesInternal({monotonicNow:()=>1,setTimeout:()=>1,clearTimeout:()=>undefined}));}
const HASH="b".repeat(64);const request:SecureTransportRequest={partitionKey:`partition-v1-${HASH}`,partitionKeySha256:HASH,provider:"crossref",operation:"search",endpointClass:"crossref-search",target:"crossref",url:"https://api.crossref.org/works?query=x"};
async function secureSettlement(payload:string,providers:AcademicNcbiProviderOptions={}){const options=normalizeAcquisitionOptions({providers});const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const pinned=createPinnedHopRuntimeInternal(undefined,node);const scheduler=createNodeRequestDeadlineSchedulerCapabilitiesInternal(node);const decoder=createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)});const capabilities=createSecureTransportCapabilitiesInternal(pinned,decoder,scheduler);const transport=createSecureJsonTransport(options,capabilities);const completion=transport.request(request);for(let count=0;count<100&&mock.requests.length===0;count+=1)await Promise.resolve();const record=mock.requests[0]!;record.callbacks.onSecureConnected({address:record.options.pinnedAddress,family:record.options.family,hostnameVerified:true,authorized:true,authorizationError:null});const bytes=new TextEncoder().encode(payload);record.callbacks.onResponse(200,"1.1",["content-length",String(bytes.byteLength)]);record.callbacks.onData(bytes);record.callbacks.onEnd();const settlement=await completion;await transport.close();if(settlement.outcome!=="success")throw new Error("expected success");return settlement;}
function code(action:()=>unknown):string|undefined{try{action();}catch(error){expect(error).toBeInstanceOf(ProviderJsonScanError);return(error as ProviderJsonScanError).code;}return undefined;}

 describe("duplicate-safe provider JSON wire scanner",()=>{
  test("scans JSON nonrecursively before parse with exact syntax escape surrogate number grammar",()=>{const valid=["{}","[]",`{"s":"x\\n\\uD834\\uDD1E","n":-1.25e+2,"v":[true,false,null]}`];for(const payload of valid){const value=scanAndParseProviderJsonInternal(payload,undefined,deadline());expect(snapshotProviderJsonInternal(value)).toEqual(JSON.parse(payload));}const invalid:readonly [string,string][]=[[`{"x":01}`,"json.invalid-number"],[`{"x":1.}`,"json.invalid-number"],[`{"x":+1}`,"json.invalid-syntax"],[`{"x":NaN}`,"json.invalid-syntax"],[`{"x":"\\x00"}`,"json.invalid-escape"],[`{"x":"\\uD800"}`,"json.invalid-surrogate"],[`{"x":"\\uDC00"}`,"json.invalid-surrogate"],[`{"x":"a
b"}`,"json.invalid-syntax"],[`{"x":true}x`,"json.invalid-syntax"],[`{"x":}`,"json.invalid-syntax"]];for(const [payload,expected] of invalid){const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal(payload,undefined,deadline())),payload).toBe(expected);expect(parse).not.toHaveBeenCalled();parse.mockRestore();}});

  test("rejects decoded duplicate keys including alternate escape spellings before JSON parse",()=>{const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal(`{"a":1,"\\u0061":2}`,undefined,deadline()))).toBe("json.duplicate-key");expect(parse).not.toHaveBeenCalled();parse.mockRestore();});

  test("lexically validates then rejects primitive boolean number string null roots before JSON parse",()=>{for(const payload of ["true","false","null","1","-2.5e3",`"value"`]){const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal(payload,undefined,deadline())),payload).toBe("transport.json-root-invalid");expect(parse).not.toHaveBeenCalled();parse.mockRestore();}const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal("tru",undefined,deadline()))).toBe("json.invalid-syntax");expect(parse).not.toHaveBeenCalled();parse.mockRestore();});

  test("deep-freezes every parsed object array node brands exact root and rejects spread structured JSON clones",()=>{const value=scanAndParseProviderJsonInternal(`{"a":[{"b":1}]}`,undefined,deadline());const snapshot=snapshotProviderJsonInternal(value);expect(Object.isFrozen(snapshot)&&Object.isFrozen((snapshot as {a:unknown[]}).a)&&Object.isFrozen((snapshot as {a:{b:number}[]}).a[0])).toBe(true);expect(code(()=>snapshotProviderJsonInternal({...snapshot} as never))).toBe("json.snapshot-mismatch");});

  test("registers parsed-or-error settlement sidecar once and future adapters use lookup only",async()=>{const parse=vi.spyOn(JSON,"parse");const valid=await secureSettlement(`{"ok":true}`);const lookup=getProviderJsonSettlementInternal(valid);expect(snapshotProviderJsonInternal(lookup.value!)).toEqual({ok:true});expect(Object.isFrozen(lookup)).toBe(true);expect(getProviderJsonSettlementInternal(valid)).toBe(lookup);expect(parse.mock.calls.filter(([text])=>text===`{"ok":true}`)).toHaveLength(1);for(const [payload,expected,providers] of [[`{"a":1,"\\u0061":2}`,"json.duplicate-key",{}],[`true`,"transport.json-root-invalid",{}],[`{"a":{"b":1}}`,"json.depth-exceeded",{maxStructureDepth:1}],[`{"a":123}`,"json.object-too-large",{maxObjectWireBytes:5}]] as const){const settlement=await secureSettlement(payload,providers);const errorLookup=getProviderJsonSettlementInternal(settlement);expect(errorLookup.errorCode).toBe(expected);expect(getProviderJsonSettlementInternal(settlement)).toBe(errorLookup);}expect(parse.mock.calls.filter(([text])=>typeof text==="string"&&([`{"a":1,"\\u0061":2}`,`true`,`{"a":{"b":1}}`,`{"a":123}`] as string[]).includes(text))).toHaveLength(0);for(const forged of [Object.freeze({...valid}),Object.freeze({outcome:"success",payloadUtf8:"{}"})])expect(code(()=>getProviderJsonSettlementInternal(forged as never))).toBe("json.snapshot-mismatch");const transportExports=Object.keys(await import("../../src/acquisition/transport.js"));expect(transportExports.some((name)=>/finalize|candidate|register/iu.test(name))).toBe(false);expect(parse.mock.calls.filter(([text])=>text===`{"ok":true}`)).toHaveLength(1);parse.mockRestore();});

  test("bounds JSON depth nodes keys object wire scalar aggregate before allocation",()=>{const cases:readonly [string,object,string][]=[[`{"a":{"b":1}}`,{maxDepth:1},"json.depth-exceeded"],[`[1,2]`,{maxNodes:2},"json.nodes-exceeded"],[`{"a":1,"b":2}`,{maxKeys:1},"json.keys-exceeded"],[`{"a":123}`,{maxObjectWireBytes:5},"json.object-too-large"],[`{"abcdef":1}`,{maxScalarCanonicalBytes:5},"json.scalar-too-large"],[`{"a":"xx","b":"yy"}`,{maxAggregateScalarBytes:8},"json.aggregate-scalars-too-large"]];for(const [payload,options,expected] of cases){const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal(payload,options,deadline())),payload).toBe(expected);expect(parse).not.toHaveBeenCalled();parse.mockRestore();}for(const [payload,bytes] of [[`{"é":1}`,8],[`{"\\u00e9":1}`,12],[`{"😀":1}`,10],[`{"\\uD83D\\uDE00":1}`,18],[`{"é":{"x":1}}`,14]] as const){expect(()=>scanAndParseProviderJsonInternal(payload,{maxObjectWireBytes:bytes},deadline()),payload).not.toThrow();const parse=vi.spyOn(JSON,"parse");expect(code(()=>scanAndParseProviderJsonInternal(payload,{maxObjectWireBytes:bytes-1},deadline())),payload).toBe("json.object-too-large");expect(parse).not.toHaveBeenCalled();parse.mockRestore();}for(const payload of [`{"x":1éé}`,`{"x":1😀}`,`{"x":1\u000b23}`]){const slice=vi.spyOn(String.prototype,"slice");expect(code(()=>scanAndParseProviderJsonInternal(payload,{maxScalarCanonicalBytes:3},deadline())),payload).toBe("json.scalar-too-large");expect(slice).not.toHaveBeenCalled();slice.mockRestore();}const boundedSlice=vi.spyOn(String.prototype,"slice");expect(code(()=>scanAndParseProviderJsonInternal(`{"x":1é}`,{maxScalarCanonicalBytes:3},deadline()))).toBe("json.invalid-number");expect(boundedSlice).toHaveBeenCalledTimes(1);boundedSlice.mockRestore();expect(()=>scanAndParseProviderJsonInternal(`{"x":123}`,{maxScalarCanonicalBytes:3},deadline())).not.toThrow();});

  test("brands scanner-produced JSON and rejects plain parsed values and digest mismatch",()=>{expect(code(()=>snapshotProviderJsonInternal(JSON.parse("{}") as never))).toBe("json.snapshot-mismatch");const parse=vi.spyOn(JSON,"parse").mockReturnValue({different:true});expect(code(()=>scanAndParseProviderJsonInternal(`{"expected":true}`,undefined,deadline()))).toBe("json.snapshot-mismatch");expect(parse).toHaveBeenCalledTimes(1);parse.mockRestore();});
 });
