import { describe, expect, test, vi } from "vitest";

import { canonicalJson } from "../../src/crypto/canonical-json.js";
import { sha256Hex } from "../../src/crypto/hash.js";
import { NetworkPolicyError } from "../../src/acquisition/network-policy.js";
import {
  PinnedHopRuntimeErrorInternal, SecureTransportError,
  createNodeDnsResolver, createNodeRuntimeCapabilitiesInternal, createPinnedHopRuntimeInternal,
  type NodePinnedHopCallbacksInternal, type NodeOperationsInternal, type NodePinnedHopHandleInternal,
} from "../../src/acquisition/node-pinned-hop-internal.js";
import {
  RequestDeadlineErrorInternal, claimRequestDeadlineInternal, createNodeRequestDeadlineSchedulerCapabilitiesInternal,
  createRequestDeadlineInternal,
} from "../../src/acquisition/request-deadline-internal.js";
import { createMockSecureTransportCapabilities } from "../helpers/mock-secure-transport.js";

function callbacks():NodePinnedHopCallbacksInternal { return {onSecureConnected:vi.fn(),onProtocolFailure:vi.fn(),onResponse:vi.fn(),onData:vi.fn(()=>"continue" as const),onEnd:vi.fn(),onError:vi.fn()}; }
function setup(){const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const scheduler=createNodeRequestDeadlineSchedulerCapabilitiesInternal(node);const deadline=createRequestDeadlineInternal(1_000,scheduler);claimRequestDeadlineInternal(deadline,"transport-request-v1-owner");const runtime=createPinnedHopRuntimeInternal(undefined,node);return{mock,node,scheduler,deadline,runtime};}
async function targetOf(value=setup()){return value.runtime.resolveProviderTarget("https://api.crossref.org/works",value.deadline);}
function runtimeCode(action:()=>unknown):string|undefined {try{action();}catch(error){expect(error).toBeInstanceOf(PinnedHopRuntimeErrorInternal);return(error as PinnedHopRuntimeErrorInternal).code;}return undefined;}

describe("authenticated pinned Node hops",()=>{
  test("races hung DNS against fake clock deadline cancels resolver and ignores late answers",async()=>{
    const value=setup();let lateResolve:((answers:readonly string[])=>void)|undefined;value.mock.resolve4=()=>new Promise((resolve)=>{lateResolve=resolve;});value.mock.resolve6=()=>new Promise(()=>undefined);
    const pending=value.runtime.resolveProviderTarget("https://api.crossref.org/works",value.deadline);value.mock.now=1_101;for(const timer of [...value.mock.timers.values()])timer();await expect(pending).rejects.toMatchObject({code:"request-deadline.expired"});expect(value.mock.resolvers[0]?.cancelCount).toBe(1);expect(value.mock.resolvers[0]?.destroyCount).toBe(1);lateResolve?.(["8.8.8.8"]);await Promise.resolve();
  });

  test("same runtime resolves all answers hashes deterministic pin then opens only chosen peer",async()=>{
    const value=setup();value.mock.resolve4=async()=>["8.8.8.8","1.1.1.1"];value.mock.resolve6=async()=>["2606:4700:4700::1111"];
    const target=await targetOf(value);expect(target.address).toBe("1.1.1.1");expect(target.allAddressesSha256).toBe(sha256Hex(canonicalJson({schemaVersion:1,addresses:[{address:"1.1.1.1",family:4},{address:"8.8.8.8",family:4},{address:"2606:4700:4700::1111",family:6}]})));
    const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:1024,connectTimeoutMs:100},cb,value.deadline);expect(value.mock.requests).toHaveLength(1);const request=value.mock.requests[0]!;expect(request.options.pinnedAddress).toBe("1.1.1.1");request.callbacks.onSecureConnected({address:"1.1.1.1",family:"IPv4",hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onEnd();await expect(handle.completion).resolves.toMatchObject({outcome:"ended",peer:{address:"1.1.1.1",family:4}});
  });

  test("rejects forged cross-runtime replayed stale and URL-host-mismatched pins before request allocation",async()=>{
    const first=setup();const second=setup();const target=await targetOf(first);const cb=callbacks();expect(runtimeCode(()=>second.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.invalid-capability");
    expect(runtimeCode(()=>first.runtime.openPinnedHop({...target} as never,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.invalid-capability");expect(first.mock.requests).toHaveLength(0);
    expect(runtimeCode(()=>first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:"https://api.crossref.org/other",headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.target-mismatch");expect(first.mock.requests).toHaveLength(0);
    const stale=setup();const staleTarget=await targetOf(stale);await stale.runtime.close();expect(runtimeCode(()=>stale.runtime.openPinnedHop(staleTarget,{ownerId:"hop-owner-v1-stale",url:staleTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,stale.deadline))).toBe("pinned-runtime.pin-stale");
    const handle=first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline);expect(runtimeCode(()=>first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-y",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.pin-replayed");handle.forceClose();await handle.close();
  });

  test("creates a fresh branded pin for every redirect and exposes no caller pinnedAddress input",async()=>{const value=setup();const a=await targetOf(value);const b=await value.runtime.resolveProviderTarget("https://api.crossref.org/next",value.deadline);expect(a).not.toBe(b);expect(Object.keys(a)).not.toContain("deadline");expect(runtimeCode(()=>value.runtime.openPinnedHop(a,{ownerId:"hop-owner-v1-a",url:a.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100,pinnedAddress:"9.9.9.9"} as never,callbacks(),value.deadline))).toBe("pinned-runtime.invalid-input");});

  test("pins DNS lookup once and verifies original Host SNI certificate and peer before bytes",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;expect(request.options.hostHeader).toBe("api.crossref.org");expect(request.options.servername).toBe("api.crossref.org");expect(request.options.checkServerIdentity("api.crossref.org",{})).toBeUndefined();expect(cb.onResponse).not.toHaveBeenCalled();request.callbacks.onSecureConnected({address:target.address,family:target.family,hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onData(new Uint8Array([1]));expect(cb.onData).toHaveBeenCalledOnce();handle.forceClose();});

  test("sets bundled CA rejectUnauthorized maxHeaderSize strict parser and duplicate policy",async()=>{const value=setup();const target=await targetOf(value);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:1234,connectTimeoutMs:100},callbacks(),value.deadline);const options=value.mock.requests[0]!.options;expect(options.ca).toBe(value.mock.ops.bundledRootCertificates);expect(options.ca).toEqual(["TEST ROOT A","TEST ROOT B"]);expect(Object.isFrozen(options.ca)).toBe(true);expect(options).toMatchObject({rejectUnauthorized:true,maxHeaderSize:1234,insecureHTTPParser:false,joinDuplicateHeaders:false});handle.forceClose();});

  test("maps pre-response llhttp failures to typed protocol callbacks before socket errors",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;request.callbacks.onProtocolFailure("invalid-header-token");request.callbacks.onError("socket");expect(cb.onProtocolFailure).toHaveBeenCalledWith("invalid-header-token");await expect(handle.completion).resolves.toMatchObject({outcome:"failed",failureCode:"hop.protocol-failed"});});

  test("destroys request socket agent timers and listeners on abort timeout error and late events",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},cb,value.deadline);value.mock.now+=11;[...value.mock.timers.values()].at(-1)!();await expect(handle.completion).resolves.toMatchObject({failureCode:"hop.connect-timeout"});expect(value.mock.requests[0]!.counts.destroy).toBe(1);expect(value.mock.agents[0]!.destroyCount).toBe(1);value.mock.requests[0]!.callbacks.onEnd();expect(cb.onEnd).not.toHaveBeenCalled();});

  test("force closes hanging hop synchronously through request socket destroy and quarantines every late callback byte",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;handle.forceClose();handle.forceClose();expect(request.counts.destroy).toBe(1);request.callbacks.onSecureConnected({address:target.address,family:4,hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onData(new Uint8Array([1,2,3]));request.callbacks.onEnd();expect(cb.onData).not.toHaveBeenCalled();await expect(handle.completion).resolves.toMatchObject({outcome:"cancelled"});});

  test("uses request-owned nonpooling HTTPS and HTTP agents and never globals",async()=>{const value=setup();const target=await targetOf(value);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);expect(value.mock.agents[0]!.agent).toMatchObject({protocol:"https:",keepAlive:false,maxSockets:1,maxFreeSockets:0});expect(value.mock.ops.createRequestOwnedAgent("http:")).toMatchObject({protocol:"http:",keepAlive:false,maxSockets:1,maxFreeSockets:0});handle.forceClose();});

  test("accepts concurrent hops without cross-cancellation or resolver reuse",async()=>{const value=setup();const a=await targetOf(value);const b=await value.runtime.resolveProviderTarget("https://api.crossref.org/next",value.deadline);const first=value.runtime.openPinnedHop(a,{ownerId:"hop-owner-v1-a",url:a.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);const second=value.runtime.openPinnedHop(b,{ownerId:"hop-owner-v1-b",url:b.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);first.abort();first.abort();void first.close();first.forceClose();expect(value.mock.requests[0]!.counts.abort).toBe(0);expect(value.mock.requests[0]!.counts.destroy).toBe(1);expect(value.mock.requests[1]!.counts.destroy).toBe(0);value.mock.requests[1]!.callbacks.onSecureConnected({address:b.address,family:b.family,hostnameVerified:true,authorized:true,authorizationError:null});value.mock.requests[1]!.callbacks.onEnd();await expect(second.completion).resolves.toMatchObject({outcome:"ended"});});

  test("validates caller headers completely before agent or request allocation and preserves valid order",async()=>{
    const invalidHeaders:unknown[]=[
      [{name:"Accept",value:"application/json"}],
      [{name:"host",value:"attacker.invalid"}],
      [{name:"accept",value:"a"},{name:"accept",value:"b"}],
      [{name:"x-extra",value:"a"}],
      [{name:"authorization",value:"a\u0000b"}],
      [{name:"authorization",value:"a\u007fb"}],
      [{name:"authorization",value:"a\u0100b"}],
      [{name:"authorization",value:"a\u202eb"}],
      [{name:"authorization",value:"a\ud800b"}],
      [{name:"user-agent",value:"a\r\nb"}],
      [{name:"accept",value:new String("primitive only")}],
      Object.defineProperty([],"0",{enumerable:true,get(){throw new Error("SECRET");}}),
      [{name:"accept",value:"a".repeat(16_383)}],
      Object.assign(new Array(2),{0:{name:"accept",value:"a"}}),
    ];
    for(const headers of invalidHeaders){const value=setup();const target=await targetOf(value);expect(runtimeCode(()=>value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-h",url:target.url,headers:headers as never,maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline))).toBe("pinned-runtime.invalid-input");expect(value.mock.agents).toHaveLength(0);expect(value.mock.requests).toHaveLength(0);}
    const value=setup();const target=await targetOf(value);const input=Object.freeze([Object.freeze({name:"user-agent",value:"\t ~\u0080\u00ff"}),Object.freeze({name:"accept",value:"a".repeat(16_382)}),Object.freeze({name:"authorization",value:"Bearer x"})]);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-valid",url:target.url,headers:input,maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);expect(value.mock.requests[0]!.options.headers).toEqual(input);expect(value.mock.requests[0]!.options.headers).not.toBe(input);expect(Object.isFrozen(value.mock.requests[0]!.options.headers)).toBe(true);expect(value.mock.requests[0]!.options.headers.every(Object.isFrozen)).toBe(true);handle.forceClose();
  });

  test("runtime close synchronously rejects active DNS races and destroys each owned resolver once",async()=>{const value=setup();let late:(value:readonly string[])=>void=()=>undefined;value.mock.resolve4=()=>new Promise((resolve)=>{late=resolve;});value.mock.resolve6=()=>new Promise(()=>undefined);const pending=targetOf(value);const closing=value.runtime.close();expect(value.mock.resolvers[0]).toMatchObject({cancelCount:1,destroyCount:1});await expect(pending).rejects.toMatchObject({code:"network.cancelled"});late(["8.8.8.8"]);await closing;await value.runtime.close();expect(value.mock.resolvers[0]).toMatchObject({cancelCount:1,destroyCount:1});});

  test("quarantines invalid and regressing clocks with valid deterministic settlements",async()=>{const invalidStart=setup();const invalidTarget=await targetOf(invalidStart);invalidStart.mock.timestampNow=()=>"2020-01-01T00:00:00Z";expect(()=>invalidStart.runtime.openPinnedHop(invalidTarget,{ownerId:"hop-owner-v1-clock-start",url:invalidTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),invalidStart.deadline)).toThrow(SecureTransportError);expect(invalidStart.mock.agents).toHaveLength(0);
    const value=setup();const target=await targetOf(value);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-clock-end",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);const request=value.mock.requests[0]!;request.callbacks.onSecureConnected({address:target.address,family:target.family,hostnameVerified:true,authorized:true,authorizationError:null});value.mock.now=Number.NaN;value.mock.timestampNow=()=>"not-a-timestamp";expect(()=>request.callbacks.onEnd()).not.toThrow();const settlement=await handle.completion;expect(settlement).toMatchObject({outcome:"failed",failureCode:"hop.protocol-failed"});expect(settlement.startedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u);expect(settlement.settledAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u);expect(Date.parse(settlement.settledAt)).toBeGreaterThanOrEqual(Date.parse(settlement.startedAt));
    const regressing=setup();const regressingTarget=await targetOf(regressing);const regressingHandle=regressing.runtime.openPinnedHop(regressingTarget,{ownerId:"hop-owner-v1-clock-regress",url:regressingTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),regressing.deadline);const regressingRequest=regressing.mock.requests[0]!;regressingRequest.callbacks.onSecureConnected({address:regressingTarget.address,family:regressingTarget.family,hostnameVerified:true,authorized:true,authorizationError:null});regressing.mock.now+=10;regressing.mock.timestampNow=()=>"2020-01-01T00:00:00.000Z";regressingRequest.callbacks.onEnd();const regressed=await regressingHandle.completion;expect(regressed).toMatchObject({outcome:"failed",failureCode:"hop.protocol-failed"});expect(Date.parse(regressed.settledAt)).toBe(Date.parse(regressed.startedAt)+10);
  });

  test("rejects delayed secure data and end callbacks without timer dispatch",async()=>{
    const secureLate=setup();const secureTarget=await targetOf(secureLate);const secureCallbacks=callbacks();const secureHandle=secureLate.runtime.openPinnedHop(secureTarget,{ownerId:"hop-owner-v1-late-secure",url:secureTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},secureCallbacks,secureLate.deadline);secureLate.mock.now+=11;secureLate.mock.requests[0]!.callbacks.onSecureConnected({address:secureTarget.address,family:secureTarget.family,hostnameVerified:true,authorized:true,authorizationError:null});expect(secureCallbacks.onSecureConnected).not.toHaveBeenCalled();await expect(secureHandle.completion).resolves.toMatchObject({outcome:"failed",failureCode:"hop.connect-timeout"});
    const dataLate=setup();const dataTarget=await targetOf(dataLate);const dataCallbacks=callbacks();const dataHandle=dataLate.runtime.openPinnedHop(dataTarget,{ownerId:"hop-owner-v1-late-data",url:dataTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},dataCallbacks,dataLate.deadline);dataLate.mock.requests[0]!.callbacks.onSecureConnected({address:dataTarget.address,family:dataTarget.family,hostnameVerified:true,authorized:true,authorizationError:null});dataLate.mock.now=1_101;expect(dataLate.mock.requests[0]!.callbacks.onData(new Uint8Array([1]))).toBe("abort");expect(dataCallbacks.onData).not.toHaveBeenCalled();await expect(dataHandle.completion).resolves.toMatchObject({outcome:"cancelled",failureCode:"hop.deadline"});
    const endLate=setup();const endTarget=await targetOf(endLate);const endCallbacks=callbacks();const endHandle=endLate.runtime.openPinnedHop(endTarget,{ownerId:"hop-owner-v1-late-end",url:endTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},endCallbacks,endLate.deadline);endLate.mock.requests[0]!.callbacks.onSecureConnected({address:endTarget.address,family:endTarget.family,hostnameVerified:true,authorized:true,authorizationError:null});endLate.mock.now=1_101;endLate.mock.requests[0]!.callbacks.onEnd();expect(endCallbacks.onEnd).not.toHaveBeenCalled();await expect(endHandle.completion).resolves.toMatchObject({outcome:"cancelled",failureCode:"hop.deadline"});
  });

  test("quarantines synchronous request callbacks before public handle publication",async()=>{for(const mode of ["response","error","protocol"] as const){const value=setup();const target=await targetOf(value);const cb=callbacks();value.mock.onRequest=(requestCallbacks)=>{if(mode==="response")requestCallbacks.onResponse(200,"1.1",[]);else if(mode==="error")requestCallbacks.onError("connect");else requestCallbacks.onProtocolFailure("invalid-protocol");};const handle=value.runtime.openPinnedHop(target,{ownerId:`hop-owner-v1-sync-${mode}`,url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);await expect(handle.completion).resolves.toMatchObject({outcome:"failed"});expect(value.mock.requests[0]!.counts).toMatchObject({end:0,destroy:1});expect(value.mock.agents[0]!.destroyCount).toBe(1);}
    const throwing=setup();const throwingTarget=await targetOf(throwing);throwing.mock.onRequest=(requestCallbacks)=>{requestCallbacks.onProtocolFailure("invalid-protocol");throw new Error("SECRET");};let handle:NodePinnedHopHandleInternal|undefined;expect(()=>{handle=throwing.runtime.openPinnedHop(throwingTarget,{ownerId:"hop-owner-v1-sync-throw",url:throwingTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),throwing.deadline);}).not.toThrow();await expect(handle!.completion).resolves.toMatchObject({outcome:"failed",failureCode:"hop.protocol-failed"});expect(throwing.mock.agents[0]!.destroyCount).toBe(1);
  });

  test("observes reentrant DNS promise rejection before close gate checks",async()=>{const unhandled:unknown[]=[];const listener=(reason:unknown)=>{unhandled.push(reason);};process.on("unhandledRejection",listener);try{const first=setup();first.mock.resolve4=()=>{const rejected=Promise.reject(new Error("SECRET"));void first.runtime.close();return rejected;};first.mock.resolve6=()=>new Promise(()=>undefined);await expect(targetOf(first)).rejects.toMatchObject({code:"network.cancelled"});await new Promise((resolve)=>setTimeout(resolve,0));const second=setup();second.mock.resolve4=async()=>["8.8.8.8"];second.mock.resolve6=()=>{const rejected=Promise.reject(new Error("SECRET"));void second.runtime.close();return rejected;};await expect(targetOf(second)).rejects.toMatchObject({code:"network.cancelled"});await new Promise((resolve)=>setTimeout(resolve,0));expect(unhandled).toEqual([]);}finally{process.off("unhandledRejection",listener);}});

  test("uses absolute connect deadline across synchronous adapter callbacks and return work",async()=>{
    const syncSecure=setup();const syncTarget=await targetOf(syncSecure);syncSecure.mock.onRequest=(requestCallbacks)=>{requestCallbacks.onSecureConnected({address:syncTarget.address,family:syncTarget.family,hostnameVerified:true,authorized:true,authorizationError:null});};const syncHandle=syncSecure.runtime.openPinnedHop(syncTarget,{ownerId:"hop-owner-v1-sync-secure",url:syncTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},callbacks(),syncSecure.deadline);syncSecure.mock.now+=11;for(const [id,timer] of [...syncSecure.mock.timers])if(id!==1)timer();syncSecure.mock.requests[0]!.callbacks.onEnd();await expect(syncHandle.completion).resolves.toMatchObject({outcome:"ended"});expect(syncSecure.mock.timerMilliseconds.size).toBe(1);
    const syncSlow=setup();const slowTarget=await targetOf(syncSlow);syncSlow.mock.onRequest=()=>{syncSlow.mock.now+=11;};const slowHandle=syncSlow.runtime.openPinnedHop(slowTarget,{ownerId:"hop-owner-v1-sync-slow",url:slowTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},callbacks(),syncSlow.deadline);const slowEndCount=syncSlow.mock.requests[0]!.counts.end;const slowTimerCount=syncSlow.mock.timerMilliseconds.size;slowHandle.forceClose();expect(slowEndCount).toBe(0);expect(slowTimerCount).toBe(1);await expect(slowHandle.completion).resolves.toMatchObject({outcome:"failed",failureCode:"hop.connect-timeout"});
    const asyncValue=setup();const asyncTarget=await targetOf(asyncValue);const asyncHandle=asyncValue.runtime.openPinnedHop(asyncTarget,{ownerId:"hop-owner-v1-async-normal",url:asyncTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},callbacks(),asyncValue.deadline);expect([...asyncValue.mock.timerMilliseconds.values()]).toEqual([1_000,10]);asyncHandle.forceClose();
  });

  test("maps malformed injected Node operations to invalid-capability without invoking defaults",()=>{const mock=createMockSecureTransportCapabilities();expect(()=>createNodeRuntimeCapabilitiesInternal({...mock.ops,httpsRequest:undefined} as never)).toThrow(expect.objectContaining({code:"transport.invalid-capability"}));});

  test("cancels and destroys fake-backed Node DNS resolver operations idempotently",async()=>{const mock=createMockSecureTransportCapabilities();mock.resolve4=()=>new Promise(()=>undefined);mock.resolve6=()=>new Promise(()=>undefined);const runtime=createNodeRuntimeCapabilitiesInternal(mock.ops);const resolver=createNodeDnsResolver(runtime);const controller=new AbortController();const pending=(resolver as unknown as {resolveAll:(hostname:string,signal:AbortSignal)=>Promise<unknown>}).resolveAll;expect(pending).toBeUndefined();const deadline=createRequestDeadlineInternal(10,createNodeRequestDeadlineSchedulerCapabilitiesInternal(runtime),controller.signal);const pinned=createPinnedHopRuntimeInternal(undefined,runtime);const target=pinned.resolveProviderTarget("https://api.crossref.org",deadline);controller.abort();await expect(target).rejects.toBeDefined();expect(mock.resolvers[0]?.cancelCount).toBe(1);expect(mock.resolvers[0]?.destroyCount).toBe(1);await pinned.close();await pinned.close();});

  test("validates exact NodeOperations descriptors and lazily references defaults without invoking them",()=>{const mock=createMockSecureTransportCapabilities();const createResolver=vi.spyOn(mock.ops,"createResolver");const runtime=createNodeRuntimeCapabilitiesInternal(mock.ops);expect(Object.isFrozen(runtime)).toBe(true);expect(createResolver).not.toHaveBeenCalled();expect(()=>createNodeRuntimeCapabilitiesInternal({...mock.ops,extra:true} as never)).toThrow(SecureTransportError);const getter=Object.defineProperty({},"createResolver",{enumerable:true,get(){throw new Error("SECRET");}});expect(()=>createNodeRuntimeCapabilitiesInternal(getter as NodeOperationsInternal)).toThrow(SecureTransportError);});
});
