import { describe, expect, test, vi } from "vitest";

import { canonicalJson } from "../../src/crypto/canonical-json.js";
import { sha256Hex } from "../../src/crypto/hash.js";
import { NetworkPolicyError } from "../../src/acquisition/network-policy.js";
import {
  PinnedHopRuntimeErrorInternal, SecureTransportError,
  createNodeDnsResolver, createNodeRuntimeCapabilitiesInternal, createPinnedHopRuntimeInternal,
  type NodePinnedHopCallbacksInternal, type NodeOperationsInternal,
} from "../../src/acquisition/node-pinned-hop-internal.js";
import {
  RequestDeadlineErrorInternal, claimRequestDeadlineInternal, createNodeRequestDeadlineSchedulerCapabilitiesInternal,
  createRequestDeadlineInternal,
} from "../../src/acquisition/request-deadline-internal.js";
import { createMockSecureTransportCapabilities } from "../helpers/mock-secure-transport.js";

function callbacks():NodePinnedHopCallbacksInternal { return {onSecureConnected:vi.fn(),onProtocolFailure:vi.fn(),onResponse:vi.fn(),onData:vi.fn(()=>"continue" as const),onEnd:vi.fn(),onError:vi.fn()}; }
function setup(){const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const scheduler=createNodeRequestDeadlineSchedulerCapabilitiesInternal(node);const deadline=createRequestDeadlineInternal(1_000,scheduler);claimRequestDeadlineInternal(deadline,"transport-request-v1-owner");const runtime=createPinnedHopRuntimeInternal(undefined,node);return{mock,node,scheduler,deadline,runtime};}
async function targetOf(value=setup()){return value.runtime.resolveProviderTarget("https://api.crossref.org/works",value.deadline);}
function runtimeCode(action:()=>unknown):string|undefined {try{action();}catch(error){expect(error).toBeInstanceOf(PinnedHopRuntimeErrorInternal);return(error as PinnedHopRuntimeErrorInternal).code;}return undefined;}

describe("authenticated pinned Node hops",()=>{
  test("races hung DNS against fake clock deadline cancels resolver and ignores late answers",async()=>{
    const value=setup();let lateResolve:((answers:readonly string[])=>void)|undefined;value.mock.resolve4=()=>new Promise((resolve)=>{lateResolve=resolve;});value.mock.resolve6=()=>new Promise(()=>undefined);
    const pending=value.runtime.resolveProviderTarget("https://api.crossref.org/works",value.deadline);value.mock.now=1_101;for(const timer of [...value.mock.timers.values()])timer();await expect(pending).rejects.toMatchObject({code:"request-deadline.expired"});expect(value.mock.resolvers[0]?.cancelCount).toBe(1);expect(value.mock.resolvers[0]?.destroyCount).toBe(1);lateResolve?.(["8.8.8.8"]);await Promise.resolve();
  });

  test("same runtime resolves all answers hashes deterministic pin then opens only chosen peer",async()=>{
    const value=setup();value.mock.resolve4=async()=>["8.8.8.8","1.1.1.1"];value.mock.resolve6=async()=>["2606:4700:4700::1111"];
    const target=await targetOf(value);expect(target.address).toBe("1.1.1.1");expect(target.allAddressesSha256).toBe(sha256Hex(canonicalJson({schemaVersion:1,addresses:[{address:"1.1.1.1",family:4},{address:"8.8.8.8",family:4},{address:"2606:4700:4700::1111",family:6}]})));
    const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:1024,connectTimeoutMs:100},cb,value.deadline);expect(value.mock.requests).toHaveLength(1);const request=value.mock.requests[0]!;expect(request.options.pinnedAddress).toBe("1.1.1.1");request.callbacks.onSecureConnected({address:"1.1.1.1",family:"IPv4",hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onEnd();await expect(handle.completion).resolves.toMatchObject({outcome:"ended",peer:{address:"1.1.1.1",family:4}});
  });

  test("rejects forged cross-runtime replayed stale and URL-host-mismatched pins before request allocation",async()=>{
    const first=setup();const second=setup();const target=await targetOf(first);const cb=callbacks();expect(runtimeCode(()=>second.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.invalid-capability");
    expect(runtimeCode(()=>first.runtime.openPinnedHop({...target} as never,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.invalid-capability");expect(first.mock.requests).toHaveLength(0);
    expect(runtimeCode(()=>first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:"https://api.crossref.org/other",headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.target-mismatch");expect(first.mock.requests).toHaveLength(0);
    const stale=setup();const staleTarget=await targetOf(stale);await stale.runtime.close();expect(runtimeCode(()=>stale.runtime.openPinnedHop(staleTarget,{ownerId:"hop-owner-v1-stale",url:staleTarget.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,stale.deadline))).toBe("pinned-runtime.pin-stale");
    const handle=first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-x",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline);expect(runtimeCode(()=>first.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-y",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,first.deadline))).toBe("pinned-runtime.pin-replayed");handle.forceClose();await handle.close();
  });

  test("creates a fresh branded pin for every redirect and exposes no caller pinnedAddress input",async()=>{const value=setup();const a=await targetOf(value);const b=await value.runtime.resolveProviderTarget("https://api.crossref.org/next",value.deadline);expect(a).not.toBe(b);expect(Object.keys(a)).not.toContain("deadline");expect(runtimeCode(()=>value.runtime.openPinnedHop(a,{ownerId:"hop-owner-v1-a",url:a.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100,pinnedAddress:"9.9.9.9"} as never,callbacks(),value.deadline))).toBe("pinned-runtime.invalid-input");});

  test("pins DNS lookup once and verifies original Host SNI certificate and peer before bytes",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;expect(request.options.hostHeader).toBe("api.crossref.org");expect(request.options.servername).toBe("api.crossref.org");expect(request.options.checkServerIdentity("api.crossref.org",{})).toBeUndefined();expect(cb.onResponse).not.toHaveBeenCalled();request.callbacks.onSecureConnected({address:target.address,family:target.family,hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onData(new Uint8Array([1]));expect(cb.onData).toHaveBeenCalledOnce();handle.forceClose();});

  test("sets bundled CA rejectUnauthorized maxHeaderSize strict parser and duplicate policy",async()=>{const value=setup();const target=await targetOf(value);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:1234,connectTimeoutMs:100},callbacks(),value.deadline);const options=value.mock.requests[0]!.options;expect(options.ca).toEqual(["TEST ROOT A","TEST ROOT B"]);expect(Object.isFrozen(options.ca)).toBe(true);expect(options).toMatchObject({rejectUnauthorized:true,maxHeaderSize:1234,insecureHTTPParser:false,joinDuplicateHeaders:false});handle.forceClose();});

  test("maps pre-response llhttp failures to typed protocol callbacks before socket errors",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;request.callbacks.onProtocolFailure("invalid-header-token");request.callbacks.onError("socket");expect(cb.onProtocolFailure).toHaveBeenCalledWith("invalid-header-token");await expect(handle.completion).resolves.toMatchObject({outcome:"failed",failureCode:"hop.protocol-failed"});});

  test("destroys request socket agent timers and listeners on abort timeout error and late events",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:10},cb,value.deadline);value.mock.now+=11;[...value.mock.timers.values()].at(-1)!();await expect(handle.completion).resolves.toMatchObject({failureCode:"hop.connect-timeout"});expect(value.mock.requests[0]!.counts.destroy).toBe(1);expect(value.mock.agents[0]!.destroyCount).toBe(1);value.mock.requests[0]!.callbacks.onEnd();expect(cb.onEnd).not.toHaveBeenCalled();});

  test("force closes hanging hop synchronously through request socket destroy and quarantines every late callback byte",async()=>{const value=setup();const target=await targetOf(value);const cb=callbacks();const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},cb,value.deadline);const request=value.mock.requests[0]!;handle.forceClose();handle.forceClose();expect(request.counts.destroy).toBe(1);request.callbacks.onSecureConnected({address:target.address,family:4,hostnameVerified:true,authorized:true,authorizationError:null});request.callbacks.onData(new Uint8Array([1,2,3]));request.callbacks.onEnd();expect(cb.onData).not.toHaveBeenCalled();await expect(handle.completion).resolves.toMatchObject({outcome:"cancelled"});});

  test("uses request-owned nonpooling HTTPS and HTTP agents and never globals",async()=>{const value=setup();const target=await targetOf(value);const handle=value.runtime.openPinnedHop(target,{ownerId:"hop-owner-v1-a",url:target.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);expect(value.mock.agents[0]!.agent).toMatchObject({protocol:"https:",keepAlive:false,maxSockets:1,maxFreeSockets:0});expect(value.mock.ops.createRequestOwnedAgent("http:")).toMatchObject({protocol:"http:",keepAlive:false,maxSockets:1,maxFreeSockets:0});handle.forceClose();});

  test("accepts concurrent hops without cross-cancellation or resolver reuse",async()=>{const value=setup();const a=await targetOf(value);const b=await value.runtime.resolveProviderTarget("https://api.crossref.org/next",value.deadline);const first=value.runtime.openPinnedHop(a,{ownerId:"hop-owner-v1-a",url:a.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);const second=value.runtime.openPinnedHop(b,{ownerId:"hop-owner-v1-b",url:b.url,headers:[],maxHeaderSize:100,connectTimeoutMs:100},callbacks(),value.deadline);first.abort();expect(value.mock.requests[0]!.counts.destroy).toBe(1);expect(value.mock.requests[1]!.counts.destroy).toBe(0);value.mock.requests[1]!.callbacks.onSecureConnected({address:b.address,family:b.family,hostnameVerified:true,authorized:true,authorizationError:null});value.mock.requests[1]!.callbacks.onEnd();await expect(second.completion).resolves.toMatchObject({outcome:"ended"});});

  test("cancels and destroys fake-backed Node DNS resolver operations idempotently",async()=>{const mock=createMockSecureTransportCapabilities();mock.resolve4=()=>new Promise(()=>undefined);mock.resolve6=()=>new Promise(()=>undefined);const runtime=createNodeRuntimeCapabilitiesInternal(mock.ops);const resolver=createNodeDnsResolver(runtime);const controller=new AbortController();const pending=(resolver as unknown as {resolveAll:(hostname:string,signal:AbortSignal)=>Promise<unknown>}).resolveAll;expect(pending).toBeUndefined();const deadline=createRequestDeadlineInternal(10,createNodeRequestDeadlineSchedulerCapabilitiesInternal(runtime),controller.signal);const pinned=createPinnedHopRuntimeInternal(undefined,runtime);const target=pinned.resolveProviderTarget("https://api.crossref.org",deadline);controller.abort();await expect(target).rejects.toBeDefined();expect(mock.resolvers[0]?.cancelCount).toBe(1);expect(mock.resolvers[0]?.destroyCount).toBe(1);await pinned.close();await pinned.close();});

  test("validates exact NodeOperations descriptors and lazily references defaults without invoking them",()=>{const mock=createMockSecureTransportCapabilities();const createResolver=vi.spyOn(mock.ops,"createResolver");const runtime=createNodeRuntimeCapabilitiesInternal(mock.ops);expect(Object.isFrozen(runtime)).toBe(true);expect(createResolver).not.toHaveBeenCalled();expect(()=>createNodeRuntimeCapabilitiesInternal({...mock.ops,extra:true} as never)).toThrow(SecureTransportError);const getter=Object.defineProperty({},"createResolver",{enumerable:true,get(){throw new Error("SECRET");}});expect(()=>createNodeRuntimeCapabilitiesInternal(getter as NodeOperationsInternal)).toThrow(SecureTransportError);});
});
