import {describe,expect,test,vi} from "vitest";

import {createContentDecodeCapabilitiesInternal} from "../../src/acquisition/content-decoding-internal.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {createProviderPartitionExecutor} from "../../src/acquisition/providers/shared.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import {createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createProviderRequestPartitionFixtureInternal,normalizeAcquisitionOptions,type ProviderRequestPartitionInternal,type ProviderRequestPartitionSnapshotInternal,type TransportSettlement} from "../../src/acquisition/contracts.js";
import {createMockSecureTransportCapabilities} from "../helpers/mock-secure-transport.js";

const normalized=normalizeAcquisitionOptions(undefined);const options=normalized.providers;
const registryOptions={maxPartitions:normalized.maxPartitions,maxCanonicalUrlBytes:normalized.transport.maxCanonicalUrlBytes,maxStructureDepth:normalized.maxStructureDepth,maxStructureNodes:normalized.maxStructureNodes,maxStructureKeys:normalized.maxStructureKeys,maxStringCanonicalBytes:normalized.maxStringCanonicalBytes,maxScalarCanonicalBytes:normalized.maxScalarCanonicalBytes};
function partition(snapshot:ProviderRequestPartitionSnapshotInternal):ProviderRequestPartitionInternal{return createProviderRequestPartitionFixtureInternal({partition:snapshot,options:registryOptions});}
async function settlement(snapshot:ProviderRequestPartitionSnapshotInternal,payload:string):Promise<TransportSettlement>{const mock=createMockSecureTransportCapabilities();const node=createNodeRuntimeCapabilitiesInternal(mock.ops);const transport=createSecureJsonTransport(normalized,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node)));const completion=transport.request({partitionKey:snapshot.partitionKey,partitionKeySha256:snapshot.partitionKeySha256,provider:snapshot.provider,operation:snapshot.operation,endpointClass:snapshot.endpointClass,target:snapshot.target,url:snapshot.url});for(let count=0;count<100&&mock.requests.length===0;count+=1)await Promise.resolve();const request=mock.requests[0]!;request.callbacks.onSecureConnected({address:request.options.pinnedAddress,family:request.options.family,hostnameVerified:true,authorized:true,authorizationError:null});const bytes=new TextEncoder().encode(payload);request.callbacks.onResponse(200,"1.1",["content-length",String(bytes.byteLength)]);request.callbacks.onData(bytes);request.callbacks.onEnd();const output=await completion;await transport.close();return output;}
async function run(payload:unknown){const adapter=createOpenAlexAdapter();const snapshot=adapter.buildSearchPartition({query:"synthetic",limit:10});const wire=await settlement(snapshot,JSON.stringify(payload));return adapter.search(partition(snapshot),options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));}
const work={id:"https://openalex.org/W123",doi:"https://doi.org/10.5555/synthetic.2",ids:{doi:"10.5555/SYNTHETIC.2",pmid:"https://pubmed.ncbi.nlm.nih.gov/12345/",pmcid:"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC67890/"},display_name:"Synthetic",authorships:[{author:{display_name:"Ada Literal"}}],primary_location:{landing_page_url:"https://example.org/work",source:{display_name:"Venue"}},publication_date:"2024-02-29",publication_year:2023,type:"review",abstract_inverted_index:{bounded:[0],abstract:[1]}};

describe("OpenAlex metadata adapter",()=>{
 test("builds exact RFC3986 ordered OpenAlex paths parameters and select list",()=>{const adapter=createOpenAlexAdapter();expect(adapter.buildSearchPartition({query:"space / café",limit:7}).url).toBe("https://api.openalex.org/works?per-page=7&search=space%20%2F%20caf%C3%A9&select=id%2Cdoi%2Cdisplay_name%2Cauthorships%2Cprimary_location%2Cpublication_date%2Cpublication_year%2Ctype%2Cabstract_inverted_index%2Cids");expect(adapter.buildFetchPartition({identifierKind:"doi",identifier:"10.5555/ABC"}).url).toBe("https://api.openalex.org/works/https%3A%2F%2Fdoi.org%2F10.5555%2Fabc");});
 test("requires canonical OpenAlex provider ID and reconciles top-level and ids DOI PMID PMCID exactly",async()=>{const result=await run({results:[work]});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");const draft=result.outcomes[0]!.candidateDrafts[0]!;expect([draft.providerRecordId,draft.identifiers]).toEqual(["https://openalex.org/W123",{doi:"10.5555/synthetic.2",pmid:"12345",pmcid:"PMC67890"}]);for(const bad of [{...work,id:"W123"},{...work,ids:{...work.ids,doi:"10.5555/conflict"}}])expect((await run({results:[bad]})).outcomes[0]!.code).toBe("provider.invalid-response");});
 test("parses exact OpenAlex date precedence author literals venue URL and type mappings",async()=>{for(const [type,expected] of [["article","journal-article"],["review","review"],["dataset","dataset"],["book","other"]] as const){const result=await run({results:[{...work,type}]});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");const draft=result.outcomes[0]!.candidateDrafts[0]!;expect([draft.published,draft.authors,draft.containerTitle,draft.canonicalUrl,draft.publicationType]).toEqual([{date:"2024-02-29",precision:"day"},[{family:null,given:null,literal:"Ada Literal",orcid:null}],"Venue","https://example.org/work",expected]);}});
 test("reconstructs bounded OpenAlex inverted abstracts deterministically",async()=>{const result=await run({results:[{...work,abstract_inverted_index:{world:[1],hello:[0],again:[2]}}]});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");expect([result.outcomes[0]!.candidateDrafts[0]!.abstractText,result.outcomes[0]!.candidateDrafts[0]!.accessLevel]).toEqual(["hello world again","abstract-only"]);});
 test("rejects duplicate sparse negative unsafe hole and oversized abstract positions before allocation",async()=>{const cases=[{a:[0],b:[0]},{a:[-1]},{a:[Number.MAX_SAFE_INTEGER]},{a:[1]},{a:Object.assign([0,1],{length:3})}];for(const inverted of cases){const parse=vi.spyOn(Array.prototype,"sort");const result=await run({results:[{...work,abstract_inverted_index:inverted}]});expect(result.outcomes[0]!.code).toBe("provider.invalid-response");parse.mockRestore();}});
 test("uses existing DOI and URL normalization without claiming ORCID support",async()=>{const result=await run({results:[{...work,doi:"HTTPS://DOI.ORG/10.5555/synthetic.2",primary_location:{landing_page_url:"not a url",source:null}}]});if(result.outcomes[0]!.status!=="success")throw new Error("success expected");expect(result.outcomes[0]!.candidateDrafts[0]!.canonicalUrl).toBe("https://doi.org/10.5555/synthetic.2");expect(result.outcomes[0]!.warnings).toEqual([{code:"provider.invalid-identifier-omitted",recordOrdinal:0,field:"doi"},{code:"provider.invalid-url-omitted",recordOrdinal:0,field:"primary_location.landing_page_url"}]);expect(Object.keys(await import("../../src/acquisition/providers/openalex.js"))).not.toContain("normalizeOrcid");});
});
