import {describe,expect,test} from "vitest";
import {normalizeAcquisitionOptions,assertProviderRequestPartitionInternal,lookupProviderRequestPartitionInternal} from "../../src/acquisition/contracts.js";
import {createCrossrefAdapter} from "../../src/acquisition/providers/crossref.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {createPubmedAdapter} from "../../src/acquisition/providers/pubmed.js";
import {createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {createAcquisitionPlanningCapabilitiesInternal,planAcquisitionInvocation,getAcquisitionExecutionPlanSnapshotInternal,listInvocationConcretePartitionsInternal,listInvocationConditionalReservationsInternal,inspectConditionalReservationInternal,createConditionalMaterializationFactsInternal,AcademicAcquisitionError} from "../../src/acquisition/planner-internal.js";

const options=normalizeAcquisitionOptions(undefined);
const caps=()=>createAcquisitionPlanningCapabilitiesInternal({crossref:createCrossrefAdapter(),openalex:createOpenAlexAdapter(),pubmed:createPubmedAdapter(),pmc:createPmcAdapter()});
const search=(raw:Record<string,unknown>={queries:["alpha"]})=>planAcquisitionInvocation({operation:"search",raw} as never,options,caps());
const fetchPlan=(kind:"doi"|"pmid"|"pmcid",identifier:string)=>planAcquisitionInvocation({operation:"fetch",raw:{identifierKind:kind,identifier}},options,caps());
function errorCode(action:()=>unknown){try{action();}catch(error){expect(error).toBeInstanceOf(AcademicAcquisitionError);return(error as AcademicAcquisitionError).code;}return undefined;}

describe("bounded acquisition planner",()=>{
 test("planAcquisitionInvocation accepts only authentic normalized-options identity closed raw search fetch discriminants and planning capability",()=>{expect(getAcquisitionExecutionPlanSnapshotInternal(search()).input.operation).toBe("search");expect(getAcquisitionExecutionPlanSnapshotInternal(fetchPlan("doi","10.5555/example")).input.operation).toBe("fetch");for(const value of [{operation:"search",raw:{queries:["x"]},extra:true},{operation:"other",raw:{queries:["x"]}},{operation:"fetch",raw:{identifierKind:"doi"}}])expect(errorCode(()=>planAcquisitionInvocation(value as never,options,caps()))).toBe("acquisition.invalid-input");});
 test("rejects forged cloned mutated-hash or foreign normalized options before planning capability and per-call input access",()=>{let traps=0;const input=new Proxy({}, {get(){traps++;throw new Error("secret");},getOwnPropertyDescriptor(){traps++;throw new Error("secret");}}),capability=new Proxy({}, {get(){traps++;throw new Error("secret");}});expect(errorCode(()=>planAcquisitionInvocation(input as never,{...options} as never,capability as never))).toBe("acquisition.invalid-capability");expect(traps).toBe(0);});
 test("normalizes exact bounded per-call queries providers filters identifiers and requested max without redefaulting options",()=>{const plan=search({queries:[" z ","a","z","a"],providers:["pubmed"],maxResultsPerQuery:7,publicationTypes:["review"],fromYear:2000,toYear:2024}),snapshot=getAcquisitionExecutionPlanSnapshotInternal(plan);expect(snapshot.input).toMatchObject({normalizedQueries:["a","z"],providers:["pubmed"],requestedMaxResultsPerQuery:7,publicationTypes:["review"],fromYear:2000,toYear:2024});expect(snapshot.options).toBe(options);expect(errorCode(()=>search({queries:["\tbad"]}))).toBe("acquisition.invalid-input");});
 test("computes cleanup capacity from concrete plus reserved ownerCapacity at zero default and 64-slot boundary",()=>{const empty=getAcquisitionExecutionPlanSnapshotInternal(search({queries:["x"],providers:[]}));expect([empty.ownerCapacity,empty.diagnosticCapacity]).toEqual([0,3]);const one=getAcquisitionExecutionPlanSnapshotInternal(search({queries:["x"],providers:["pubmed"]}));expect([one.ownerCapacity,one.diagnosticCapacity]).toEqual([2,13]);const defaultTwelve=getAcquisitionExecutionPlanSnapshotInternal(search({queries:["a","b","c"]}));expect([defaultTwelve.ownerCapacity,defaultTwelve.diagnosticCapacity]).toEqual([12,63]);const hard=normalizeAcquisitionOptions({maxQueries:16,maxPartitions:64,maxCleanupDiagnostics:323}),boundary=getAcquisitionExecutionPlanSnapshotInternal(planAcquisitionInvocation({operation:"search",raw:{queries:Array.from({length:16},(_,index)=>`q${index}`)}},hard,caps()));expect([boundary.ownerCapacity,boundary.diagnosticCapacity]).toEqual([64,323]);});
 test("maps owner multiply add overflow or capacity excess to acquisition too-many-partitions before allocation dispatch",()=>{const tiny=normalizeAcquisitionOptions({maxPartitions:1,maxCleanupDiagnostics:8});expect(errorCode(()=>planAcquisitionInvocation({operation:"search",raw:{queries:["x"],providers:["pubmed"]}},tiny,caps()))).toBe("acquisition.too-many-partitions");});
 test("deduplicates all five actual-owner and three global cleanup codes while skipped reservation capacity stays empty",()=>{const snapshot=getAcquisitionExecutionPlanSnapshotInternal(search({queries:["x"],providers:[]}));expect(snapshot.diagnosticCapacity).toBe(3);});
 test("computes exact caller configured Crossref OpenAlex PubMed endpoint minima once while parser keeps raw maxProviderRecords",()=>{const custom=normalizeAcquisitionOptions({maxResultsPerQuery:100,providers:{maxProviderRecords:700,maxConditionalIdentifiers:700}}),plan=planAcquisitionInvocation({operation:"search",raw:{queries:["x"],maxResultsPerQuery:600}},custom,caps());expect(getAcquisitionExecutionPlanSnapshotInternal(plan).effectiveProviderLimits.map(x=>[x.provider,x.effectiveLimit])).toEqual([["crossref",100],["openalex",100],["pubmed",100]]);});
 test("builds authentic frozen concrete reservation capacity snapshots with zero network sink scheduler executor calls",()=>{const plan=search(),parts=listInvocationConcretePartitionsInternal(plan),reservations=listInvocationConditionalReservationsInternal(plan);expect([parts.length,reservations.length,Object.isFrozen(parts),Object.isFrozen(reservations)]).toEqual([3,1,true,true]);for(const item of parts){expect(()=>assertProviderRequestPartitionInternal(item.partition)).not.toThrow();expect(Object.isFrozen(item)).toBe(true);}});
 test("gets provider results only through shared O1 registry and maps forged clone mutated hash to internal-contract without reparse",()=>{expect(errorCode(()=>createConditionalMaterializationFactsInternal(Object.freeze({}) as never,"partition-v1-"+"0".repeat(64) as never))).toBe("acquisition.internal-contract");});
 test("registers concrete and materialized opaque partitions under one real plan owner and rejects forged foreign fixture or stale owner values",()=>{const parts=listInvocationConcretePartitionsInternal(search());expect(new Set(parts.map(x=>lookupProviderRequestPartitionInternal(x.partition).partitionKey)).size).toBe(parts.length);});
 test("brands concrete ESummary ELink PMC reservations with exact IDs parents kinds ordinals one-shot state and no future URL key",()=>{const reservations=listInvocationConditionalReservationsInternal(fetchPlan("pmid","9"));expect(reservations.map(x=>[x.futureOperationKind,x.ordinal,x.maxMaterializations,inspectConditionalReservationInternal(x).state])).toEqual([["pubmed-elink",1,1,"reserved"],["pmc-bioc",2,1,"reserved"]]);for(const reservation of reservations){expect(reservation.reservationId).toMatch(/^reservation-v1-[a-f0-9]{64}$/u);expect("url" in reservation||"partitionKey" in reservation).toBe(false);}});
 test("counts all concrete plus every conditional reservation in ownerCapacity even when sink or parent later skips slots",()=>{const snapshot=getAcquisitionExecutionPlanSnapshotInternal(fetchPlan("pmid","9"));expect([snapshot.ownerCapacity,snapshot.diagnosticCapacity]).toEqual([3,18]);});
 test("dispatches concrete slots only after release and never reuses sink-skipped capacity",()=>{const plan=search({queries:["x"],providers:[]});expect(listInvocationConcretePartitionsInternal(plan)).toEqual([]);});
 test("materializes successful parent facts atomically into exact one partition and skips failure blocked or no IDs",()=>{const reservation=listInvocationConditionalReservationsInternal(search({queries:["x"],providers:["pubmed"]}))[0]!;expect(inspectConditionalReservationInternal(reservation)).toEqual({reservationId:reservation.reservationId,state:"reserved"});});
 test("maps double foreign wrong-parent or over-one reservation materialization to internal-contract",()=>{const reservation=listInvocationConditionalReservationsInternal(search({queries:["x"],providers:["pubmed"]}))[0]!;expect(errorCode(()=>inspectConditionalReservationInternal({...reservation} as never))).toBe("acquisition.internal-contract");});
});
