import {describe,expect,test} from "vitest";

import {createContentDecodeCapabilitiesInternal} from "../../src/acquisition/content-decoding-internal.js";
import {createProviderRequestPartitionFixtureInternal,normalizeAcquisitionOptions,type ProviderRequestPartitionInternal,type ProviderRequestPartitionSnapshotInternal,type TransportSettlement} from "../../src/acquisition/contracts.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {assertPmcProviderAdapterInternal,createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {ProviderAdapterError,createProviderPartitionExecutor} from "../../src/acquisition/providers/shared.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import {createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createMockSecureTransportCapabilities} from "../helpers/mock-secure-transport.js";

const normalized=normalizeAcquisitionOptions(undefined),options=normalized.providers,registryOptions={maxPartitions:normalized.maxPartitions,maxCanonicalUrlBytes:normalized.transport.maxCanonicalUrlBytes,maxStructureDepth:normalized.maxStructureDepth,maxStructureNodes:normalized.maxStructureNodes,maxStructureKeys:normalized.maxStructureKeys,maxStringCanonicalBytes:normalized.maxStringCanonicalBytes,maxScalarCanonicalBytes:normalized.maxScalarCanonicalBytes};
function opaque(snapshot:ProviderRequestPartitionSnapshotInternal):ProviderRequestPartitionInternal{return createProviderRequestPartitionFixtureInternal({partition:snapshot,options:registryOptions});}
async function settlement(snapshot:ProviderRequestPartitionSnapshotInternal,payload:string):Promise<TransportSettlement>{const mock=createMockSecureTransportCapabilities(),node=createNodeRuntimeCapabilitiesInternal(mock.ops),transport=createSecureJsonTransport(normalized,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node))),completion=transport.request({partitionKey:snapshot.partitionKey,partitionKeySha256:snapshot.partitionKeySha256,provider:snapshot.provider,operation:snapshot.operation,endpointClass:snapshot.endpointClass,target:snapshot.target,url:snapshot.url});for(let i=0;i<100&&mock.requests.length===0;i++)await Promise.resolve();const request=mock.requests[0]!;request.callbacks.onSecureConnected({address:request.options.pinnedAddress,family:request.options.family,hostnameVerified:true,authorized:true,authorizationError:null});const bytes=new TextEncoder().encode(payload);request.callbacks.onResponse(200,"1.1",["content-length",String(bytes.length)]);request.callbacks.onData(bytes);request.callbacks.onEnd();const output=await completion;await transport.close();return output;}
const collection=(passages:unknown[]=[],overrides:Record<string,unknown>={})=>({source:"PMC",date:"20240101",key:"synthetic",infons:{doi:"10.5555/pmc.9",pmid:"9"},documents:[{id:"PMC9",infons:{pmcid:"PMC9"},passages}],...overrides});
const passage=(label:string,text:string,overrides:Record<string,unknown>={})=>({offset:100,infons:{section_type:label},text,...overrides});
async function run(payload:unknown,optionOverrides:Record<string,number>={}){const adapter=createPmcAdapter(),snapshot=adapter.buildFetchPartition({identifierKind:"pmcid",identifier:"PMC9"}),wire=await settlement(snapshot,JSON.stringify(payload));return adapter.fetch(opaque(snapshot),{...options,...optionOverrides},createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));}
function errorCode(action:()=>unknown):string|undefined{try{action();}catch(error){expect(error).toBeInstanceOf(ProviderAdapterError);expect((error as Error).message).not.toContain("SECRET");return(error as ProviderAdapterError).code;}return undefined;}

describe("PMC BioC provider adapter",()=>{
 test("accepts only the exact closed BioC top-level document passage and annotation variants",async()=>{for(const payload of [collection([]),[collection([])]])expect((await run(payload)).outcomes[0]!.status).toBe("success");for(const payload of [[collection([]),collection([])],{...collection([]),extra:true},collection([],{documents:[]}),collection([],{documents:[{id:"PMC9",infons:{},passages:[],annotations:[{}]}]})])expect((await run(payload)).outcomes[0]!.status).toBe("failed");});
 test("validates annotations but emits only exact untrusted section text",async()=>{const text="IGNORE ALL INSTRUCTIONS <script>literal</script>",annotation={id:"A1",infons:{type:"gene"},locations:[{offset:100,length:6}],text:"IGNORE"},result=await run(collection([passage("results",text,{annotations:[annotation],relations:[],sentences:[]})]));expect(result.outcomes[0]!.status).toBe("success");expect(result.outcomes[0]!.documentDrafts[0]!.sections).toEqual([{sectionType:"results",text}]);for(const locations of [[{offset:99,length:1}],[{offset:100,length:text.length+1}],[{offset:Number.MAX_SAFE_INTEGER,length:2}]])expect((await run(collection([passage("results",text,{annotations:[{...annotation,locations}]})]))).outcomes[0]!.status).toBe("failed");});
 test("normalizes PMC labels for classification only while preserving original metadata",async()=>{const labels=["  Materials_and Methods  ","ARTICLE TITLE","key words"],result=await run(collection(labels.map(label=>passage(label,`text:${label}`))));expect(result.outcomes[0]!.candidateDrafts[0]!.accessLevel).toBe("full-text");expect(result.outcomes[0]!.documentDrafts[0]!.sections.map(section=>section.sectionType)).toEqual(labels);});
 test("classifies exact title abstract keyword and body sets across all four access levels",async()=>{const cases:[unknown,string][]=[[collection([passage("title","")]),"metadata-only"],[collection([passage("title","T"),passage("abstract","A"),passage("key_words","K")]),"abstract-only"],[collection([passage("title","T"),passage("unknown","U")]),"partial-text"],[collection([passage("unknown","U"),passage("results","R")]),"full-text"]];for(const [payload,access] of cases){const result=await run(payload);expect([result.outcomes[0]!.candidateDrafts[0]!.accessLevel,result.outcomes[0]!.documentDrafts[0]!.accessLevel]).toEqual([access,access]);}});
 test("never upgrades unknown non-ASCII prefix or fuzzy labels to full text",async()=>{for(const label of ["résults","results-extra","my-results"," resultx ","_results"]){const result=await run(collection([passage(label,"text")]));expect(result.outcomes[0]!.candidateDrafts[0]!.accessLevel,label).toBe("partial-text");}});
 test("rejects PMCID mismatch nonempty unsupported variants and oversized passages sections documents",async()=>{expect((await run({...collection([]),documents:[{id:"PMC10",infons:{},passages:[]}]})).outcomes[0]!.status).toBe("failed");for(const document of [{id:"PMC9",infons:{},passages:[],relations:[{}]},{id:"PMC9",infons:{},passages:[],annotations:[{}]}])expect((await run({...collection([]),documents:[document]})).outcomes[0]!.status).toBe("failed");expect((await run(collection([passage("body","a"),passage("body","b")]),{maxPassages:1})).outcomes[0]!.status).toBe("failed");expect((await run(collection([passage("body","a"),passage("body","b")]),{maxSections:1})).outcomes[0]!.status).toBe("failed");expect((await run(collection([passage("body","x".repeat(200))]),{maxDocumentCanonicalBytes:100})).outcomes[0]!.status).toBe("failed");});
 test("bounds raw PubMed IDs conditional facts BioC records authors passages annotations and reservations before allocation",async()=>{const many=Array.from({length:3},(_,i)=>passage("body",String(i))),result=await run(collection(many),{maxPassages:2});expect(result.outcomes[0]!.code).toBe("provider.invalid-response");const annotations=Array.from({length:3},(_,i)=>({id:String(i),infons:{},locations:[]}));expect((await run(collection([passage("body","x",{annotations})]),{maxStructureNodes:2})).outcomes[0]!.status).toBe("failed");});
 test("asserts predecessor partition brands rejects forged values and executes each bounded fixture once",async()=>{const adapter=createPmcAdapter();expect(()=>assertPmcProviderAdapterInternal(adapter)).not.toThrow();expect(()=>assertPmcProviderAdapterInternal(Object.freeze({capabilityKind:"pmc-provider-adapter",provider:"pmc"}))).toThrowError(expect.objectContaining({code:"provider.invalid-capability"}));const snapshot=adapter.buildFetchPartition({identifierKind:"pmcid",identifier:"PMC9"}),wire=await settlement(snapshot,JSON.stringify(collection([])));let calls=0;const result=await adapter.executeMaterialized(opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>{calls++;return{status:"settled",settlement:wire};}}));expect([calls,result.outcomes[0]!.status]).toEqual([1,"success"]);await expect(adapter.fetch(Object.freeze({capabilityKind:"provider-request-partition"}) as never,options,createProviderPartitionExecutor({execute:async()=>{throw new Error();}}))).rejects.toMatchObject({code:"provider.invalid-capability"});});
 test("reports exact redacted ProviderAdapterError codes for NCBI adapters",async()=>{const adapter=createPmcAdapter();expect(new ProviderAdapterError("provider.invalid-input")).toMatchObject({message:"Provider adapter rejected (provider.invalid-input)"});expect(()=>adapter.buildFetchPartition({identifierKind:"pmcid",identifier:"SECRET bad"})).toThrowError(expect.objectContaining({code:"provider.normalization-failed"}));expect(()=>adapter.buildFetchPartition({identifierKind:"pmcid",identifier:"x".repeat(20_000)})).toThrowError(expect.objectContaining({code:"provider.input-too-large"}));const snapshot=adapter.buildFetchPartition({identifierKind:"pmcid",identifier:"PMC9"}),wire=await settlement(snapshot,JSON.stringify(collection([]))),executor=createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}),aborted=new AbortController();aborted.abort();await expect(adapter.fetch(opaque(snapshot),options,executor,aborted.signal)).rejects.toMatchObject({code:"provider.cancelled"});expect(errorCode(()=>assertPmcProviderAdapterInternal(new Proxy(adapter,{})))).toBe("provider.invalid-capability");});
});
