import {describe,expect,test,vi} from "vitest";

import {canonicalJson} from "../../src/crypto/canonical-json.js";
import {sha256Hex} from "../../src/crypto/hash.js";
import {createContentDecodeCapabilitiesInternal} from "../../src/acquisition/content-decoding-internal.js";
import {createProviderPartitionKey,createProviderRequestPartitionFixtureInternal,normalizeAcquisitionOptions,type ProviderNormalizedInput,type ProviderRequestPartitionInternal,type ProviderRequestPartitionSnapshotInternal,type TransportSettlement} from "../../src/acquisition/contracts.js";
import {createNodeRuntimeCapabilitiesInternal,createPinnedHopRuntimeInternal} from "../../src/acquisition/node-pinned-hop-internal.js";
import {createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {createPubmedAdapter,assertPubmedProviderAdapterInternal} from "../../src/acquisition/providers/pubmed.js";
import {ProviderAdapterError,createProviderExecutionResultInternal,createProviderPartitionExecutor,providerEndpointResultCap} from "../../src/acquisition/providers/shared.js";
import {createNodeRequestDeadlineSchedulerCapabilitiesInternal} from "../../src/acquisition/request-deadline-internal.js";
import {createSecureJsonTransport,createSecureTransportCapabilitiesInternal} from "../../src/acquisition/secure-json-transport-internal.js";
import {createMockSecureTransportCapabilities} from "../helpers/mock-secure-transport.js";

const normalized=normalizeAcquisitionOptions(undefined),options=normalized.providers;
const registryOptions={maxPartitions:normalized.maxPartitions,maxCanonicalUrlBytes:normalized.transport.maxCanonicalUrlBytes,maxStructureDepth:normalized.maxStructureDepth,maxStructureNodes:normalized.maxStructureNodes,maxStructureKeys:normalized.maxStructureKeys,maxStringCanonicalBytes:normalized.maxStringCanonicalBytes,maxScalarCanonicalBytes:normalized.maxScalarCanonicalBytes};
function opaque(snapshot:ProviderRequestPartitionSnapshotInternal):ProviderRequestPartitionInternal{return createProviderRequestPartitionFixtureInternal({partition:snapshot,options:registryOptions});}
function fixture(provider:"pubmed"|"pmc",operation:"search"|"fetch",endpointClass:string,input:ProviderNormalizedInput,url:string):ProviderRequestPartitionSnapshotInternal{const target="ncbi" as const,key=createProviderPartitionKey({provider,operation,endpointClass,target,normalizedInput:input,requestedUrl:url});return Object.freeze({provider,operation,endpointClass,...key,normalizedInput:Object.freeze(input),normalizedInputSha256:sha256Hex(canonicalJson(input)),target,url});}
async function settlement(snapshot:ProviderRequestPartitionSnapshotInternal,payload:string,status=200):Promise<TransportSettlement>{const mock=createMockSecureTransportCapabilities(),node=createNodeRuntimeCapabilitiesInternal(mock.ops),transport=createSecureJsonTransport(normalized,createSecureTransportCapabilitiesInternal(createPinnedHopRuntimeInternal(undefined,node),createContentDecodeCapabilitiesInternal({decodeContentLayer:async(_encoding,input)=>new Uint8Array(input)}),createNodeRequestDeadlineSchedulerCapabilitiesInternal(node))),completion=transport.request({partitionKey:snapshot.partitionKey,partitionKeySha256:snapshot.partitionKeySha256,provider:snapshot.provider,operation:snapshot.operation,endpointClass:snapshot.endpointClass,target:snapshot.target,url:snapshot.url});for(let i=0;i<100&&mock.requests.length===0;i++)await Promise.resolve();const request=mock.requests[0]!;request.callbacks.onSecureConnected({address:request.options.pinnedAddress,family:request.options.family,hostnameVerified:true,authorized:true,authorizationError:null});const bytes=new TextEncoder().encode(payload);request.callbacks.onResponse(status,"1.1",["content-length",String(bytes.length)]);request.callbacks.onData(bytes);request.callbacks.onEnd();const output=await completion;await transport.close();return output;}
const header={type:"eutils",version:"0.3"};
const esearch={header,esearchresult:{count:"3",retmax:"3",retstart:"0",idlist:["100","9","10"],translationset:[],querytranslation:"synthetic"}};
const summaryRecord=(uid:string,overrides:Record<string,unknown>={})=>({uid,title:`Title ${uid}`,authors:[{name:"Ada Literal"}],fulljournalname:"Synthetic Journal",source:"Fallback",sortpubdate:"2024/02/29 00:00",epubdate:"2023 Jan 02",pubdate:"2022 Dec",articleids:[{idtype:"pubmed",value:uid},{idtype:"doi",value:`10.5555/synthetic.${uid}`},{idtype:"pmc",value:`PMC${uid}`}],doctype:"Journal Article",volume:"1",issue:"2",pages:"3-4",elocationid:"e5",...overrides});
const esummary=(uids:string[])=>({header,result:{uids,...Object.fromEntries(uids.map(uid=>[uid,summaryRecord(uid)]))}});
const elink={header,linksets:[{ids:["9"],linksetdbs:[{dbto:"pmc",linkname:"pubmed_pmc",links:["100","9","10","9"]}]}]};
function code(action:()=>unknown):string|undefined{try{action();}catch(error){expect(error).toBeInstanceOf(ProviderAdapterError);return(error as ProviderAdapterError).code;}return undefined;}
async function invoke(snapshot:ProviderRequestPartitionSnapshotInternal,payload:unknown,method:"search"|"fetch"|"executeMaterialized"="executeMaterialized"){const adapter=createPubmedAdapter(),wire=await settlement(snapshot,JSON.stringify(payload));return adapter[method](opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})}));}

describe("PubMed provider adapter",()=>{
 test("exposes fixed PubMed 10000 search and all NCBI fetch 1 endpoint caps",async()=>{expect([providerEndpointResultCap("pubmed","search"),providerEndpointResultCap("pubmed","fetch"),providerEndpointResultCap("pmc","fetch")]).toEqual([10000,1,1]);expect(Object.keys(await import("../../src/acquisition/providers/pubmed.js")).sort()).toEqual(["assertPubmedProviderAdapterInternal","createPubmedAdapter"]);expect(Object.keys(await import("../../src/acquisition/providers/pmc.js")).sort()).toEqual(["assertPmcProviderAdapterInternal","createPmcAdapter"]);const adapter=createPubmedAdapter();expect(()=>assertPubmedProviderAdapterInternal(adapter)).not.toThrow();expect(()=>assertPubmedProviderAdapterInternal(Object.freeze({capabilityKind:"pubmed-provider-adapter",provider:"pubmed"}))).toThrowError(expect.objectContaining({code:"provider.invalid-capability"}));});
 test("builds exact RFC3986 ordered ESearch ESummary ELink and PMC paths",async()=>{const pubmed=createPubmedAdapter(),pmc=createPmcAdapter(),literal="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json",link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},literal);expect(pubmed.buildSearchPartition({query:"space / café",limit:7}).url).toBe("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&retmax=7&retmode=json&term=space%20%2F%20caf%C3%A9");expect(pubmed.buildFetchPartition({identifierKind:"pmid",identifier:"0009"}).url).toBe("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=9&retmode=json");expect(link.url).toBe(literal);expect([...new URL(link.url).searchParams.keys()]).toEqual(["db","dbfrom","id","retmode"]);expect(new URL(link.url).pathname).toBe("/entrez/eutils/elink.fcgi");expect(pmc.buildFetchPartition({identifierKind:"pmcid",identifier:"pmc9"}).url).toBe("https://www.ncbi.nlm.nih.gov/research/bionlp/RESTful/pmcoa.cgi/BioC_json/PMC9/unicode");for(const wrong of ["https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=pubmed&db=pmc&id=9&retmode=json","https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json"]){const bad=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},wrong);let calls=0;await expect(pubmed.executeMaterialized(opaque(bad),options,createProviderPartitionExecutor({execute:async()=>{calls++;throw new Error("SECRET executor");}}))).rejects.toMatchObject({code:"provider.invalid-input",message:"Provider adapter rejected (provider.invalid-input)"});expect(calls).toBe(0);}});
 test("search executes and parses ESearch only emits conditional facts and never executes ESummary or ELink",async()=>{const adapter=createPubmedAdapter(),snapshot=adapter.buildSearchPartition({query:"synthetic",limit:3}),wire=await settlement(snapshot,JSON.stringify(esearch));let calls=0;const result=await adapter.search(opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>{calls++;return{status:"settled",settlement:wire};}}));expect([calls,result.outcomes.length,result.outcomes[0]!.status,result.outcomes[0]!.candidateDrafts.length,result.conditionalFacts.map(f=>f.kind)]).toEqual([1,1,"success",0,["esearch-pmid-set"]]);});
 test("fixture-owned executeMaterialized parses ESummary ELink and PMC without production partition construction",async()=>{const summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json"),pmc=createPmcAdapter().buildFetchPartition({identifierKind:"pmcid",identifier:"PMC9"});expect((await invoke(summary,esummary(["9"]))).outcomes[0]!.status).toBe("success");expect((await invoke(link,elink)).conditionalFacts[0]!.kind).toBe("elink-direct-pmcid-candidates");const pmcWire=await settlement(pmc,JSON.stringify({source:"PMC",date:"20240101",key:"k",infons:{},documents:[{id:"PMC9",infons:{pmcid:"PMC9"},passages:[]}]})),pmcResult=await createPmcAdapter().executeMaterialized(opaque(pmc),options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:pmcWire})}));expect(pmcResult.outcomes[0]!.status).toBe("success");});
 test("sorts PMIDs numerically by decimal length and code units before joining",async()=>{const snapshot=createPubmedAdapter().buildSearchPartition({query:"sort",limit:5}),payload={...esearch,esearchresult:{...esearch.esearchresult,count:"5",retmax:"5",idlist:["100","10","9","2","10"]}},result=await invoke(snapshot,payload,"search"),fact=result.conditionalFacts[0];expect(fact?.kind==="esearch-pmid-set"?fact.pmids:null).toEqual(["2","9","10","100"]);expect(fact).toMatchObject({rawIdentifierCount:5,normalizedIdentifierCount:4});});
 test("emits exact discriminated ESearch PMID-set ESummary availability and ELink direct-PMCID facts",async()=>{const search=createPubmedAdapter().buildSearchPartition({query:"facts",limit:3}),summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json");expect((await invoke(search,esearch,"search")).conditionalFacts[0]).toMatchObject({kind:"esearch-pmid-set",pmids:["9","10","100"]});expect((await invoke(summary,esummary(["9"]))).conditionalFacts[0]).toMatchObject({kind:"esummary-pmid-metadata",metadata:[{pmid:"9",available:true}]});expect((await invoke(link,elink)).conditionalFacts[0]).toMatchObject({kind:"elink-direct-pmcid-candidates",pmid:"9",pmcids:["PMC9","PMC10","PMC100"]});});
 test("rejects excess forged oversized unsorted duplicate count-mismatched and payload-mismatched conditional facts before indexes",async()=>{const snapshot=createPubmedAdapter().buildSearchPartition({query:"facts",limit:3}),result=await invoke(snapshot,esearch,"search"),base=result.conditionalFacts[0]!,cases=[{...base,pmids:["10","9"]},{...base,pmids:["9","9"]},{...base,normalizedIdentifierCount:99},{...base,responsePayloadSha256:"0".repeat(64)},{...base,extra:true}];for(const [index,fact] of cases.entries())expect(code(()=>createProviderExecutionResultInternal({outcomes:result.outcomes,conditionalFacts:[fact] as never,options}))).toBe(index===2?"provider.response-too-large":"provider.invalid-input");});
 test("deep-freezes fact snapshots with no raw payload alias side channel or JSON reparse",async()=>{const adapter=createPubmedAdapter(),snapshot=adapter.buildSearchPartition({query:"freeze",limit:3}),wire=await settlement(snapshot,JSON.stringify(esearch)),partition=opaque(snapshot),parse=vi.spyOn(JSON,"parse"),result=await adapter.search(partition,options,createProviderPartitionExecutor({execute:async()=>({status:"settled",settlement:wire})})),fact=result.conditionalFacts[0]!;expect(Object.isFrozen(fact)&&Object.isFrozen((fact as {pmids:unknown}).pmids)).toBe(true);expect("payload" in fact||"root" in fact).toBe(false);expect(parse.mock.calls.some(call=>call[0]===JSON.stringify(esearch))).toBe(false);parse.mockRestore();});
 test("emits bounded empty ESearch PMID facts without constructing or executing ESummary",async()=>{const adapter=createPubmedAdapter(),snapshot=adapter.buildSearchPartition({query:"empty",limit:1}),wire=await settlement(snapshot,JSON.stringify({...esearch,esearchresult:{...esearch.esearchresult,count:"0",retmax:"0",idlist:[]}}));let calls=0;const result=await adapter.search(opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>{calls++;return{status:"settled",settlement:wire};}}));expect([calls,result.conditionalFacts[0]]).toEqual([1,expect.objectContaining({rawIdentifierCount:0,normalizedIdentifierCount:0,pmids:[]})]);});
 test("emits bounded ESummary and ELink facts without constructing future partitions",async()=>{const summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json");for(const [snapshot,payload] of [[summary,esummary(["9"])],[link,elink]] as const){let calls=0;const adapter=createPubmedAdapter(),wire=await settlement(snapshot,JSON.stringify(payload)),result=await adapter.executeMaterialized(opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>{calls++;return{status:"settled",settlement:wire};}}));expect([calls,result.outcomes.length,result.conditionalFacts.length]).toEqual([1,1,1]);}});
 test("parses ESummary venue and date precedence types article IDs and affected-ID failure exactly",async()=>{const snapshot=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),result=await invoke(snapshot,esummary(["9"])),draft=result.outcomes[0]!.candidateDrafts[0]!;expect(draft).toMatchObject({providerRecordId:"9",identifiers:{doi:"10.5555/synthetic.9",pmid:"9",pmcid:"PMC9"},containerTitle:"Synthetic Journal",published:{date:"2024-02-29",precision:"day"},publicationType:"journal-article",accessLevel:"metadata-only",canonicalUrl:"https://pubmed.ncbi.nlm.nih.gov/9/"});const dates:[Record<string,unknown>,Readonly<{date:string|null;precision:string}>][]=[[{sortpubdate:"2024/02/29 trailing",epubdate:"2020",pubdate:"2019"},{date:"2024-02-29",precision:"day"}],[{sortpubdate:"bad",epubdate:"2023"},{date:"2023",precision:"year"}],[{sortpubdate:"bad",epubdate:"2023 Jan"},{date:"2023-01",precision:"month"}],[{sortpubdate:"bad",epubdate:"2023 Jan 2"},{date:"2023-01-02",precision:"day"}],[{sortpubdate:"bad",epubdate:"bad",pubdate:"2022"},{date:"2022",precision:"year"}],[{sortpubdate:"bad",epubdate:"bad",pubdate:"2022 Dec"},{date:"2022-12",precision:"month"}],[{sortpubdate:"2023/02/29",epubdate:"2023 Feb 29",pubdate:"2020 Feb 29"},{date:"2020-02-29",precision:"day"}],[{sortpubdate:"2024/04/31",epubdate:"2023 Feb 29",pubdate:"2022 Dec 2"},{date:"2022-12-02",precision:"day"}],[{sortpubdate:"0000/01/01",epubdate:"10000 Jan",pubdate:""},{date:null,precision:"unknown"}],[{},{date:null,precision:"unknown"}]];for(const [fields,published] of dates){const parsed=await invoke(snapshot,{header,result:{uids:["9"],"9":summaryRecord("9",{sortpubdate:null,epubdate:null,pubdate:null,...fields})}});expect(parsed.outcomes[0]!.candidateDrafts[0]!.published,JSON.stringify(fields)).toEqual(published);}for(const [doctype,expected] of [["Review","review"],["Dataset","dataset"],["Journal Article","journal-article"],["Book","other"]]){const parsed=await invoke(snapshot,{header,result:{uids:["9"],"9":summaryRecord("9",{doctype,fulljournalname:"",source:"Fallback",sortpubdate:"bad",epubdate:"2023 Jan 02"})}});expect(parsed.outcomes[0]!.candidateDrafts[0]).toMatchObject({containerTitle:"Fallback",published:{date:"2023-01-02",precision:"day"},publicationType:expected});}for(const invalid of [{fulljournalname:1},{source:[]},{doctype:{}},{title:1}])expect((await invoke(snapshot,{header,result:{uids:["9"],"9":summaryRecord("9",invalid)}})).outcomes[0]!.status).toBe("failed");const unavailable=await invoke(snapshot,{header,result:{uids:["9"],"9":{uid:"9",error:"not found"}}});expect([unavailable.outcomes[0]!.candidateDrafts.length,unavailable.conditionalFacts[0]]).toEqual([0,expect.objectContaining({metadata:[{pmid:"9",available:false}]})]);});
 test("accepts only direct pubmed_pmc ELink relations with exact requested PMID",async()=>{const snapshot=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json");expect((await invoke(snapshot,elink)).conditionalFacts[0]).toMatchObject({pmcids:["PMC9","PMC10","PMC100"]});for(const payload of [{header,linksets:[{ids:["10"],linksetdbs:[]}]},{header,linksets:[{ids:["9"],linksetdbs:[{dbto:"pmc",linkname:"pubmed_pmc_refs",links:["8"]}]}]}]){const result=await invoke(snapshot,payload);if(payload===undefined)throw new Error();expect(result.outcomes[0]!.status,JSON.stringify(payload)).toBe(payload.linksets[0]!.ids[0]==="9"?"success":"failed");if(result.outcomes[0]!.status==="success")expect(result.conditionalFacts[0]).toMatchObject({pmcids:[]});}});
 test("returns ESummary success drafts and facts without executing ELink",async()=>{const adapter=createPubmedAdapter(),snapshot=adapter.buildFetchPartition({identifierKind:"pmid",identifier:"9"}),wire=await settlement(snapshot,JSON.stringify(esummary(["9"])));let calls=0;const result=await adapter.fetch(opaque(snapshot),options,createProviderPartitionExecutor({execute:async()=>{calls++;return{status:"settled",settlement:wire};}}));expect([calls,result.outcomes[0]!.candidateDrafts.length,result.conditionalFacts[0]!.kind]).toEqual([1,1,"esummary-pmid-metadata"]);});
 test("parses ELink failure independently without mutating prior ESummary result",async()=>{const summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),prior=await invoke(summary,esummary(["9"])),link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json"),failed=await invoke(link,{bad:true});expect([prior.outcomes[0]!.candidateDrafts.length,failed.outcomes[0]!.status,failed.conditionalFacts.length]).toEqual([1,"failed",0]);});
 test("covers each ESummary ELink PMC parser outcome independently through bounded fixture partitions",async()=>{const summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"}),link=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json");for(const [snapshot,payload] of [[summary,esummary(["9"])],[link,elink]] as const)expect((await invoke(snapshot,payload)).outcomes[0]!.status).toBe("success");for(const [snapshot,payload] of [[summary,{}],[link,{}]] as const)expect((await invoke(snapshot,payload)).outcomes[0]!.status).toBe("failed");});
 test("normalizes every PMCID and selects the smallest numeric link without refs fallback",async()=>{const snapshot=fixture("pubmed","fetch","pubmed-elink",{kind:"pmid-link",pmid:"9"},"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=9&retmode=json"),result=await invoke(snapshot,{header,linksets:[{ids:["9"],linksetdbs:[{dbto:"pmc",linkname:"pubmed_pmc",links:["100","0009","10"]},{dbto:"pmc",linkname:"pubmed_pmc_refs",links:["1"]}]}]});expect(result.conditionalFacts[0]).toMatchObject({pmcids:["PMC9","PMC10","PMC100"]});});
 test("rejects malformed duplicate missing excess and mismatched PubMed IDs",async()=>{const summary=createPubmedAdapter().buildFetchPartition({identifierKind:"pmid",identifier:"9"});for(const payload of [{header,result:{uids:["9","9"],"9":summaryRecord("9")}},{header,result:{uids:[]}},{header,result:{uids:["9","10"],"9":summaryRecord("9"),"10":summaryRecord("10")}},{header,result:{uids:["9"],"9":summaryRecord("10")}},{header,result:{uids:["9"],"9":summaryRecord("9",{articleids:[{idtype:"pubmed",value:"10"}]})}}])expect((await invoke(summary,payload)).outcomes[0]!.status,JSON.stringify(payload)).toBe("failed");const search=createPubmedAdapter().buildSearchPartition({query:"bad",limit:2});for(const ids of [["bad"],["9",{}]])expect((await invoke(search,{...esearch,esearchresult:{...esearch.esearchresult,idlist:ids,retmax:"2"}},"search")).outcomes[0]!.status).toBe("failed");const adapter=createPubmedAdapter(),partition=opaque(search),trap={count:0},proxy=new Proxy({}, {get(){trap.count++;throw new Error("SECRET get");},getOwnPropertyDescriptor(){trap.count++;throw new Error("SECRET descriptor");},ownKeys(){trap.count++;throw new Error("SECRET keys");},getPrototypeOf(){trap.count++;throw new Error("SECRET prototype");}}),accessorTrap={count:0},accessor=Object.defineProperty({},"partitionKey",{enumerable:true,get(){accessorTrap.count++;throw new Error("SECRET getter");}});for(const hostile of [null,1,"SECRET primitive",proxy,accessor])for(const transportResult of [{status:"settled",settlement:hostile},{status:"blocked",code:"sink.blocked",settlement:hostile}]){const parse=vi.spyOn(JSON,"parse");await expect(adapter.search(partition,options,createProviderPartitionExecutor({execute:async()=>(transportResult as never)}))).rejects.toMatchObject({code:"provider.invalid-capability",message:"Provider adapter rejected (provider.invalid-capability)"});expect(parse.mock.calls.length).toBeGreaterThan(0);expect(JSON.stringify(parse.mock.calls)).not.toMatch(/SECRET|"header"|"documents"|"status":"ok"/u);parse.mockRestore();}expect([trap.count,accessorTrap.count]).toEqual([0,0]);});
});
