import {describe,expect,test} from "vitest";
import {createBlockedTraceSettlementInternal,lookupProviderRequestPartitionInternal,normalizeAcquisitionOptions,type ProviderRequestPartitionInternal,type TransportFailureCode,type TransportSettlement} from "../../src/acquisition/contracts.js";
import type {ProviderPartitionTransportResult} from "../../src/acquisition/providers/shared.js";
import {createCrossrefAdapter} from "../../src/acquisition/providers/crossref.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {createPubmedAdapter} from "../../src/acquisition/providers/pubmed.js";
import {createEncodedTransportOutcomeInternal} from "../../src/acquisition/transport.js";
import {AcademicAcquisitionError,createAcquisitionPlanningCapabilitiesInternal,listInvocationConcretePartitionsInternal,planAcquisitionInvocation} from "../../src/acquisition/planner-internal.js";
import {createInvocationExecutorCapabilitiesInternal,createInvocationSchedulerCapabilitiesInternal,executeInvocationPlanInternal,InvocationExecutionErrorInternal,type PhysicalRequestOwnerInternal} from "../../src/acquisition/scheduler-internal.js";

const AT="2025-01-02T03:04:05.000Z";
const options=normalizeAcquisitionOptions({maxConcurrency:2,maxPerOriginConcurrency:1,shutdownGraceMs:10}),capabilities=createAcquisitionPlanningCapabilitiesInternal({crossref:createCrossrefAdapter(),openalex:createOpenAlexAdapter(),pubmed:createPubmedAdapter(),pmc:createPmcAdapter()});
const plan=(providers:("crossref"|"openalex"|"pubmed")[]=["crossref"],queries=["x"])=>planAcquisitionInvocation({operation:"search",raw:{queries,providers}},options,capabilities);
const key=(item:{partition:ProviderRequestPartitionInternal})=>lookupProviderRequestPartitionInternal(item.partition).partitionKeySha256;
function blocked(partition:ProviderRequestPartitionInternal){const snapshot=lookupProviderRequestPartitionInternal(partition);return Object.freeze({status:"blocked" as const,code:"sink.blocked" as const,settlement:createBlockedTraceSettlementInternal({requestedUrl:snapshot.url,retrievedAt:AT,limits:{maxCanonicalUrlBytes:16_384,maxRedirects:5}})}) as ProviderPartitionTransportResult;}
function settledFailure(partition:ProviderRequestPartitionInternal,code:TransportFailureCode){const snapshot=lookupProviderRequestPartitionInternal(partition),cancelled=code==="transport.cancelled"||code==="transport.deadline-exceeded",settlement={schemaVersion:1 as const,partitionKey:snapshot.partitionKey,partitionKeySha256:snapshot.partitionKeySha256,provider:snapshot.provider,operation:snapshot.operation,endpointClass:snapshot.endpointClass,normalizedOrigin:new URL(snapshot.url).origin,requestedUrl:snapshot.url,finalUrl:null,redirectWitnesses:[],httpStatus:null,encodedBytes:0,decodedBytes:0,responsePayloadSha256:null,responseHeaders:{contentType:null,retryAfter:null,etag:null,lastModified:null},responseHeadersSha256:null,connectedPeer:null,startedAt:AT,settledAt:AT,outcome:cancelled?"cancelled" as const:"failure" as const,failureCode:code,payloadUtf8:null} as TransportSettlement;const outcome=createEncodedTransportOutcomeInternal({outcome:cancelled?"cancelled":"failure",settlement} as never,options.transport);if(outcome.outcome==="encoded")throw new Error("failure expected");return Object.freeze({status:"settled" as const,settlement:outcome.settlement});}
function fakeScheduler(config:Readonly<{clockThrows?:boolean;timerSetThrows?:boolean;timerClearThrows?:boolean}>={}){let now=0,next=1;const callbacks=new Map<number,()=>void>(),cleared:number[]=[];return{capability:createInvocationSchedulerCapabilitiesInternal({monotonicNow:()=>{if(config.clockThrows)throw new Error("clock secret");return now;},setTimeout:(callback)=>{if(config.timerSetThrows)throw new Error("timer secret");const id=next++;callbacks.set(id,callback);return id;},clearTimeout:(id)=>{if(config.timerClearThrows)throw new Error("clear secret");cleared.push(id as number);callbacks.delete(id as number);}}),advance(ms:number){now+=ms;for(const [id,callback] of [...callbacks]){callbacks.delete(id);callback();}},callbacks,cleared,setNow(value:number){now=value;}};}
function executor(overrides:Partial<{dispatch:(partition:ProviderRequestPartitionInternal,owner:PhysicalRequestOwnerInternal)=>PhysicalRequestOwnerInternal;abort:(owner:PhysicalRequestOwnerInternal,reason:string)=>void;close:(owner:PhysicalRequestOwnerInternal)=>Promise<void>;forceClose:(owner:PhysicalRequestOwnerInternal)=>void}>={}){return createInvocationExecutorCapabilitiesInternal({dispatch:overrides.dispatch??((_partition:ProviderRequestPartitionInternal,owner:PhysicalRequestOwnerInternal)=>owner),abort:overrides.abort??(()=>{}),close:overrides.close??(async()=>{}),forceClose:overrides.forceClose??(()=>{})} as never);}

async function flush(){await Promise.resolve();await Promise.resolve();}
function promiseSpeciesBoundaryRegression():readonly Promise<void>[]{const subclass=new(class HostilePromise extends Promise<void>{})(resolve=>resolve(undefined)),own=Promise.resolve();Object.defineProperty(own,"constructor",{get(){throw new Error("species secret");}});return[subclass,own];}

describe("bounded invocation scheduler",()=>{
 test("brands one-consumer authenticated acquisition execution plan executor and frozen invocation scheduler descriptors",async()=>{const scheduler=fakeScheduler(),empty=plan([]),execution=executeInvocationPlanInternal(empty,executor(),scheduler.capability);expect([execution.capabilityKind,Object.isFrozen(execution),scheduler.capability.capabilityKind]).toEqual(["invocation-execution",true,"invocation-scheduler-capabilities"]);execution.seal();await expect(execution.completion).resolves.toEqual([]);expect(()=>executeInvocationPlanInternal(empty,executor(),fakeScheduler().capability)).toThrowError(expect.objectContaining({code:"invocation.invalid-plan"}));await execution.close();expect(()=>listInvocationConcretePartitionsInternal(empty)).toThrowError(expect.objectContaining({code:"acquisition.invalid-capability"}));});
 test("rejects forged timer handles nonmonotonic clocks and invalid scheduler callback descriptors before dispatch",()=>{expect(()=>createInvocationSchedulerCapabilitiesInternal({monotonicNow:1 as never,setTimeout:()=>1,clearTimeout:()=>{}})).toThrow();const fake=fakeScheduler();expect(fake.capability.monotonicNow()).toBe(0);fake.setNow(-1);expect(()=>fake.capability.monotonicNow()).toThrow();expect(()=>fake.capability.clearTimeout(Object.freeze({capabilityKind:"invocation-scheduler-timer"}) as never)).toThrow();});
 test("owns one physical request per key and rejects wrong-owner or double settlement",async()=>{for(const variant of ["mutable","clone","raw-mutable","raw-clone","foreign","twice"] as const){const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let ownerResult:Promise<unknown>|null=null;const cap=executor({dispatch:(partition,owner)=>{ownerResult=owner.result;const authentic=blocked(partition);if(variant==="mutable")owner.settle(Object.freeze({status:"blocked",code:"sink.blocked",settlement:{...authentic.settlement}}) as never);else if(variant==="clone")owner.settle(Object.freeze({...authentic,settlement:Object.freeze({...authentic.settlement})}) as never);else if(variant==="raw-mutable"||variant==="raw-clone"){const raw=settledFailure(partition,"transport.tls-failed");owner.settle(Object.freeze({...raw,settlement:variant==="raw-clone"?Object.freeze({...raw.settlement}):{...raw.settlement}}) as never);}else if(variant==="foreign")owner.settle(blocked(listInvocationConcretePartitionsInternal(plan(["crossref"],["foreign"]))[0]!.partition));else{owner.settle(authentic);owner.settle(authentic);}return owner;}}),execution=executeInvocationPlanInternal(p,cap,fake.capability),waiter=execution.attach(key(part));execution.releaseConcrete(key(part));execution.seal();await expect(execution.completion).rejects.toMatchObject({code:variant==="foreign"?"invocation.duplicate-owner":"invocation.settle-twice"});if(variant==="twice"){await expect(ownerResult!).resolves.toMatchObject({status:"blocked"});await expect(waiter.result).resolves.toMatchObject({status:"blocked"});}else{await expect(ownerResult!).rejects.toBeInstanceOf(InvocationExecutionErrorInternal);await expect(waiter.result).rejects.toBeInstanceOf(InvocationExecutionErrorInternal);}fake.advance(options.shutdownGraceMs);await execution.close();}const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let provisional!:PhysicalRequestOwnerInternal;const execution=executeInvocationPlanInternal(p,executor({dispatch:(_partition,owner)=>{provisional=owner;void owner.result.catch(()=>{});return Object.freeze({...owner}) as PhysicalRequestOwnerInternal;}}),fake.capability),waiter=execution.attach(key(part)),completion=expect(execution.completion).rejects.toMatchObject({code:"invocation.duplicate-owner"});execution.releaseConcrete(key(part));await completion;await expect(provisional.result).rejects.toMatchObject({code:"invocation.duplicate-owner"});await expect(waiter.result).rejects.toMatchObject({code:"invocation.duplicate-owner"});});
 test("races hanging close against fake monotonic grace clears timer force closes open owners then detaches waiters on dispatch throw",async()=>{const fake=fakeScheduler(),p=plan(["crossref","openalex"]),parts=listInvocationConcretePartitionsInternal(p);let aborts=0,closes=0,forces=0,firstOwner:PhysicalRequestOwnerInternal|null=null;const cap=executor({dispatch:(partition,owner)=>{if(!firstOwner){firstOwner=owner;owner.settle(blocked(partition));return owner;}throw new Error("dispatch secret");},abort:()=>{aborts++;},close:async()=>{closes++;await new Promise(()=>{});},forceClose:()=>{forces++;}}),execution=executeInvocationPlanInternal(p,cap,fake.capability),waiter=execution.attach(key(parts[1]!));for(const part of parts)execution.releaseConcrete(key(part));await flush();expect([aborts,closes,forces]).toEqual([2,2,0]);fake.advance(options.shutdownGraceMs);await expect(execution.completion).rejects.toMatchObject({code:"acquisition.internal-contract"});await expect(waiter.result).rejects.toMatchObject({code:"acquisition.internal-contract"});expect([forces,fake.cleared.length]).toEqual([2,1]);expect(execution.cleanupDiagnostics().filter(x=>x.code==="cleanup.grace-expired")).toHaveLength(2);expect(()=>lookupProviderRequestPartitionInternal(parts[0]!.partition)).toThrow();for(const raw of promiseSpeciesBoundaryRegression()){const hostileFake=fakeScheduler(),hostilePlan=plan(),hostilePart=listInvocationConcretePartitionsInternal(hostilePlan)[0]!,hostileExecution=executeInvocationPlanInternal(hostilePlan,executor({dispatch:()=>{throw new Error("dispatch secret");},close:()=>raw as Promise<void>}),hostileFake.capability),rejection=expect(hostileExecution.completion).rejects.toMatchObject({code:"acquisition.internal-contract"});hostileExecution.releaseConcrete(key(hostilePart));await rejection;await flush();expect(hostileExecution.cleanupDiagnostics()).toContainEqual({ownerOrdinal:0,code:"cleanup.close-rejected"});}});
 test("quarantines cleared raw timer and post force-close settlement callbacks and bytes without replacing internal-contract",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let ownerRef!:PhysicalRequestOwnerInternal;const cap=executor({dispatch:(_partition,owner)=>{ownerRef=owner;throw new Error("secret");},close:async()=>{await new Promise(()=>{});}}),execution=executeInvocationPlanInternal(p,cap,fake.capability),lateSettlement=blocked(part.partition),completionAssertion=expect(execution.completion).rejects.toMatchObject({code:"acquisition.internal-contract"});execution.releaseConcrete(key(part));await flush();const late=[...fake.callbacks.values()][0]!;fake.advance(options.shutdownGraceMs);await flush();ownerRef.settle(lateSettlement);late();await completionAssertion;expect(execution.cleanupDiagnostics()).toContainEqual({ownerOrdinal:0,code:"cleanup.late-callback"});});
 test("seals materialization resolves ordinal completion and closes idempotently",async()=>{const fake=fakeScheduler(),p=plan(),parts=listInvocationConcretePartitionsInternal(p);let closes=0;const cap=executor({dispatch:(partition,owner)=>{owner.settle(blocked(partition));return owner;},close:async()=>{closes++;}}),execution=executeInvocationPlanInternal(p,cap,fake.capability);expect(()=>execution.attach("f".repeat(64))).toThrowError(expect.objectContaining({code:"invocation.invalid-plan"}));for(const part of parts)execution.releaseConcrete(key(part));execution.seal();expect(await execution.completion).toHaveLength(parts.length);await flush();expect(closes).toBe(parts.length);await execution.close();await execution.close();for(const part of parts)expect(()=>lookupProviderRequestPartitionInternal(part.partition)).toThrow();});
 test("schedules FIFO total and per-origin concurrency without exceeding ceilings",async()=>{const fake=fakeScheduler(),p=plan(["crossref","openalex","pubmed"]),parts=listInvocationConcretePartitionsInternal(p),active=new Map<string,{owner:PhysicalRequestOwnerInternal;partition:ProviderRequestPartitionInternal}>(),order:string[]=[];const cap=executor({dispatch:(partition,owner)=>{const partitionKey=lookupProviderRequestPartitionInternal(partition).partitionKeySha256;order.push(partitionKey);active.set(partitionKey,{owner,partition});return owner;}}),execution=executeInvocationPlanInternal(p,cap,fake.capability);for(const part of parts)execution.releaseConcrete(key(part));expect(active.size).toBe(2);const first=active.get(key(parts[0]!))!;first.owner.settle(blocked(first.partition));active.delete(key(parts[0]!));await flush();expect(order).toEqual(parts.map(item=>key(item)));for(const current of active.values())current.owner.settle(blocked(current.partition));execution.seal();await expect(execution.completion).resolves.toHaveLength(3);});
 test("coalesces identical partitions once within invocation and never across invocations",async()=>{let calls=0;for(let invocation=0;invocation<2;invocation++){const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!,cap=executor({dispatch:(partition,owner)=>{calls++;owner.settle(blocked(partition));return owner;}}),execution=executeInvocationPlanInternal(p,cap,fake.capability);execution.releaseConcrete(key(part));execution.releaseConcrete(key(part));execution.seal();await execution.completion;}expect(calls).toBe(2);});
 test("attaches and idempotently detaches waiter without cancelling shared owner or siblings",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let ownerRef!:PhysicalRequestOwnerInternal,aborts=0;const execution=executeInvocationPlanInternal(p,executor({dispatch:(_partition,owner)=>{ownerRef=owner;return owner;},abort:()=>{aborts++;}}),fake.capability),first=execution.attach(key(part)),second=execution.attach(key(part));execution.releaseConcrete(key(part));first.detach();first.detach();ownerRef.settle(blocked(part.partition));await expect(second.result).resolves.toStrictEqual(blocked(part.partition));expect(aborts).toBe(0);});
 test("aborts queued active work on root cancel close and security stop",async()=>{const rootFake=fakeScheduler(),rootPlan=plan(),rootPart=listInvocationConcretePartitionsInternal(rootPlan)[0]!,controller=new AbortController();let rootAborts=0;const rootExecution=executeInvocationPlanInternal(rootPlan,executor({abort:()=>{rootAborts++;}}),rootFake.capability,controller.signal),waiter=rootExecution.attach(key(rootPart));rootExecution.releaseConcrete(key(rootPart));controller.abort();await expect(rootExecution.completion).rejects.toMatchObject({code:"invocation.cancelled"});await expect(waiter.result).rejects.toMatchObject({code:"invocation.cancelled"});rootFake.advance(options.shutdownGraceMs);expect(rootAborts).toBe(1);
  const security=["network.dns-unsafe","transport.tls-failed","transport.peer-unavailable","transport.peer-mismatch","transport.redirect-invalid","transport.too-many-redirects","transport.too-many-headers","transport.headers-too-large","transport.framing-invalid","transport.protocol-invalid","transport.encoded-too-large","transport.too-many-encoding-layers","transport.unsupported-encoding","transport.decompression-failed","transport.decompression-ratio","transport.decoded-too-large","transport.invalid-utf8"] as const;for(const code of security){const fake=fakeScheduler(),p=plan(["crossref","openalex"]),parts=listInvocationConcretePartitionsInternal(p);let siblingAborts=0,firstOwner:PhysicalRequestOwnerInternal|null=null,firstPartition:ProviderRequestPartitionInternal|null=null;const execution=executeInvocationPlanInternal(p,executor({dispatch:(partition,owner)=>{void owner.result.catch(()=>{});if(!firstOwner){firstOwner=owner;firstPartition=partition;}return owner;},abort:(_owner,reason)=>{if(reason==="security-stop")siblingAborts++;}}),fake.capability);for(const part of parts)execution.releaseConcrete(key(part));firstOwner!.settle(settledFailure(firstPartition!,code));execution.seal();await expect(execution.completion).resolves.toMatchObject([{status:"settled"}]);expect(siblingAborts).toBe(1);expect(()=>execution.releaseConcrete(key(parts[1]!))).toThrow();await execution.close();}
  for(const code of ["network.dns-empty","network.dns-nxdomain","network.dns-temporary","transport.connect-timeout","transport.connect-failed","transport.cancelled","transport.deadline-exceeded","transport.json-root-invalid","transport.http-retryable","transport.http-terminal"] as const){const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let aborts=0;const execution=executeInvocationPlanInternal(p,executor({dispatch:(partition,owner)=>{owner.settle(settledFailure(partition,code));return owner;},abort:()=>{aborts++;}}),fake.capability);execution.releaseConcrete(key(part));execution.seal();await expect(execution.completion).resolves.toHaveLength(1);expect(aborts).toBe(0);await execution.close();}});
});
