import {describe,expect,test} from "vitest";
import {lookupProviderRequestPartitionInternal,normalizeAcquisitionOptions,type ProviderRequestPartitionInternal} from "../../src/acquisition/contracts.js";
import {createCrossrefAdapter} from "../../src/acquisition/providers/crossref.js";
import {createOpenAlexAdapter} from "../../src/acquisition/providers/openalex.js";
import {createPubmedAdapter} from "../../src/acquisition/providers/pubmed.js";
import {createPmcAdapter} from "../../src/acquisition/providers/pmc.js";
import {createAcquisitionPlanningCapabilitiesInternal,planAcquisitionInvocation,listInvocationConcretePartitionsInternal,AcademicAcquisitionError} from "../../src/acquisition/planner-internal.js";
import {createInvocationSchedulerCapabilitiesInternal,createInvocationExecutorCapabilitiesInternal,executeInvocationPlanInternal,InvocationExecutionErrorInternal} from "../../src/acquisition/scheduler-internal.js";

const options=normalizeAcquisitionOptions({maxConcurrency:2,maxPerOriginConcurrency:1}),capabilities=createAcquisitionPlanningCapabilitiesInternal({crossref:createCrossrefAdapter(),openalex:createOpenAlexAdapter(),pubmed:createPubmedAdapter(),pmc:createPmcAdapter()});
const plan=(providers:("crossref"|"openalex"|"pubmed")[]=["crossref"])=>planAcquisitionInvocation({operation:"search",raw:{queries:["x"],providers}},options,capabilities);
function fakeScheduler(){let now=0,next=1;const callbacks=new Map<number,()=>void>(),cleared:number[]=[];return{capability:createInvocationSchedulerCapabilitiesInternal({monotonicNow:()=>now,setTimeout:(callback)=>{const id=next++;callbacks.set(id,callback);return id;},clearTimeout:(id)=>{cleared.push(id as number);callbacks.delete(id as number);}}),advance(ms:number){now+=ms;for(const [id,callback] of [...callbacks]){callbacks.delete(id);callback();}},callbacks,cleared,setNow(value:number){now=value;}};}
const key=(item:{partition:ProviderRequestPartitionInternal})=>lookupProviderRequestPartitionInternal(item.partition).partitionKeySha256;
const settled=Object.freeze({status:"blocked",code:"sink.blocked",settlement:Object.freeze({outcome:"blocked",code:"sink-blocked"})}) as never;

describe("bounded invocation scheduler",()=>{
 test("brands one-consumer authenticated acquisition execution plan executor and frozen invocation scheduler descriptors",()=>{const scheduler=fakeScheduler(),executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>owner,abort:()=>{},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(plan([]),executor,scheduler.capability);expect([execution.capabilityKind,Object.isFrozen(execution),scheduler.capability.capabilityKind]).toEqual(["invocation-execution",true,"invocation-scheduler-capabilities"]);expect(()=>executeInvocationPlanInternal(plan([]),executor,scheduler.capability)).toThrowError(expect.objectContaining({code:"invocation.invalid-capability"}));});
 test("rejects forged timer handles nonmonotonic clocks and invalid scheduler callback descriptors before dispatch",()=>{expect(()=>createInvocationSchedulerCapabilitiesInternal({monotonicNow:1 as never,setTimeout:()=>1,clearTimeout:()=>{}})).toThrow();const fake=fakeScheduler();expect(fake.capability.monotonicNow()).toBe(0);fake.setNow(-1);expect(()=>fake.capability.monotonicNow()).toThrow();expect(()=>fake.capability.clearTimeout(Object.freeze({capabilityKind:"invocation-scheduler-timer"}) as never)).toThrow();});
 test("owns one physical request per key and rejects wrong-owner or double settlement",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!,owners:unknown[]=[];const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>{owners.push(owner);owner.settle(settled);owner.settle(settled);return owner;},abort:()=>{},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability);execution.releaseConcrete(key(part));execution.seal();await expect(execution.completion).rejects.toBeInstanceOf(InvocationExecutionErrorInternal);expect(owners).toHaveLength(1);});
 test("races hanging close against fake monotonic grace clears timer force closes open owners then detaches waiters on dispatch throw",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let aborts=0,closes=0,forces=0;const executor=createInvocationExecutorCapabilitiesInternal({dispatch:()=>{throw new Error("secret");},abort:()=>{aborts++;},close:async()=>{closes++;await new Promise(()=>{});},forceClose:()=>{forces++;}}),execution=executeInvocationPlanInternal(p,executor,fake.capability),waiter=execution.attach(key(part));execution.releaseConcrete(key(part));await Promise.resolve();expect([aborts,closes,forces]).toEqual([1,1,0]);fake.advance(options.shutdownGraceMs);await expect(execution.completion).rejects.toMatchObject({code:"acquisition.internal-contract"});await expect(waiter.result).rejects.toMatchObject({code:"acquisition.internal-contract"});expect([forces,fake.cleared.length]).toEqual([1,1]);});
 test("quarantines cleared raw timer and post force-close settlement callbacks and bytes without replacing internal-contract",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let ownerRef:any;const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>{ownerRef=owner;throw new Error("secret");},abort:()=>{},close:async()=>{await new Promise(()=>{});},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability);execution.releaseConcrete(key(part));await Promise.resolve();fake.advance(options.shutdownGraceMs);ownerRef.settle(settled);await expect(execution.completion).rejects.toMatchObject({code:"acquisition.internal-contract"});});
 test("seals materialization resolves ordinal completion and closes idempotently",async()=>{const fake=fakeScheduler(),p=plan(),parts=listInvocationConcretePartitionsInternal(p);const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>{owner.settle(settled);return owner;},abort:()=>{},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability);for(const part of parts)execution.releaseConcrete(key(part));execution.seal();expect(await execution.completion).toHaveLength(parts.length);await execution.close();await execution.close();});
 test("schedules FIFO total and per-origin concurrency without exceeding ceilings",async()=>{const fake=fakeScheduler(),p=plan(["crossref","openalex","pubmed"]),parts=listInvocationConcretePartitionsInternal(p),active=new Map<string,any>(),order:string[]=[];const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(partition,owner)=>{const partitionKey=key(parts.find(x=>x.partition===partition)!);order.push(partitionKey);active.set(partitionKey,owner);return owner;},abort:()=>{},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability);for(const part of parts)execution.releaseConcrete(key(part));expect(active.size).toBe(2);active.get(key(parts[0]!))!.settle(settled);active.delete(key(parts[0]!));await Promise.resolve();expect(order).toEqual(parts.map(x=>key(x)));for(const owner of active.values())owner.settle(settled);execution.seal();});
 test("coalesces identical partitions once within invocation and never across invocations",()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let calls=0;const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>{calls++;return owner;},abort:()=>{},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability);execution.releaseConcrete(key(part));execution.releaseConcrete(key(part));expect(calls).toBe(1);});
 test("attaches and idempotently detaches waiter without cancelling shared owner or siblings",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let ownerRef:any,aborts=0;const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>{ownerRef=owner;return owner;},abort:()=>{aborts++;},close:async()=>{},forceClose:()=>{}}),execution=executeInvocationPlanInternal(p,executor,fake.capability),first=execution.attach(key(part)),second=execution.attach(key(part));execution.releaseConcrete(key(part));first.detach();first.detach();ownerRef.settle(settled);await expect(second.result).resolves.toStrictEqual(settled);expect(aborts).toBe(0);});
 test("aborts queued active work on root cancel close and security stop",async()=>{const fake=fakeScheduler(),p=plan(),part=listInvocationConcretePartitionsInternal(p)[0]!;let aborts=0;const executor=createInvocationExecutorCapabilitiesInternal({dispatch:(_partition,owner)=>owner,abort:()=>{aborts++;},close:async()=>{},forceClose:()=>{}}),partitionKey=key(part),controller=new AbortController(),execution=executeInvocationPlanInternal(p,executor,fake.capability,controller.signal);execution.releaseConcrete(partitionKey);controller.abort();await expect(execution.completion).rejects.toMatchObject({code:"invocation.cancelled"});await execution.close();expect(aborts).toBe(1);expect(()=>execution.attach(partitionKey)).toThrowError(expect.objectContaining({code:"invocation.closed"}));});
});
