import {createBrotliDecompress,createGunzip,createInflate} from "node:zlib";
import {types as utilTypes} from "node:util";

import {SecureTransportError} from "./node-pinned-hop-internal.js";
import {createContentDecodeCapabilitiesInternal,type ContentDecodeCapabilitiesInternal} from "./json-wire-scanner-internal.js";
class DecodeFailure extends Error{readonly code:"transport.cancelled"|"transport.decompression-failed"|"transport.decompression-ratio"|"transport.decoded-too-large";constructor(code:DecodeFailure["code"]){super(`Content decode rejected (${code})`);this.name="DecodeFailure";this.code=code;}}
const ADD_EVENT=EventTarget.prototype.addEventListener;const REMOVE_EVENT=EventTarget.prototype.removeEventListener;const ABORTED_GETTER=Object.getOwnPropertyDescriptor(AbortSignal.prototype,"aborted")!.get!;
const TYPED_ARRAY_BYTE_LENGTH_GETTER=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(Uint8Array.prototype) as object,"byteLength")!.get!;
function fail():never{throw new SecureTransportError("transport.invalid-capability");}
function typedLength(value:unknown):number|null{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||Object.getPrototypeOf(value)!==Uint8Array.prototype)return null;try{const length=TYPED_ARRAY_BYTE_LENGTH_GETTER.call(value) as number;return Number.isSafeInteger(length)&&length>=0?length:null;}catch{return null;}}
function checkedAdd(left:number,right:number):number{const value=left+right;if(!Number.isSafeInteger(value)||value<left)throw new DecodeFailure("transport.decoded-too-large");return value;}
function nodeDecodeContentLayer(encoding:"gzip"|"deflate"|"br",input:Uint8Array,maxOutputBytes:number,decodedOutputCap:number,ratioOutputCap:number,signal:AbortSignal):Promise<Uint8Array>{
  if(!Number.isSafeInteger(maxOutputBytes)||maxOutputBytes<0||!Number.isSafeInteger(decodedOutputCap)||decodedOutputCap<maxOutputBytes||!Number.isSafeInteger(ratioOutputCap)||ratioOutputCap<maxOutputBytes||typedLength(input)===null)fail();
  return new Promise<Uint8Array>((resolve,reject)=>{const transform=encoding==="gzip"?createGunzip():encoding==="deflate"?createInflate():createBrotliDecompress();let gate=true;let destroyed=false;let outputBytes=0;const chunks:Uint8Array[]=[];const destroy=()=>{if(destroyed)return;destroyed=true;try{transform.destroy();}catch{/* quarantine */}};const cleanup=()=>{REMOVE_EVENT.call(signal,"abort",onAbort);transform.removeListener("data",onData);transform.removeListener("end",onEnd);};const stop=(error:DecodeFailure)=>{if(!gate)return;gate=false;cleanup();destroy();for(const chunk of chunks)chunk.fill(0);chunks.length=0;reject(error);};const onAbort=()=>stop(new DecodeFailure("transport.cancelled"));const onData=(raw:Buffer)=>{if(!gate)return;if(!Buffer.isBuffer(raw)){stop(new DecodeFailure("transport.decompression-failed"));return;}const length=raw.byteLength;let projected:number;try{projected=checkedAdd(outputBytes,length);}catch{stop(new DecodeFailure("transport.decoded-too-large"));return;}const decodedBreach=projected>decodedOutputCap;const ratioBreach=projected>ratioOutputCap;if(decodedBreach){stop(new DecodeFailure("transport.decoded-too-large"));return;}if(ratioBreach||projected>maxOutputBytes){stop(new DecodeFailure("transport.decompression-ratio"));return;}if(length>0)chunks.push(new Uint8Array(raw));outputBytes=projected;};const onEnd=()=>{if(!gate)return;gate=false;cleanup();const result=new Uint8Array(outputBytes);let offset=0;for(const chunk of chunks){result.set(chunk,offset);offset+=chunk.byteLength;chunk.fill(0);}chunks.length=0;resolve(result);};transform.on("error",()=>{if(gate)stop(new DecodeFailure("transport.decompression-failed"));});transform.on("data",onData);transform.on("end",onEnd);ADD_EVENT.call(signal,"abort",onAbort,{once:true});if(ABORTED_GETTER.call(signal)){onAbort();return;}try{transform.end(input);}catch{stop(new DecodeFailure("transport.decompression-failed"));}});
}
export function createNodeContentDecodeCapabilitiesInternal():ContentDecodeCapabilitiesInternal{return createContentDecodeCapabilitiesInternal({decodeContentLayer:nodeDecodeContentLayer});}
export {createContentDecodeCapabilitiesInternal,assertSecureJsonTransportInternal,createNodeSecureTransportCapabilitiesInternal,createSecureJsonTransport,createSecureTransportCapabilitiesInternal,openSecureTransportRequestInternal} from "./json-wire-scanner-internal.js";
export type {ContentDecodeCapabilitiesInternal,ContentDecodeOperationsDescriptorInternal,PhysicalRequestAbortReasonInternal,SecureJsonTransport,SecureTransportCapabilitiesInternal,SecureTransportRequestHandleInternal} from "./json-wire-scanner-internal.js";
