import {types as utilTypes} from "node:util";

import {canonicalJson} from "../crypto/canonical-json.js";
import {sha256Hex} from "../crypto/hash.js";
import {assertBoundedStructure} from "../storage/bounded-structure.js";
import {assertRequestDeadlineInternal,type RequestDeadlineInternal} from "./request-deadline-internal.js";

export type ProviderJsonScanErrorCode=
  |"json.invalid-syntax"|"json.invalid-escape"|"json.invalid-surrogate"|"json.invalid-number"|"json.duplicate-key"|"json.depth-exceeded"
  |"json.nodes-exceeded"|"json.keys-exceeded"|"json.object-too-large"|"json.scalar-too-large"|"json.aggregate-scalars-too-large"|"json.snapshot-mismatch"
  |"transport.json-root-invalid";
export class ProviderJsonScanError extends Error{readonly code:ProviderJsonScanErrorCode;constructor(code:ProviderJsonScanErrorCode){super(`Provider JSON rejected (${code})`);this.name="ProviderJsonScanError";this.code=code;}}
export interface ProviderJsonScanOptions{readonly maxDepth?:number;readonly maxNodes?:number;readonly maxKeys?:number;readonly maxObjectWireBytes?:number;readonly maxScalarCanonicalBytes?:number;readonly maxAggregateScalarBytes?:number;}
export interface ProviderJsonValueInternal{readonly capabilityKind:"provider-json-object-array";}
export type ProviderJsonRootSnapshotInternal=readonly unknown[]|Readonly<Record<string,unknown>>;
export interface ProviderJsonSettlementLookupInternal{readonly value:ProviderJsonValueInternal|null;readonly errorCode:ProviderJsonScanErrorCode|null;}
type Limits={maxDepth:number;maxNodes:number;maxKeys:number;maxObjectWireBytes:number;maxScalarCanonicalBytes:number;maxAggregateScalarBytes:number};
type ObjectFrame={kind:"object";state:"first-key"|"key"|"colon"|"value"|"comma";startByte:number;key:string|null;seen:Map<string,Set<string>>;entries:Array<readonly[string,string]>};
type ArrayFrame={kind:"array";state:"first-value"|"value"|"comma";entries:string[]};
type Frame=ObjectFrame|ArrayFrame;
const DEFAULTS:Limits={maxDepth:64,maxNodes:250_000,maxKeys:250_000,maxObjectWireBytes:8_388_608,maxScalarCanonicalBytes:1_048_576,maxAggregateScalarBytes:16_777_216};
const HARD:Limits={maxDepth:128,maxNodes:1_000_000,maxKeys:1_000_000,maxObjectWireBytes:33_554_432,maxScalarCanonicalBytes:4_194_304,maxAggregateScalarBytes:67_108_864};
const OPTION_KEYS=["maxDepth","maxNodes","maxKeys","maxObjectWireBytes","maxScalarCanonicalBytes","maxAggregateScalarBytes"] as const;
const roots=new WeakSet<object>();
function fail(code:ProviderJsonScanErrorCode):never{throw new ProviderJsonScanError(code);}
function options(value:ProviderJsonScanOptions|undefined):Limits{if(value===undefined)return DEFAULTS;if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)fail("json.invalid-syntax");const descriptors=Object.getOwnPropertyDescriptors(value);const keys=Reflect.ownKeys(descriptors);if(keys.some((key)=>typeof key!=="string"||!OPTION_KEYS.includes(key as typeof OPTION_KEYS[number])))fail("json.invalid-syntax");const output={...DEFAULTS};for(const key of OPTION_KEYS){const descriptor=descriptors[key];if(!descriptor)continue;if(!("value" in descriptor)||!descriptor.enumerable)fail("json.invalid-syntax");const item=descriptor.value;if(typeof item!=="number"||!Number.isSafeInteger(item)||item<1||item>HARD[key])fail("json.invalid-syntax");output[key]=item;}return output;}
function scalarDigest(kind:string,value:unknown):string{return sha256Hex(canonicalJson([kind,value]));}
function objectDigest(entries:readonly Readonly<[string,string]>[]):string{const sorted=[...entries].sort((left,right)=>left[0]<right[0]?-1:left[0]>right[0]?1:0);return sha256Hex(canonicalJson(["object",sorted]));}
function arrayDigest(entries:readonly string[]):string{return sha256Hex(canonicalJson(["array",entries]));}
function utf8BytesForCodePoint(point:number):number{return point<=0x7f?1:point<=0x7ff?2:point<=0xffff?3:4;}
function canonicalScalarBytes(value:unknown):number{try{return Buffer.byteLength(canonicalJson(value),"utf8");}catch{return Number.POSITIVE_INFINITY;}}
function graphDigest(root:unknown):string{if(root===null||typeof root!=="object")return scalarDigest(root===null?"null":typeof root,root);const digests=new WeakMap<object,string>();const stack:Array<{value:object;visited:boolean}>=[{value:root as object,visited:false}];while(stack.length>0){const item=stack.pop()!;if(!item.visited){stack.push({value:item.value,visited:true});const values=Array.isArray(item.value)?item.value:Object.keys(item.value).map((key)=>(item.value as Record<string,unknown>)[key]);for(let index=values.length-1;index>=0;index-=1){const child=values[index];if(child!==null&&typeof child==="object")stack.push({value:child as object,visited:false});}}else if(Array.isArray(item.value)){const entries=item.value.map((child)=>child!==null&&typeof child==="object"?digests.get(child as object)!:scalarDigest(child===null?"null":typeof child,child));digests.set(item.value,arrayDigest(entries));}else{const entries=Object.keys(item.value).map((key)=>{const child=(item.value as Record<string,unknown>)[key];return[key,child!==null&&typeof child==="object"?digests.get(child as object)!:scalarDigest(child===null?"null":typeof child,child)] as const;});digests.set(item.value,objectDigest(entries));}}return digests.get(root as object)!;}
function deepFreeze(root:object):void{const stack:Array<{value:object;visited:boolean}>=[{value:root,visited:false}];const seen=new WeakSet<object>();while(stack.length>0){const item=stack.pop()!;if(item.visited){Object.freeze(item.value);continue;}if(seen.has(item.value))fail("json.snapshot-mismatch");seen.add(item.value);stack.push({value:item.value,visited:true});for(const descriptor of Object.values(Object.getOwnPropertyDescriptors(item.value)))if("value" in descriptor&&descriptor.value!==null&&typeof descriptor.value==="object")stack.push({value:descriptor.value as object,visited:false});}}

export function scanAndParseProviderJsonInternal(payloadUtf8:string,optionsValue:ProviderJsonScanOptions|undefined,deadline:RequestDeadlineInternal):ProviderJsonValueInternal{
  const limits=options(optionsValue);if(typeof payloadUtf8!=="string")fail("json.invalid-syntax");assertRequestDeadlineInternal(deadline);deadline.throwIfExpired();let index=0;let wireBytes=0;let nodes=0;let keys=0;let aggregate=0;let rootStarted=false;let rootDone=false;let rootContainer=false;let rootDigest="";const frames:Frame[]=[];
  const checkDeadline=()=>{assertRequestDeadlineInternal(deadline);deadline.throwIfExpired();};
  const checkObjectWire=()=>{for(const frame of frames)if(frame.kind==="object"){const bytes=wireBytes-frame.startByte;if(!Number.isSafeInteger(bytes)||bytes>limits.maxObjectWireBytes)fail("json.object-too-large");}};
  const rawWidth=(position:number):Readonly<{units:number;bytes:number}>=>{const first=payloadUtf8.charCodeAt(position);if(first<=0x7f)return{units:1,bytes:1};if(first<=0x7ff)return{units:1,bytes:2};if(first>=0xd800&&first<=0xdbff&&position+1<payloadUtf8.length&&payloadUtf8.charCodeAt(position+1)>=0xdc00&&payloadUtf8.charCodeAt(position+1)<=0xdfff)return{units:2,bytes:4};return{units:1,bytes:3};};
  const moveRaw=()=>{const width=rawWidth(index);const units=width.units;const bytes=width.bytes;const next=wireBytes+bytes;if(!Number.isSafeInteger(next)||next<wireBytes)fail("json.object-too-large");wireBytes=next;index+=units;checkObjectWire();};
  const moveAscii=(count:number)=>{for(let ordinal=0;ordinal<count;ordinal+=1){if(payloadUtf8.charCodeAt(index)>0x7f)fail("json.invalid-syntax");moveRaw();}};
  const parseHex4=():number=>{if(index+4>payloadUtf8.length)fail("json.invalid-escape");let value=0;for(let ordinal=0;ordinal<4;ordinal+=1){const unit=payloadUtf8.charCodeAt(index+ordinal);let digit:number;if(unit>=48&&unit<=57)digit=unit-48;else if(unit>=65&&unit<=70)digit=unit-55;else if(unit>=97&&unit<=102)digit=unit-87;else fail("json.invalid-escape");value=value*16+digit;}moveAscii(4);return value;};
  const addScalar=(value:unknown)=>{const bytes=canonicalScalarBytes(value);if(!Number.isSafeInteger(bytes)||bytes>limits.maxScalarCanonicalBytes)fail("json.scalar-too-large");const next=aggregate+bytes;if(!Number.isSafeInteger(next)||next<aggregate||next>limits.maxAggregateScalarBytes)fail("json.aggregate-scalars-too-large");aggregate=next;};
  const skipWhitespace=()=>{while(index<payloadUtf8.length){checkDeadline();const unit=payloadUtf8.charCodeAt(index);if(unit===32||unit===9||unit===10||unit===13)moveAscii(1);else break;}};
  const parseString=():string=>{if(payloadUtf8.charCodeAt(index)!==34)fail("json.invalid-syntax");moveAscii(1);const pieces:string[]=[];let stringCanonicalBytes=2;while(index<payloadUtf8.length){checkDeadline();const unit=payloadUtf8.charCodeAt(index);if(unit===34){moveAscii(1);return pieces.join("");}if(unit<32)fail("json.invalid-syntax");let text:string;if(unit===92){moveAscii(1);if(index>=payloadUtf8.length)fail("json.invalid-escape");const escaped=payloadUtf8.charCodeAt(index);moveAscii(1);if(escaped===34)text='"';else if(escaped===92)text="\\";else if(escaped===47)text="/";else if(escaped===98)text="\b";else if(escaped===102)text="\f";else if(escaped===110)text="\n";else if(escaped===114)text="\r";else if(escaped===116)text="\t";else if(escaped===117){const first=parseHex4();if(first>=0xd800&&first<=0xdbff){if(index+6>payloadUtf8.length||payloadUtf8.charCodeAt(index)!==92||payloadUtf8.charCodeAt(index+1)!==117)fail("json.invalid-surrogate");moveAscii(2);const second=parseHex4();if(second<0xdc00||second>0xdfff)fail("json.invalid-surrogate");text=String.fromCodePoint(0x10000+(first-0xd800)*0x400+(second-0xdc00));}else{if(first>=0xdc00&&first<=0xdfff)fail("json.invalid-surrogate");text=String.fromCharCode(first);}}else fail("json.invalid-escape");}else if(unit>=0xd800&&unit<=0xdbff){const low=payloadUtf8.charCodeAt(index+1);if(low<0xdc00||low>0xdfff)fail("json.invalid-surrogate");text=String.fromCharCode(unit,low);moveRaw();}else{if(unit>=0xdc00&&unit<=0xdfff)fail("json.invalid-surrogate");text=String.fromCharCode(unit);moveRaw();}const point=text.codePointAt(0)!;const added=point===34||point===92||point===8||point===9||point===10||point===12||point===13?2:point<32?6:utf8BytesForCodePoint(point);const next=stringCanonicalBytes+added;if(!Number.isSafeInteger(next)||next<stringCanonicalBytes||next>limits.maxScalarCanonicalBytes)fail("json.scalar-too-large");stringCanonicalBytes=next;pieces.push(text);}fail("json.invalid-syntax");};
  const completeValue=(digest:string)=>{if(frames.length===0){rootDigest=digest;rootDone=true;return;}const frame=frames[frames.length-1]!;if(frame.kind==="array")frame.entries.push(digest);else{if(frame.key===null)fail("json.invalid-syntax");frame.entries.push([frame.key,digest]);frame.key=null;}};
  const beginValue=()=>{nodes+=1;if(!Number.isSafeInteger(nodes)||nodes>limits.maxNodes)fail("json.nodes-exceeded");if(frames.length===0){if(rootStarted)fail("json.invalid-syntax");rootStarted=true;}else frames[frames.length-1]!.state="comma";};
  const parseValue=()=>{checkDeadline();beginValue();const unit=payloadUtf8.charCodeAt(index);if(unit===123||unit===91){rootContainer=rootContainer||frames.length===0;const depth=frames.length+1;if(depth>limits.maxDepth)fail("json.depth-exceeded");if(unit===123)frames.push({kind:"object",state:"first-key",startByte:wireBytes,key:null,seen:new Map(),entries:[]});else frames.push({kind:"array",state:"first-value",entries:[]});moveAscii(1);return;}if(unit===34){const value=parseString();addScalar(value);completeValue(scalarDigest("string",value));return;}for(const [literal,value] of [["true",true],["false",false],["null",null]] as const)if(payloadUtf8.startsWith(literal,index)){moveAscii(literal.length);addScalar(value);completeValue(scalarDigest(value===null?"null":typeof value,value));return;}const tokenStart=index;let tokenBytes=0;while(index<payloadUtf8.length&&!" \t\n\r,]}".includes(payloadUtf8[index]!)){checkDeadline();const width=rawWidth(index);const next=tokenBytes+width.bytes;if(!Number.isSafeInteger(next)||next<tokenBytes||next>limits.maxScalarCanonicalBytes)fail("json.scalar-too-large");tokenBytes=next;moveRaw();}if(index===tokenStart)fail("json.invalid-syntax");const token=payloadUtf8.slice(tokenStart,index);if(!/^-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?$/u.test(token)){if(token[0]==="-"||/[0-9]/u.test(token[0]??""))fail("json.invalid-number");fail("json.invalid-syntax");}const value=Number(token);if(!Number.isFinite(value))fail("json.invalid-number");addScalar(value);completeValue(scalarDigest("number",value));};
  while(true){checkDeadline();skipWhitespace();if(frames.length===0){if(rootDone){if(index!==payloadUtf8.length)fail("json.invalid-syntax");break;}parseValue();continue;}const frame=frames[frames.length-1]!;if(frame.kind==="object"){if(frame.state==="first-key"||frame.state==="key"){if(payloadUtf8.charCodeAt(index)===125){if(frame.state==="key")fail("json.invalid-syntax");moveAscii(1);const objectBytes=wireBytes-frame.startByte;if(!Number.isSafeInteger(objectBytes)||objectBytes>limits.maxObjectWireBytes)fail("json.object-too-large");frames.pop();completeValue(objectDigest(frame.entries));continue;}if(payloadUtf8.charCodeAt(index)!==34)fail("json.invalid-syntax");const key=parseString();keys+=1;if(!Number.isSafeInteger(keys)||keys>limits.maxKeys)fail("json.keys-exceeded");addScalar(key);const fingerprint=sha256Hex(canonicalJson(key));const matching=frame.seen.get(fingerprint);if(matching?.has(key))fail("json.duplicate-key");if(matching)matching.add(key);else frame.seen.set(fingerprint,new Set([key]));frame.key=key;frame.state="colon";continue;}if(frame.state==="colon"){if(payloadUtf8.charCodeAt(index)!==58)fail("json.invalid-syntax");moveAscii(1);frame.state="value";continue;}if(frame.state==="value"){parseValue();continue;}if(payloadUtf8.charCodeAt(index)===44){moveAscii(1);frame.state="key";continue;}if(payloadUtf8.charCodeAt(index)===125){moveAscii(1);const objectBytes=wireBytes-frame.startByte;if(!Number.isSafeInteger(objectBytes)||objectBytes>limits.maxObjectWireBytes)fail("json.object-too-large");frames.pop();completeValue(objectDigest(frame.entries));continue;}fail("json.invalid-syntax");}if(frame.state==="first-value"||frame.state==="value"){if(payloadUtf8.charCodeAt(index)===93){if(frame.state==="value")fail("json.invalid-syntax");moveAscii(1);frames.pop();completeValue(arrayDigest(frame.entries));continue;}parseValue();continue;}if(payloadUtf8.charCodeAt(index)===44){moveAscii(1);frame.state="value";continue;}if(payloadUtf8.charCodeAt(index)===93){moveAscii(1);frames.pop();completeValue(arrayDigest(frame.entries));continue;}fail("json.invalid-syntax");}
  if(!rootStarted||!rootDone)fail("json.invalid-syntax");if(!rootContainer)fail("transport.json-root-invalid");let parsed:unknown;try{parsed=JSON.parse(payloadUtf8);}catch{return fail("json.snapshot-mismatch");}if(parsed===null||typeof parsed!=="object"||utilTypes.isProxy(parsed))fail("json.snapshot-mismatch");try{assertBoundedStructure(parsed,{maxDepth:limits.maxDepth,maxNodes:limits.maxNodes,maxKeys:limits.maxKeys,maxArrayLength:limits.maxNodes,maxStringBytes:limits.maxScalarCanonicalBytes,maxScalarBytes:limits.maxAggregateScalarBytes});}catch{return fail("json.snapshot-mismatch");}if(graphDigest(parsed)!==rootDigest)fail("json.snapshot-mismatch");deepFreeze(parsed as object);roots.add(parsed as object);return parsed as ProviderJsonValueInternal;
}

export function snapshotProviderJsonInternal(value:ProviderJsonValueInternal):ProviderJsonRootSnapshotInternal{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!roots.has(value as object)||!Object.isFrozen(value))fail("json.snapshot-mismatch");return value as unknown as ProviderJsonRootSnapshotInternal;}
export {getProviderJsonSettlementInternal} from "./secure-json-transport-internal.js";
