import {types as utilTypes} from "node:util";
import {canonicalJson} from "../crypto/canonical-json.js";
import {sha256Hex} from "../crypto/hash.js";
import {normalizeDoi,normalizePmcid,normalizePmid} from "../scholarly/identifiers.js";
import {assertMetadataProviderAdapterInternal,getProviderExecutionResultInternal,type MetadataProviderAdapter,type ProviderExecutionResult} from "./providers/shared.js";
import {assertPubmedProviderAdapterInternal,type PubmedProviderAdapter} from "./providers/pubmed.js";
import {assertPmcProviderAdapterInternal,type PmcProviderAdapter} from "./providers/pmc.js";
import {assertNormalizedAcquisitionOptionsInternal,assertProviderRequestPartitionInternal,assertProviderRequestPartitionOwnedByInternal,closeProviderPartitionPlanOwnerInternal,createProviderPartitionKey,createProviderPartitionPlanOwnerInternal,registerProviderRequestPartitionInternal,type AcademicFetchInput,type AcademicSearchInput,type AcquisitionProvider,type NormalizedAcquisitionOptionsInternal,type ProviderNormalizedInput,type ProviderPartitionPlanOwnerInternal,type ProviderRequestPartitionInternal,type ProviderRequestPartitionSnapshotInternal} from "./contracts.js";

export type AcademicAcquisitionErrorCode="acquisition.invalid-options"|"acquisition.invalid-input"|"acquisition.invalid-capability"|"acquisition.too-many-queries"|"acquisition.query-too-large"|"acquisition.too-many-partitions"|"acquisition.cancelled"|"acquisition.deadline-exceeded"|"acquisition.security-failure"|"acquisition.sink-settlement-failure"|"acquisition.provider-failure"|"acquisition.result-too-large"|"acquisition.closed"|"acquisition.internal-contract";
export class AcademicAcquisitionError extends Error{readonly code:AcademicAcquisitionErrorCode;constructor(code:AcademicAcquisitionErrorCode){super(`Academic acquisition rejected (${code})`);this.code=code;this.name="AcademicAcquisitionError";}}
const fail=(code:AcademicAcquisitionErrorCode):never=>{throw new AcademicAcquisitionError(code);};
const plain=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==="object"&&!utilTypes.isProxy(value)&&Object.getPrototypeOf(value)===Object.prototype;
function descriptors(value:unknown,allowed:readonly string[],required:readonly string[]=allowed,code:AcademicAcquisitionErrorCode="acquisition.invalid-input"):PropertyDescriptorMap{if(!plain(value))fail(code);const d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(d);if(keys.some(key=>typeof key!=="string"||!allowed.includes(key))||required.some(key=>!d[key]))fail(code);for(const key of keys as string[])if(!d[key]!.enumerable||!("value" in d[key]!))fail(code);return d;}
function dense(value:unknown,maximum:number,code:AcademicAcquisitionErrorCode):readonly unknown[]{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)fail("acquisition.invalid-input");const length=Object.getOwnPropertyDescriptor(value,"length"),count=length&&"value" in length?length.value:null;if(typeof count!=="number"||!Number.isSafeInteger(count)||count<0)fail("acquisition.invalid-input");if(count>maximum)fail(code);const d=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(d).length!==count+1)fail("acquisition.invalid-input");const out:unknown[]=[];for(let i=0;i<count;i++){const item=d[String(i)];if(!item||!item.enumerable||!("value" in item))fail("acquisition.invalid-input");out.push(item.value);}return out;}
const freeze=<T>(value:T):Readonly<T>=>Object.freeze(value);
const capabilityStates=new WeakMap<object,AcquisitionPlanningCapabilitiesDescriptorInternal>();
const planStates=new WeakMap<object,PlanState>();
const reservationStates=new WeakMap<object,ReservationState>();
const factStates=new WeakMap<object,{parentPartitionKey:`partition-v1-${string}`;pmids:readonly string[];pmcids:readonly string[]}>();
const materializedPartitions=new WeakSet<object>();
const RESERVATION_TRANSITION_TOKEN=Symbol.for("pi-science-research.acquisition.reservation-transition.v1");

export interface AcquisitionPlanningCapabilitiesDescriptorInternal{readonly crossref:MetadataProviderAdapter;readonly openalex:MetadataProviderAdapter;readonly pubmed:PubmedProviderAdapter;readonly pmc:PmcProviderAdapter;}
export interface AcquisitionPlanningCapabilitiesInternal{readonly capabilityKind:"acquisition-planning-capabilities";}
export type AcquisitionInvocationInputInternal=Readonly<{operation:"search";raw:AcademicSearchInput}>|Readonly<{operation:"fetch";raw:AcademicFetchInput}>;
export type NormalizedAcquisitionInvocationInputInternal=Readonly<{operation:"search";normalizedQueries:readonly string[];providers:readonly("crossref"|"openalex"|"pubmed")[];requestedMaxResultsPerQuery:number;publicationTypes:readonly("journal-article"|"review"|"dataset"|"other")[];fromYear:number|null;toYear:number|null}>|Readonly<{operation:"fetch";identifierKind:"doi"|"pmid"|"pmcid";normalizedIdentifier:string}>;
export interface AcquisitionEffectiveProviderLimitInternal{readonly provider:AcquisitionProvider;readonly callerLimit:number;readonly configuredLimit:number;readonly endpointLimit:number;readonly effectiveLimit:number;}
export interface AcquisitionExecutionPlanSnapshotInternal{readonly input:NormalizedAcquisitionInvocationInputInternal;readonly options:NormalizedAcquisitionOptionsInternal;readonly effectiveProviderLimits:readonly AcquisitionEffectiveProviderLimitInternal[];readonly ownerCapacity:number;readonly diagnosticCapacity:number;readonly optionsSha256:string;}
export interface AuthenticatedAcquisitionExecutionPlanInternal{readonly capabilityKind:"authenticated-acquisition-execution-plan";readonly planId:`plan-v1-${string}`;}
export interface InvocationPlannedPartitionInternal{readonly ordinal:number;readonly partition:ProviderRequestPartitionInternal;readonly origin:string;}
export type ConditionalFutureOperationKindInternal="pubmed-esummary"|"pubmed-elink"|"pmc-bioc";export type ConditionalReservationStateInternal="reserved"|"materialized"|"skipped";
export interface ConditionalReservationSnapshotInternal{readonly reservationId:`reservation-v1-${string}`;readonly state:ConditionalReservationStateInternal;}
export interface ConditionalPartitionReservationInternal{readonly capabilityKind:"conditional-partition-reservation";readonly reservationId:`reservation-v1-${string}`;readonly parentPartitionKey:`partition-v1-${string}`;readonly parentPartitionKeySha256:string;readonly provider:"pubmed"|"pmc";readonly futureOperationKind:ConditionalFutureOperationKindInternal;readonly ordinal:number;readonly maxMaterializations:1;currentState():ConditionalReservationSnapshotInternal;}
export interface ConditionalMaterializationFactsInternal{readonly capabilityKind:"conditional-materialization-facts";readonly parentPartitionKey:`partition-v1-${string}`;readonly pmids:readonly string[];readonly pmcids:readonly string[];}
export type ConditionalMaterializationResultInternal=Readonly<{state:"materialized";partition:ProviderRequestPartitionInternal}>|Readonly<{state:"skipped";partition:null;reason:"no-identifiers"|"parent-failed"|"parent-blocked"}>;
type PlanState={snapshot:AcquisitionExecutionPlanSnapshotInternal;concrete:readonly InvocationPlannedPartitionInternal[];reservations:readonly ConditionalPartitionReservationInternal[];owner:ProviderPartitionPlanOwnerInternal;capabilities:AcquisitionPlanningCapabilitiesDescriptorInternal;consumed:boolean;closed:boolean};
type ReservationState={plan:AuthenticatedAcquisitionExecutionPlanInternal;state:ConditionalReservationStateInternal;futureParentKey:`partition-v1-${string}`|null;materialized:ProviderRequestPartitionInternal|null;skipReason:"no-identifiers"|"parent-failed"|"parent-blocked"|null};

export function createAcquisitionPlanningCapabilitiesInternal(value:AcquisitionPlanningCapabilitiesDescriptorInternal):AcquisitionPlanningCapabilitiesInternal{const d=descriptors(value,["crossref","openalex","pubmed","pmc"],undefined,"acquisition.invalid-capability");try{assertMetadataProviderAdapterInternal(d.crossref!.value);assertMetadataProviderAdapterInternal(d.openalex!.value);assertPubmedProviderAdapterInternal(d.pubmed!.value);assertPmcProviderAdapterInternal(d.pmc!.value);}catch{return fail("acquisition.invalid-capability");}if((d.crossref!.value as MetadataProviderAdapter).provider!=="crossref"||(d.openalex!.value as MetadataProviderAdapter).provider!=="openalex")fail("acquisition.invalid-capability");const cap=freeze({capabilityKind:"acquisition-planning-capabilities" as const});capabilityStates.set(cap,{crossref:d.crossref!.value as MetadataProviderAdapter,openalex:d.openalex!.value as MetadataProviderAdapter,pubmed:d.pubmed!.value as PubmedProviderAdapter,pmc:d.pmc!.value as PmcProviderAdapter});return cap;}
function capState(value:unknown):AcquisitionPlanningCapabilitiesDescriptorInternal{if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!Object.isFrozen(value))fail("acquisition.invalid-capability");const state=capabilityStates.get(value as object);if(!state)fail("acquisition.invalid-capability");return state!;}
function normalizedQueries(value:unknown,options:NormalizedAcquisitionOptionsInternal):readonly string[]{const raw=dense(value,options.maxQueries,"acquisition.too-many-queries"),normalized:string[]=[];let aggregate=0;for(const candidate of raw){if(typeof candidate!=="string")fail("acquisition.invalid-input");const item=candidate as string;if(item.length>options.maxCanonicalQueryBytes)fail("acquisition.query-too-large");let bytes:number;try{bytes=Buffer.byteLength(canonicalJson(item),"utf8");}catch{return fail("acquisition.invalid-input");}if(bytes>options.maxCanonicalQueryBytes)fail("acquisition.query-too-large");for(let i=0;i<item.length;i++){const unit=item.charCodeAt(i);if(unit<=31||unit===127||unit===0x61c||unit===0x200e||unit===0x200f||unit>=0x202a&&unit<=0x202e||unit>=0x2066&&unit<=0x2069)fail("acquisition.invalid-input");if(unit>=0xd800&&unit<=0xdbff){const next=item.charCodeAt(++i);if(next<0xdc00||next>0xdfff)fail("acquisition.invalid-input");}else if(unit>=0xdc00&&unit<=0xdfff)fail("acquisition.invalid-input");}let start=0,end=item.length;while(start<end&&item.charCodeAt(start)===32)start++;while(end>start&&item.charCodeAt(end-1)===32)end--;if(start===end)fail("acquisition.invalid-input");normalized.push(item.slice(start,end));aggregate+=bytes;if(!Number.isSafeInteger(aggregate))fail("acquisition.query-too-large");}let wrapper:number;try{wrapper=Buffer.byteLength(canonicalJson({queries:normalized}),"utf8");}catch{return fail("acquisition.invalid-input");}if(wrapper>options.maxTotalQueryBytes)fail("acquisition.query-too-large");normalized.sort((left,right)=>left<right?-1:left>right?1:0);return freeze(normalized.filter((item,index)=>index===0||item!==normalized[index-1]));}
function stringList<T extends string>(value:unknown,allowed:readonly T[],maximum:number,defaults:readonly T[]):readonly T[]{if(value===undefined)return freeze([...defaults]);const raw=dense(value,maximum,"acquisition.invalid-input"),out:T[]=[];for(const item of raw){if(typeof item!=="string"||!allowed.includes(item as T))fail("acquisition.invalid-input");if(!out.includes(item as T))out.push(item as T);}return freeze(out);}
function year(value:unknown):number|null{if(value===undefined)return null;if(typeof value!=="number"||!Number.isSafeInteger(value)||value<1||value>9999)fail("acquisition.invalid-input");return value as number;}
function endpoint(provider:AcquisitionProvider):number{return provider==="crossref"?1000:provider==="openalex"?200:provider==="pubmed"?10000:1;}
function snapshotFor(provider:"pubmed",kind:"pubmed-esummary"|"pubmed-elink",pmids:readonly string[]):ProviderRequestPartitionSnapshotInternal{const normalizedInput:ProviderNormalizedInput=kind==="pubmed-esummary"?freeze({kind:"pmid-list" as const,pmids:freeze([...pmids])}):freeze({kind:"pmid-link" as const,pmid:pmids[0]!}),url=kind==="pubmed-esummary"?`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=${encodeURIComponent(pmids.join(","))}&retmode=json`:`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?db=pmc&dbfrom=pubmed&id=${pmids[0]}&retmode=json`,key=createProviderPartitionKey({provider,operation:"fetch",endpointClass:kind,target:"ncbi",normalizedInput,requestedUrl:url});return freeze({provider,operation:"fetch",endpointClass:kind,...key,normalizedInput,normalizedInputSha256:sha256Hex(canonicalJson(normalizedInput)),target:"ncbi",url});}
function reservation(plan:AuthenticatedAcquisitionExecutionPlanInternal,parent:ProviderRequestPartitionSnapshotInternal,provider:"pubmed"|"pmc",kind:ConditionalFutureOperationKindInternal,ordinal:number,futureParentKey:`partition-v1-${string}`|null):ConditionalPartitionReservationInternal{const preimage={schemaVersion:1,parentPartitionKey:parent.partitionKey,parentPartitionKeySha256:parent.partitionKeySha256,provider,futureOperationKind:kind,ordinal,maxMaterializations:1},reservationId=`reservation-v1-${sha256Hex(canonicalJson(preimage))}` as const;let output:ConditionalPartitionReservationInternal;output=freeze({capabilityKind:"conditional-partition-reservation" as const,reservationId,parentPartitionKey:parent.partitionKey,parentPartitionKeySha256:parent.partitionKeySha256,provider,futureOperationKind:kind,ordinal,maxMaterializations:1 as const,currentState:()=>inspectConditionalReservationInternal(output)});reservationStates.set(output,{plan,state:"reserved",futureParentKey,materialized:null,skipReason:null});return output;}
export function planAcquisitionInvocation(input:AcquisitionInvocationInputInternal,normalizedOptions:NormalizedAcquisitionOptionsInternal,planningCapabilities:AcquisitionPlanningCapabilitiesInternal):AuthenticatedAcquisitionExecutionPlanInternal{try{assertNormalizedAcquisitionOptionsInternal(normalizedOptions);}catch{return fail("acquisition.invalid-capability");}const caps=capState(planningCapabilities),outer=descriptors(input,["operation","raw"]),operation=outer.operation!.value;if(operation!=="search"&&operation!=="fetch")fail("acquisition.invalid-input");let normalizedInput:NormalizedAcquisitionInvocationInputInternal,limits:AcquisitionEffectiveProviderLimitInternal[]=[],snapshots:ProviderRequestPartitionSnapshotInternal[]=[],reservationSpecs:{parent:ProviderRequestPartitionSnapshotInternal;provider:"pubmed"|"pmc";kind:ConditionalFutureOperationKindInternal;futureParentKey:`partition-v1-${string}`|null}[]=[];
 if(operation==="search"){const d=descriptors(outer.raw!.value,["queries","providers","maxResultsPerQuery","publicationTypes","fromYear","toYear"],["queries"]),queries=normalizedQueries(d.queries!.value,normalizedOptions),providers=stringList(d.providers?.value,["crossref","openalex","pubmed"],3,["crossref","openalex","pubmed"]),caller=d.maxResultsPerQuery?.value??normalizedOptions.maxResultsPerQuery;if(typeof caller!=="number"||!Number.isSafeInteger(caller)||caller<1)fail("acquisition.invalid-input");const publicationTypes=stringList(d.publicationTypes?.value,["journal-article","review","dataset","other"],4,[]),fromYear=year(d.fromYear?.value),toYear=year(d.toYear?.value);if(fromYear!==null&&toYear!==null&&fromYear>toYear)fail("acquisition.invalid-input");normalizedInput=freeze({operation:"search" as const,normalizedQueries:queries,providers:providers as readonly("crossref"|"openalex"|"pubmed")[],requestedMaxResultsPerQuery:caller,publicationTypes,fromYear,toYear});for(const provider of providers){const endpointLimit=endpoint(provider),effectiveLimit=Math.min(caller,normalizedOptions.maxResultsPerQuery,endpointLimit);limits.push(freeze({provider,callerLimit:caller,configuredLimit:normalizedOptions.maxResultsPerQuery,endpointLimit,effectiveLimit}));for(const query of queries){const built=provider==="crossref"?caps.crossref.buildSearchPartition({query,limit:effectiveLimit}):provider==="openalex"?caps.openalex.buildSearchPartition({query,limit:effectiveLimit}):caps.pubmed.buildSearchPartition({query,limit:effectiveLimit});snapshots.push(built);if(provider==="pubmed")reservationSpecs.push({parent:built,provider:"pubmed",kind:"pubmed-esummary",futureParentKey:null});}}}
 else{const d=descriptors(outer.raw!.value,["identifierKind","identifier"]),kind=d.identifierKind!.value,raw=d.identifier!.value;if(!["doi","pmid","pmcid"].includes(kind)||typeof raw!=="string"||raw.length>normalizedOptions.maxStringCanonicalBytes)fail("acquisition.invalid-input");let identifier:string;try{identifier=kind==="doi"?normalizeDoi(raw):kind==="pmid"?normalizePmid(raw):normalizePmcid(raw);}catch{return fail("acquisition.invalid-input");}normalizedInput=freeze({operation:"fetch" as const,identifierKind:kind as "doi"|"pmid"|"pmcid",normalizedIdentifier:identifier});if(kind==="doi"){for(const [provider,adapter] of [["crossref",caps.crossref],["openalex",caps.openalex]] as const){limits.push(freeze({provider,callerLimit:1,configuredLimit:1,endpointLimit:1,effectiveLimit:1}));snapshots.push(adapter.buildFetchPartition({identifierKind:"doi",identifier}));}}else if(kind==="pmid"){limits.push(freeze({provider:"pubmed",callerLimit:1,configuredLimit:1,endpointLimit:1,effectiveLimit:1}));const summary=caps.pubmed.buildFetchPartition({identifierKind:"pmid",identifier});snapshots.push(summary);const link=snapshotFor("pubmed","pubmed-elink",[identifier]);reservationSpecs.push({parent:summary,provider:"pubmed",kind:"pubmed-elink",futureParentKey:link.partitionKey},{parent:link,provider:"pmc",kind:"pmc-bioc",futureParentKey:null});}else{limits.push(freeze({provider:"pmc",callerLimit:1,configuredLimit:1,endpointLimit:1,effectiveLimit:1}));snapshots.push(caps.pmc.buildFetchPartition({identifierKind:"pmcid",identifier}));}}
 const ownerCapacity=snapshots.length+reservationSpecs.length,diagnosticCapacity=5*ownerCapacity+3;if(!Number.isSafeInteger(ownerCapacity)||ownerCapacity>normalizedOptions.maxPartitions||!Number.isSafeInteger(diagnosticCapacity)||diagnosticCapacity>normalizedOptions.maxCleanupDiagnostics||diagnosticCapacity>323)fail("acquisition.too-many-partitions");const planId=`plan-v1-${sha256Hex(canonicalJson({schemaVersion:1,input:normalizedInput,optionsSha256:normalizedOptions.optionsSha256,partitions:snapshots.map(x=>x.partitionKey),reservations:reservationSpecs.map(x=>[x.parent.partitionKey,x.kind])}))}` as const,owner=createProviderPartitionPlanOwnerInternal({planId,options:{maxPartitions:normalizedOptions.maxPartitions,maxCanonicalUrlBytes:normalizedOptions.transport.maxCanonicalUrlBytes,maxStructureDepth:normalizedOptions.maxStructureDepth,maxStructureNodes:normalizedOptions.maxStructureNodes,maxStructureKeys:normalizedOptions.maxStructureKeys,maxStringCanonicalBytes:normalizedOptions.maxStringCanonicalBytes,maxScalarCanonicalBytes:normalizedOptions.maxScalarCanonicalBytes}}),plan=freeze({capabilityKind:"authenticated-acquisition-execution-plan" as const,planId});try{const concrete=snapshots.map((item,ordinal)=>{const partition=registerProviderRequestPartitionInternal(owner,item);return freeze({ordinal,partition,origin:new URL(item.url).origin});}),reservations=reservationSpecs.map((item,index)=>reservation(plan,item.parent,item.provider,item.kind,snapshots.length+index,item.futureParentKey)),snapshot=freeze({input:normalizedInput,options:normalizedOptions,effectiveProviderLimits:freeze(limits),ownerCapacity,diagnosticCapacity,optionsSha256:normalizedOptions.optionsSha256});planStates.set(plan,{snapshot,concrete:freeze(concrete),reservations:freeze(reservations),owner,capabilities:caps,consumed:false,closed:false});return plan;}catch{closeProviderPartitionPlanOwnerInternal(owner);return fail("acquisition.internal-contract");}}
function state(plan:unknown):PlanState{if(plan===null||typeof plan!=="object"||utilTypes.isProxy(plan)||!Object.isFrozen(plan))fail("acquisition.invalid-capability");const found=planStates.get(plan as object);if(!found||found.closed)fail("acquisition.invalid-capability");return found!;}
export function getAcquisitionExecutionPlanSnapshotInternal(plan:AuthenticatedAcquisitionExecutionPlanInternal):AcquisitionExecutionPlanSnapshotInternal{return state(plan).snapshot;}
export function listInvocationConcretePartitionsInternal(plan:AuthenticatedAcquisitionExecutionPlanInternal):readonly InvocationPlannedPartitionInternal[]{return state(plan).concrete;}
export function listInvocationConditionalReservationsInternal(plan:AuthenticatedAcquisitionExecutionPlanInternal):readonly ConditionalPartitionReservationInternal[]{return state(plan).reservations;}
export function inspectConditionalReservationInternal(value:ConditionalPartitionReservationInternal):ConditionalReservationSnapshotInternal{if(arguments.length===5&&arguments[1]===RESERVATION_TRANSITION_TOKEN)return transitionConditionalReservation(value,arguments[2] as AuthenticatedAcquisitionExecutionPlanInternal,arguments[3] as ConditionalMaterializationFactsInternal|null,arguments[4] as "parent-failed"|"parent-blocked"|null) as never;if(value===null||typeof value!=="object"||utilTypes.isProxy(value)||!Object.isFrozen(value))fail("acquisition.internal-contract");const found=reservationStates.get(value as object);if(!found)fail("acquisition.internal-contract");return freeze({reservationId:value.reservationId,state:found!.state});}
export function createConditionalMaterializationFactsInternal(result:ProviderExecutionResult,parentPartitionKey:`partition-v1-${string}`):ConditionalMaterializationFactsInternal{let view;try{view=getProviderExecutionResultInternal(result);}catch{return fail("acquisition.internal-contract");}if(typeof parentPartitionKey!=="string"||!/^partition-v1-[a-f0-9]{64}$/u.test(parentPartitionKey))fail("acquisition.internal-contract");let pmids:string[]=[],pmcids:string[]=[];for(const fact of view.conditionalFacts)if(fact.parentPartitionKey===parentPartitionKey){if(fact.kind==="esearch-pmid-set")pmids=[...fact.pmids];else if(fact.kind==="esummary-pmid-metadata")pmids=fact.metadata.filter(x=>x.available).map(x=>x.pmid);else pmcids=[...fact.pmcids];}const output=freeze({capabilityKind:"conditional-materialization-facts" as const,parentPartitionKey,pmids:freeze(pmids),pmcids:freeze(pmcids)});factStates.set(output,{parentPartitionKey,pmids:output.pmids,pmcids:output.pmcids});return output;}
function transitionConditionalReservation(value:ConditionalPartitionReservationInternal,plan:AuthenticatedAcquisitionExecutionPlanInternal,facts:ConditionalMaterializationFactsInternal|null,reason:"parent-failed"|"parent-blocked"|null):ConditionalMaterializationResultInternal{const planState=state(plan),reservationState=reservationStates.get(value as object);if(!reservationState||reservationState.plan!==plan||reservationState.state!=="reserved")fail("acquisition.internal-contract");const reservationRecord=reservationState!;if(reason){reservationRecord.state="skipped";reservationRecord.skipReason=reason;for(const child of planState.reservations){const childState=reservationStates.get(child as object)!;if(childState.state==="reserved"&&child.parentPartitionKey===reservationRecord.futureParentKey){childState.state="skipped";childState.skipReason=reason;}}return freeze({state:"skipped" as const,partition:null,reason});}const fact=facts?factStates.get(facts as object):undefined;if(!fact||fact.parentPartitionKey!==value.parentPartitionKey)fail("acquisition.internal-contract");const materialization=fact!;let built:ProviderRequestPartitionSnapshotInternal|null=null;if(value.futureOperationKind==="pubmed-esummary"&&materialization.pmids.length)built=snapshotFor("pubmed","pubmed-esummary",materialization.pmids);else if(value.futureOperationKind==="pubmed-elink"&&materialization.pmids.length)built=snapshotFor("pubmed","pubmed-elink",[materialization.pmids[0]!]);else if(value.futureOperationKind==="pmc-bioc"&&materialization.pmcids.length)built=planState.capabilities.pmc.buildFetchPartition({identifierKind:"pmcid",identifier:materialization.pmcids[0]!});if(!built){reservationRecord.state="skipped";reservationRecord.skipReason="no-identifiers";return freeze({state:"skipped" as const,partition:null,reason:"no-identifiers" as const});}const partition=registerProviderRequestPartitionInternal(planState.owner,built);materializedPartitions.add(partition);reservationRecord.state="materialized";reservationRecord.materialized=partition;return freeze({state:"materialized" as const,partition});}
export function assertMaterializedProviderPartitionInternal(partition:ProviderRequestPartitionInternal):void{try{assertProviderRequestPartitionInternal(partition);}catch{return fail("acquisition.internal-contract");}if(!materializedPartitions.has(partition as object))fail("acquisition.internal-contract");}
