import {types as utilTypes} from "node:util";

import {canonicalJson} from "../../crypto/canonical-json.js";
import {sha256Hex} from "../../crypto/hash.js";
import {canonicalDoiUrl,normalizeCanonicalUrl,normalizeDoi} from "../../scholarly/identifiers.js";
import {assertBoundedStructure,StructuralLimitError} from "../../storage/bounded-structure.js";
import {createProviderPartitionKey,type AcademicAuthor,type AcquisitionTraceWarning,type ProviderRequestPartitionSnapshotInternal} from "../contracts.js";
import {
  ProviderAdapterError,
  providerEndpointResultCap,
  type MetadataProviderAdapter,
  type ProviderCandidateDraft,
  type ProviderParseOptions,
} from "./shared.js";
import {createCrossrefMetadataProviderAdapterInternal,type ProviderParsedMetadataFriendInternal} from "./provider-adapter-friend-internal.js";

const SELECT="DOI,URL,title,author,container-title,publisher,published-print,published-online,published,type,subtype";
const QUERY_MAX=4_096,URL_MAX=16_384;
function fail(code:"provider.invalid-input"|"provider.input-too-large"|"provider.invalid-response"|"provider.response-too-large"|"provider.normalization-failed"|"provider.unsupported-identifier"|"provider.identifier-mismatch"):never{throw new ProviderAdapterError(code);}
function plain(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==="object"&&!utilTypes.isProxy(value)&&Object.getPrototypeOf(value)===Object.prototype;}
function descriptors(value:unknown,allowed:readonly string[]):PropertyDescriptorMap{if(!plain(value))fail("provider.invalid-input");const output=Object.getOwnPropertyDescriptors(value);const keys=Reflect.ownKeys(output);if(keys.length!==allowed.length||keys.some((key)=>typeof key!=="string"||!allowed.includes(key)))fail("provider.invalid-input");for(const key of allowed){const item=output[key];if(!item||!item.enumerable||!("value" in item))fail("provider.invalid-input");}return output;}
function own(value:Record<string,unknown>,key:string):unknown{const d=Object.getOwnPropertyDescriptor(value,key);if(!d)return undefined;if(!d.enumerable||!("value" in d))fail("provider.invalid-response");return d.value;}
function dense(value:unknown,maximum:number,tooLarge="provider.invalid-response" as "provider.invalid-response"|"provider.response-too-large"):readonly unknown[]{if(value===null||typeof value!=="object")fail("provider.invalid-response");const object=value as object;if(utilTypes.isProxy(object)||!Array.isArray(object)||Object.getPrototypeOf(object)!==Array.prototype)fail("provider.invalid-response");const d=Object.getOwnPropertyDescriptors(object),ld=d["length"] as PropertyDescriptor|undefined,raw=ld&&"value" in ld?ld.value:null;if(typeof raw!=="number"||!Number.isSafeInteger(raw)||raw<0)fail("provider.invalid-response");if(raw>maximum)fail(tooLarge);if(Reflect.ownKeys(d).length!==raw+1)fail("provider.invalid-response");for(let i=0;i<raw;i++){const item=d[String(i)];if(!item||!item.enumerable||!("value" in item))fail("provider.invalid-response");}const output:unknown[]=new Array(raw);for(let i=0;i<raw;i++)output[i]=d[String(i)]!.value;return output;}
function freeze<T>(value:T):T{if(value!==null&&typeof value==="object"&&!Object.isFrozen(value)){for(const key of Reflect.ownKeys(value as object)){const d=Object.getOwnPropertyDescriptor(value as object,key);if(d&&"value" in d)freeze(d.value);}Object.freeze(value);}return value;}
function bytes(value:unknown,code:"provider.invalid-input"|"provider.input-too-large"|"provider.invalid-response"="provider.invalid-input"):number{try{return Buffer.byteLength(canonicalJson(value),"utf8");}catch{return fail(code);}}
function malformedUtf16(value:string):boolean{for(let i=0;i<value.length;i++){const unit=value.charCodeAt(i);if(unit>=0xd800&&unit<=0xdbff){if(i+1>=value.length)return true;const next=value.charCodeAt(i+1);if(next<0xdc00||next>0xdfff)return true;i++;}else if(unit>=0xdc00&&unit<=0xdfff)return true;}return false;}
function encode(value:string):string{if(malformedUtf16(value))fail("provider.invalid-input");return encodeURIComponent(value).replace(/[!'()*]/gu,(character)=>`%${character.charCodeAt(0).toString(16).toUpperCase()}`);}
function snapshot(operation:"search"|"fetch",normalizedInput:{kind:"query";query:string;limit:number}|{kind:"doi";doi:string},url:string):ProviderRequestPartitionSnapshotInternal{if(bytes(url,"provider.input-too-large")>URL_MAX)fail("provider.input-too-large");let key:Readonly<{partitionKey:`partition-v1-${string}`;partitionKeySha256:string}>;try{key=createProviderPartitionKey({provider:"crossref",operation,endpointClass:`crossref-${operation}`,target:"crossref",normalizedInput,requestedUrl:url});}catch{return fail("provider.normalization-failed");}return freeze({provider:"crossref" as const,operation,endpointClass:`crossref-${operation}`,...key,normalizedInput,normalizedInputSha256:sha256Hex(canonicalJson(normalizedInput)),target:"crossref" as const,url});}
function buildSearch(input:Readonly<{query:string;limit:number}>):ProviderRequestPartitionSnapshotInternal{const d=descriptors(input,["query","limit"]),query=d.query!.value,limit=d.limit!.value;if(typeof query!=="string"||query.length===0||typeof limit!=="number"||!Number.isSafeInteger(limit)||limit<1||limit>providerEndpointResultCap("crossref","search"))fail("provider.invalid-input");if(malformedUtf16(query))fail("provider.invalid-input");if(bytes(query,"provider.input-too-large")>QUERY_MAX)fail("provider.input-too-large");const parameters=[["query.bibliographic",query],["rows",String(limit)],["select",SELECT]].map(([name,value])=>[encode(name!),encode(value!)] as const).sort((a,b)=>a[0]===b[0]?(a[1]<b[1]?-1:a[1]>b[1]?1:0):a[0]<b[0]?-1:1);return snapshot("search",{kind:"query",query,limit},`https://api.crossref.org/works?${parameters.map(([name,value])=>`${name}=${value}`).join("&")}`);}
function buildFetch(input:Readonly<{identifierKind:"doi";identifier:string}>):ProviderRequestPartitionSnapshotInternal{const d=descriptors(input,["identifierKind","identifier"]);if(d.identifierKind!.value!=="doi")fail("provider.unsupported-identifier");const raw=d.identifier!.value;if(typeof raw!=="string")fail("provider.invalid-input");if(malformedUtf16(raw))fail("provider.invalid-input");if(bytes(raw,"provider.input-too-large")>URL_MAX)fail("provider.input-too-large");let doi:string;try{doi=normalizeDoi(raw,{maxCanonicalScalarBytes:16_384});}catch{return fail("provider.normalization-failed");}return snapshot("fetch",{kind:"doi",doi},`https://api.crossref.org/works/${encode(doi)}`);}
function preflightRoot(value:unknown,options:Readonly<Required<ProviderParseOptions>>):Record<string,unknown>{try{assertBoundedStructure(value,{maxDepth:options.maxStructureDepth,maxNodes:options.maxStructureNodes,maxKeys:options.maxStructureKeys,maxArrayLength:options.maxStructureNodes,maxStringBytes:options.maxStringCanonicalBytes,maxScalarBytes:options.maxScalarCanonicalBytes});}catch(error){if(error instanceof StructuralLimitError&&error.reason==="limit")fail("provider.response-too-large");fail("provider.invalid-response");}if(!plain(value))fail("provider.invalid-response");const rootBytes=bytes(value,"provider.invalid-response");if(rootBytes>options.maxExecutionCanonicalBytes||rootBytes>options.maxObjectWireBytes)fail("provider.response-too-large");return value;}
function record(value:unknown,options:Readonly<Required<ProviderParseOptions>>):Readonly<{value:Record<string,unknown>;bytes:number}>{if(!plain(value))fail("provider.invalid-response");const size=bytes(value,"provider.invalid-response");if(size>options.maxProviderRecordCanonicalBytes||size>options.maxObjectWireBytes)fail("provider.response-too-large");return{value,bytes:size};}
function optionalString(value:unknown):string|null{if(value===undefined||value===null)return null;if(typeof value!=="string")fail("provider.invalid-response");return value;}
function firstString(value:unknown,maximum:number):string|null{if(value===undefined||value===null)return null;const items=dense(value,maximum);let output:string|null=null;for(const item of items){if(typeof item!=="string")fail("provider.invalid-response");if(output===null&&item.length>0)output=item;}return output;}
function validDate(year:number,month=1,day=1):boolean{if(!Number.isSafeInteger(year)||year<1||year>9999||!Number.isSafeInteger(month)||month<1||month>12||!Number.isSafeInteger(day)||day<1)return false;return day<=new Date(Date.UTC(year,month,0)).getUTCDate();}
function published(item:Record<string,unknown>):Readonly<{date:string|null;precision:"day"|"month"|"year"|"unknown"}>{for(const key of ["published-print","published-online","published"]){const value=own(item,key);if(!plain(value))continue;let outer:readonly unknown[];try{outer=dense(own(value,"date-parts"),1);}catch{continue;}if(outer.length!==1)continue;let tuple:readonly unknown[];try{tuple=dense(outer[0],3);}catch{continue;}if(tuple.length<1)continue;const [year,month=1,day=1]=tuple;if(typeof year!=="number"||typeof month!=="number"||typeof day!=="number"||!validDate(year,month,day))continue;return freeze({date:tuple.length===1?String(year).padStart(4,"0"):tuple.length===2?`${String(year).padStart(4,"0")}-${String(month).padStart(2,"0")}`:`${String(year).padStart(4,"0")}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`,precision:tuple.length===1?"year":tuple.length===2?"month":"day"});}return freeze({date:null,precision:"unknown"});}
function normalizeOrcid(value:unknown):string|null{if(typeof value!=="string")return null;const bare=value.startsWith("https://orcid.org/")?value.slice(18):value;if(!/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/u.test(bare))return null;const compact=bare.replace(/-/gu,"");let total=0;for(let i=0;i<15;i++)total=(total+Number(compact[i]))*2;const check=(12-total%11)%11;if(compact[15]!==((check===10)?"X":String(check)))return null;return`https://orcid.org/${bare}`;}
function authors(value:unknown,options:Readonly<Required<ProviderParseOptions>>):readonly AcademicAuthor[]{if(value===undefined||value===null)return Object.freeze([]);const items=dense(value,options.maxAuthors,"provider.response-too-large");const output:AcademicAuthor[]=[];for(const entry of items){if(!plain(entry))fail("provider.invalid-response");const family=optionalString(own(entry,"family")),given=optionalString(own(entry,"given")),literal=optionalString(own(entry,"name"));output.push(freeze({family:literal===null?family:null,given:literal===null?given:null,literal,orcid:normalizeOrcid(own(entry,"ORCID"))}));}return Object.freeze(output);}
function warningOrdinal(operation:"search"|"fetch",ordinal:number):number|null{return operation==="search"?ordinal:null;}
function draft(value:unknown,ordinal:number,operation:"search"|"fetch",requestedDoi:string|null,options:Readonly<Required<ProviderParseOptions>>,warnings:AcquisitionTraceWarning[]):ProviderCandidateDraft{const measured=record(value,options),item=measured.value,recordOrdinal=warningOrdinal(operation,ordinal);let doi:string|null=null;const rawDoi=own(item,"DOI");if(rawDoi!==undefined&&rawDoi!==null){if(typeof rawDoi!=="string")fail("provider.invalid-response");if(rawDoi.length>0)try{doi=normalizeDoi(rawDoi,{maxCanonicalScalarBytes:16_384});}catch{warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal,field:"doi"});}}if(operation==="fetch"&&doi!==requestedDoi)fail("provider.identifier-mismatch");let landing:string|null=null;const rawUrl=own(item,"URL");if(rawUrl!==undefined&&rawUrl!==null&&rawUrl!==""){if(typeof rawUrl!=="string")fail("provider.invalid-response");try{landing=normalizeCanonicalUrl(rawUrl,{maxCanonicalScalarBytes:16_384});}catch{warnings.push({code:"provider.invalid-url-omitted",recordOrdinal,field:"URL"});}}const type=own(item,"type"),subtype=own(item,"subtype");if(type!==undefined&&typeof type!=="string"||subtype!==undefined&&typeof subtype!=="string")fail("provider.invalid-response");return freeze({draftOrdinal:ordinal,providerRecordId:doi,providerOrdinal:doi===null&&operation==="search"?ordinal:null,identifiers:{doi,pmid:null,pmcid:null},canonicalUrl:landing??(doi?canonicalDoiUrl(doi,{maxCanonicalScalarBytes:16_384}):null),title:firstString(own(item,"title"),Math.min(options.maxStructureNodes,measured.bytes)),authors:authors(own(item,"author"),options),containerTitle:firstString(own(item,"container-title"),Math.min(options.maxStructureNodes,measured.bytes)),publisher:optionalString(own(item,"publisher")),published:published(item),publicationType:subtype==="review"?"review":type==="journal-article"?"journal-article":type==="dataset"?"dataset":"other",accessLevel:"metadata-only",abstractText:null});}
function parse(operation:"search"|"fetch",rootValue:unknown,snapshotValue:ProviderRequestPartitionSnapshotInternal,options:Readonly<Required<ProviderParseOptions>>):ProviderParsedMetadataFriendInternal{const root=preflightRoot(rootValue,options);if(own(root,"status")!=="ok")fail("provider.invalid-response");const message=own(root,"message");let records:readonly unknown[];if(operation==="search"){if(!plain(message))fail("provider.invalid-response");records=dense(own(message,"items"),options.maxProviderRecords,"provider.response-too-large");if(snapshotValue.normalizedInput.kind!=="query"||records.length>snapshotValue.normalizedInput.limit)fail("provider.response-too-large");}else records=[message];const requestedDoi=snapshotValue.normalizedInput.kind==="doi"?snapshotValue.normalizedInput.doi:null;const warnings:AcquisitionTraceWarning[]=[],drafts:ProviderCandidateDraft[]=new Array(records.length);for(let i=0;i<records.length;i++)drafts[i]=draft(records[i],i,operation,requestedDoi,options,warnings);return freeze({drafts,warnings});}

export function createCrossrefAdapter():MetadataProviderAdapter{return createCrossrefMetadataProviderAdapterInternal({buildSearchPartition:buildSearch,buildFetchPartition:buildFetch,parse});}
