import {types as utilTypes} from "node:util";

import {canonicalJson} from "../../crypto/canonical-json.js";
import {sha256Hex} from "../../crypto/hash.js";
import {canonicalDoiUrl,normalizeCanonicalUrl,normalizeDoi,normalizePmcid,normalizePmid} from "../../scholarly/identifiers.js";
import {assertBoundedStructure,StructuralLimitError} from "../../storage/bounded-structure.js";
import {createProviderPartitionKey,type AcademicAuthor,type AcquisitionTraceWarning,type ProviderRequestPartitionSnapshotInternal} from "../contracts.js";
import {ProviderAdapterError,providerEndpointResultCap,type MetadataProviderAdapter,type ProviderCandidateDraft,type ProviderParseOptions} from "./shared.js";
import {createOpenAlexMetadataProviderAdapterInternal,type ProviderParsedMetadataFriendInternal} from "./provider-adapter-friend-internal.js";

const SELECT="id,doi,display_name,authorships,primary_location,publication_date,publication_year,type,abstract_inverted_index,ids";
const QUERY_MAX=4_096,URL_MAX=16_384;
function fail(code:"provider.invalid-input"|"provider.input-too-large"|"provider.invalid-response"|"provider.response-too-large"|"provider.normalization-failed"|"provider.unsupported-identifier"|"provider.identifier-mismatch"):never{throw new ProviderAdapterError(code);}
function plain(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==="object"&&!utilTypes.isProxy(value)&&Object.getPrototypeOf(value)===Object.prototype;}
function descriptors(value:unknown,allowed:readonly string[]):PropertyDescriptorMap{if(!plain(value))fail("provider.invalid-input");const output=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(output);if(keys.length!==allowed.length||keys.some((key)=>typeof key!=="string"||!allowed.includes(key)))fail("provider.invalid-input");for(const key of allowed){const item=output[key];if(!item||!item.enumerable||!("value" in item))fail("provider.invalid-input");}return output;}
function own(value:Record<string,unknown>,key:string):unknown{const d=Object.getOwnPropertyDescriptor(value,key);if(!d)return undefined;if(!d.enumerable||!("value" in d))fail("provider.invalid-response");return d.value;}
function dense(value:unknown,maximum:number,tooLarge="provider.invalid-response" as "provider.invalid-response"|"provider.response-too-large"):readonly unknown[]{if(value===null||typeof value!=="object")fail("provider.invalid-response");const object=value as object;if(utilTypes.isProxy(object)||!Array.isArray(object)||Object.getPrototypeOf(object)!==Array.prototype)fail("provider.invalid-response");const ld=Object.getOwnPropertyDescriptor(object,"length"),raw=ld&&"value" in ld?ld.value:null;if(typeof raw!=="number"||!Number.isSafeInteger(raw)||raw<0)fail("provider.invalid-response");if(raw>maximum)fail(tooLarge);const d=Object.getOwnPropertyDescriptors(object);if(Reflect.ownKeys(d).length!==raw+1)fail("provider.invalid-response");for(let i=0;i<raw;i++){const item=d[String(i)];if(!item||!item.enumerable||!("value" in item))fail("provider.invalid-response");}const output:unknown[]=new Array(raw);for(let i=0;i<raw;i++)output[i]=d[String(i)]!.value;return output;}
function arrayView(value:unknown,maximum:number):readonly unknown[]{if(value===null||typeof value!=="object")fail("provider.invalid-response");const object=value as object;if(utilTypes.isProxy(object)||!Array.isArray(object)||Object.getPrototypeOf(object)!==Array.prototype)fail("provider.invalid-response");const ld=Object.getOwnPropertyDescriptor(object,"length"),raw=ld&&"value" in ld?ld.value:null;if(typeof raw!=="number"||!Number.isSafeInteger(raw)||raw<0)fail("provider.invalid-response");if(raw>maximum)fail("provider.invalid-response");const d=Object.getOwnPropertyDescriptors(object);if(Reflect.ownKeys(d).length!==raw+1)fail("provider.invalid-response");for(let i=0;i<raw;i++){const item=d[String(i)];if(!item||!item.enumerable||!("value" in item))fail("provider.invalid-response");}return value as readonly unknown[];}
function freeze<T>(value:T):T{if(value!==null&&typeof value==="object"&&!Object.isFrozen(value)){for(const key of Reflect.ownKeys(value as object)){const d=Object.getOwnPropertyDescriptor(value as object,key);if(d&&"value" in d)freeze(d.value);}Object.freeze(value);}return value;}
function bytes(value:unknown,code:"provider.invalid-input"|"provider.input-too-large"|"provider.invalid-response"="provider.invalid-input"):number{try{return Buffer.byteLength(canonicalJson(value),"utf8");}catch{return fail(code);}}
function malformedUtf16(value:string):boolean{for(let i=0;i<value.length;i++){const unit=value.charCodeAt(i);if(unit>=0xd800&&unit<=0xdbff){if(i+1>=value.length)return true;const next=value.charCodeAt(i+1);if(next<0xdc00||next>0xdfff)return true;i++;}else if(unit>=0xdc00&&unit<=0xdfff)return true;}return false;}
function encode(value:string):string{if(malformedUtf16(value))fail("provider.invalid-input");return encodeURIComponent(value).replace(/[!'()*]/gu,(character)=>`%${character.charCodeAt(0).toString(16).toUpperCase()}`);}
function snapshot(operation:"search"|"fetch",normalizedInput:{kind:"query";query:string;limit:number}|{kind:"doi";doi:string},url:string):ProviderRequestPartitionSnapshotInternal{if(bytes(url,"provider.input-too-large")>URL_MAX)fail("provider.input-too-large");let key:Readonly<{partitionKey:`partition-v1-${string}`;partitionKeySha256:string}>;try{key=createProviderPartitionKey({provider:"openalex",operation,endpointClass:`openalex-${operation}`,target:"openalex",normalizedInput,requestedUrl:url});}catch{return fail("provider.normalization-failed");}return freeze({provider:"openalex" as const,operation,endpointClass:`openalex-${operation}`,...key,normalizedInput,normalizedInputSha256:sha256Hex(canonicalJson(normalizedInput)),target:"openalex" as const,url});}
function buildSearch(input:Readonly<{query:string;limit:number}>):ProviderRequestPartitionSnapshotInternal{const d=descriptors(input,["query","limit"]),query=d.query!.value,limit=d.limit!.value;if(typeof query!=="string"||query.length===0||typeof limit!=="number"||!Number.isSafeInteger(limit)||limit<1||limit>providerEndpointResultCap("openalex","search"))fail("provider.invalid-input");if(query.length>QUERY_MAX)fail("provider.input-too-large");if(malformedUtf16(query))fail("provider.invalid-input");if(bytes(query,"provider.input-too-large")>QUERY_MAX)fail("provider.input-too-large");const parameters=[["per-page",String(limit)],["search",query],["select",SELECT]].map(([name,value])=>[encode(name!),encode(value!)] as const).sort((a,b)=>a[0]===b[0]?(a[1]<b[1]?-1:a[1]>b[1]?1:0):a[0]<b[0]?-1:1);return snapshot("search",{kind:"query",query,limit},`https://api.openalex.org/works?${parameters.map(([name,value])=>`${name}=${value}`).join("&")}`);}
function buildFetch(input:Readonly<{identifierKind:"doi";identifier:string}>):ProviderRequestPartitionSnapshotInternal{const d=descriptors(input,["identifierKind","identifier"]);if(d.identifierKind!.value!=="doi")fail("provider.unsupported-identifier");const raw=d.identifier!.value;if(typeof raw!=="string")fail("provider.invalid-input");if(raw.length>URL_MAX)fail("provider.input-too-large");if(malformedUtf16(raw))fail("provider.invalid-input");if(bytes(raw,"provider.input-too-large")>URL_MAX)fail("provider.input-too-large");let doi:string;try{doi=normalizeDoi(raw,{maxCanonicalScalarBytes:16_384});}catch{return fail("provider.normalization-failed");}let resolver:string;try{resolver=canonicalDoiUrl(doi,{maxCanonicalScalarBytes:16_384});}catch{return fail("provider.input-too-large");}return snapshot("fetch",{kind:"doi",doi},`https://api.openalex.org/works/${encode(resolver)}`);}
function preflightRoot(value:unknown,options:Readonly<Required<ProviderParseOptions>>):Record<string,unknown>{try{assertBoundedStructure(value,{maxDepth:options.maxStructureDepth,maxNodes:options.maxStructureNodes,maxKeys:options.maxStructureKeys,maxArrayLength:options.maxStructureNodes,maxStringBytes:options.maxStringCanonicalBytes,maxScalarBytes:options.maxScalarCanonicalBytes});}catch(error){if(error instanceof StructuralLimitError&&error.reason==="limit")fail("provider.response-too-large");fail("provider.invalid-response");}if(!plain(value))fail("provider.invalid-response");const rootBytes=bytes(value,"provider.invalid-response");if(rootBytes>options.maxExecutionCanonicalBytes||rootBytes>options.maxObjectWireBytes)fail("provider.response-too-large");return value;}
function record(value:unknown,options:Readonly<Required<ProviderParseOptions>>):Readonly<{value:Record<string,unknown>;bytes:number}>{if(!plain(value))fail("provider.invalid-response");const size=bytes(value,"provider.invalid-response");if(size>options.maxProviderRecordCanonicalBytes||size>options.maxObjectWireBytes)fail("provider.response-too-large");return{value,bytes:size};}
function optionalString(value:unknown):string|null{if(value===undefined||value===null)return null;if(typeof value!=="string")fail("provider.invalid-response");return value;}
function validDate(year:number,month=1,day=1):boolean{if(!Number.isSafeInteger(year)||year<1||year>9999||!Number.isSafeInteger(month)||month<1||month>12||!Number.isSafeInteger(day)||day<1)return false;return day<=new Date(Date.UTC(year,month,0)).getUTCDate();}
function published(item:Record<string,unknown>):Readonly<{date:string|null;precision:"day"|"month"|"year"|"unknown"}>{const full=own(item,"publication_date");if(full!==undefined&&full!==null){if(typeof full!=="string")fail("provider.invalid-response");const match=full.match(/^(\d{4})-(\d{2})-(\d{2})$/u);if(match&&validDate(Number(match[1]),Number(match[2]),Number(match[3])))return freeze({date:full,precision:"day"});}const year=own(item,"publication_year");if(year!==undefined&&year!==null){if(typeof year!=="number")fail("provider.invalid-response");if(validDate(year))return freeze({date:String(year).padStart(4,"0"),precision:"year"});}return freeze({date:null,precision:"unknown"});}
function warningOrdinal(operation:"search"|"fetch",ordinal:number):number|null{return operation==="search"?ordinal:null;}
function acceptedDoi(value:unknown,field:"doi"|"ids.doi",ordinal:number|null,warnings:AcquisitionTraceWarning[]):string|null{if(value===undefined||value===null)return null;if(typeof value!=="string")fail("provider.invalid-response");if(value.length===0)return null;let candidate:string|null=null;if(value.startsWith("https://doi.org/")){try{candidate=normalizeDoi(value.slice(16),{maxCanonicalScalarBytes:16_384});}catch{/* omit */}}else if(!/^ *[a-z][a-z0-9+.-]*:/iu.test(value)){try{candidate=normalizeDoi(value,{maxCanonicalScalarBytes:16_384});}catch{/* omit */}}if(candidate===null)warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal:ordinal,field});return candidate;}
function acceptedPmid(value:unknown,ordinal:number|null,warnings:AcquisitionTraceWarning[]):string|null{if(value===undefined||value===null)return null;if(typeof value!=="string")fail("provider.invalid-response");if(value.length===0)return null;let raw=value;if(/^https:\/\/pubmed\.ncbi\.nlm\.nih\.gov\/\d+\/$/u.test(value))raw=value.slice(32,-1);else if(!/^\d+$/u.test(value)){warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal:ordinal,field:"ids.pmid"});return null;}try{return normalizePmid(raw);}catch{warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal:ordinal,field:"ids.pmid"});return null;}}
function acceptedPmcid(value:unknown,ordinal:number|null,warnings:AcquisitionTraceWarning[]):string|null{if(value===undefined||value===null)return null;if(typeof value!=="string")fail("provider.invalid-response");if(value.length===0)return null;let raw=value;if(/^https:\/\/www\.ncbi\.nlm\.nih\.gov\/pmc\/articles\/PMC\d+\/$/u.test(value))raw=value.slice(42,-1);else if(!/^PMC\d+$/u.test(value)){warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal:ordinal,field:"ids.pmcid"});return null;}try{return normalizePmcid(raw);}catch{warnings.push({code:"provider.invalid-identifier-omitted",recordOrdinal:ordinal,field:"ids.pmcid"});return null;}}
function authors(value:unknown,options:Readonly<Required<ProviderParseOptions>>):readonly AcademicAuthor[]{if(value===undefined||value===null)return Object.freeze([]);const items=dense(value,options.maxAuthors,"provider.response-too-large"),output:AcademicAuthor[]=[];for(const entry of items){if(!plain(entry))fail("provider.invalid-response");const author=own(entry,"author");if(!plain(author))fail("provider.invalid-response");const literal=own(author,"display_name");if(typeof literal!=="string")fail("provider.invalid-response");output.push(freeze({family:null,given:null,literal,orcid:null}));}return Object.freeze(output);}
function inverted(value:unknown,recordBytes:number,options:Readonly<Required<ProviderParseOptions>>):string|null{if(value===undefined||value===null)return null;if(!plain(value))fail("provider.invalid-response");const d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(d);for(const key of keys)if(typeof key!=="string")fail("provider.invalid-response");let count=0;for(const key of keys as string[]){const term=d[key]!;if(!term.enumerable||!("value" in term)||key.length===0)fail("provider.invalid-response");const ordinals=arrayView(term.value,Math.min(options.maxStructureNodes,recordBytes));count+=ordinals.length;if(!Number.isSafeInteger(count)||count>options.maxStructureNodes)fail("provider.response-too-large");for(let i=0;i<ordinals.length;i++){const position=ordinals[i];if(typeof position!=="number"||!Number.isSafeInteger(position)||position<0||position>=recordBytes)fail("provider.invalid-response");}}if(count===0)return null;const positions=new Map<number,string>();for(const key of keys as string[]){const ordinals=arrayView(d[key]!.value,Math.min(options.maxStructureNodes,recordBytes));for(let i=0;i<ordinals.length;i++){const position=ordinals[i] as number;if(positions.has(position))fail("provider.invalid-response");positions.set(position,key);}}for(let i=0;i<count;i++)if(!positions.has(i))fail("provider.invalid-response");const words:string[]=new Array(count);for(let i=0;i<count;i++)words[i]=positions.get(i)!;const text=words.join(" ");if(bytes(text,"provider.invalid-response")>options.maxProviderRecordCanonicalBytes)fail("provider.response-too-large");return text.length?text:null;}
function draft(value:unknown,ordinal:number,operation:"search"|"fetch",requestedDoi:string|null,options:Readonly<Required<ProviderParseOptions>>,warnings:AcquisitionTraceWarning[]):ProviderCandidateDraft{const measured=record(value,options),item=measured.value,recordOrdinal=warningOrdinal(operation,ordinal),id=own(item,"id");if(typeof id!=="string"||!/^https:\/\/openalex\.org\/W\d+$/u.test(id))fail("provider.invalid-response");const topDoi=acceptedDoi(own(item,"doi"),"doi",recordOrdinal,warnings);const idsValue=own(item,"ids");let ids:Record<string,unknown>|null=null;if(idsValue!==undefined&&idsValue!==null){if(!plain(idsValue))fail("provider.invalid-response");ids=idsValue;}const idsDoi=ids?acceptedDoi(own(ids,"doi"),"ids.doi",recordOrdinal,warnings):null,pmid=ids?acceptedPmid(own(ids,"pmid"),recordOrdinal,warnings):null,pmcid=ids?acceptedPmcid(own(ids,"pmcid"),recordOrdinal,warnings):null;if(topDoi&&idsDoi&&topDoi!==idsDoi)fail("provider.invalid-response");const doi=topDoi??idsDoi;if(operation==="fetch"&&doi!==requestedDoi)fail("provider.identifier-mismatch");const locationValue=own(item,"primary_location");let location:Record<string,unknown>|null=null;if(locationValue!==undefined&&locationValue!==null){if(!plain(locationValue))fail("provider.invalid-response");location=locationValue;}let landing:string|null=null;if(location){const raw=own(location,"landing_page_url");if(raw!==undefined&&raw!==null&&raw!==""){if(typeof raw!=="string")fail("provider.invalid-response");try{landing=normalizeCanonicalUrl(raw,{maxCanonicalScalarBytes:16_384});}catch{warnings.push({code:"provider.invalid-url-omitted",recordOrdinal,field:"primary_location.landing_page_url"});}}}let venue:string|null=null;if(location){const source=own(location,"source");if(source!==undefined&&source!==null){if(!plain(source))fail("provider.invalid-response");venue=optionalString(own(source,"display_name"));}}const type=own(item,"type");if(type!==undefined&&type!==null&&typeof type!=="string")fail("provider.invalid-response");const abstractText=inverted(own(item,"abstract_inverted_index"),measured.bytes,options);return freeze({draftOrdinal:ordinal,providerRecordId:id,providerOrdinal:null,identifiers:{doi,pmid,pmcid},canonicalUrl:landing??(doi?canonicalDoiUrl(doi,{maxCanonicalScalarBytes:16_384}):null),title:optionalString(own(item,"display_name")),authors:authors(own(item,"authorships"),options),containerTitle:venue,publisher:null,published:published(item),publicationType:type==="article"?"journal-article":type==="review"?"review":type==="dataset"?"dataset":"other",accessLevel:abstractText?"abstract-only":"metadata-only",abstractText});}
function parse(operation:"search"|"fetch",rootValue:unknown,snapshotValue:ProviderRequestPartitionSnapshotInternal,options:Readonly<Required<ProviderParseOptions>>):ProviderParsedMetadataFriendInternal{let records:readonly unknown[];if(operation==="search"){const root=preflightRoot(rootValue,options);records=dense(own(root,"results"),options.maxProviderRecords,"provider.response-too-large");if(snapshotValue.normalizedInput.kind!=="query"||records.length>snapshotValue.normalizedInput.limit)fail("provider.response-too-large");}else{preflightRoot(rootValue,options);records=[rootValue];}const requestedDoi=snapshotValue.normalizedInput.kind==="doi"?snapshotValue.normalizedInput.doi:null,warnings:AcquisitionTraceWarning[]=[],drafts:ProviderCandidateDraft[]=new Array(records.length);for(let i=0;i<records.length;i++)drafts[i]=draft(records[i],i,operation,requestedDoi,options,warnings);return freeze({drafts,warnings});}

export function createOpenAlexAdapter():MetadataProviderAdapter{return createOpenAlexMetadataProviderAdapterInternal({buildSearchPartition:buildSearch,buildFetchPartition:buildFetch,parse});}
